#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AdvancedWidgets

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


namespace SDK
{

// ScriptStruct AdvancedWidgets.ColorGradingSpinBoxStyle
// 0x02D8 (0x02E0 - 0x0008)
struct FColorGradingSpinBoxStyle final : public FSlateWidgetStyle
{
public:
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)
	struct FSlateBrush                            BorderBrush;                                       // 0x0010(0x00B0)
	struct FSlateBrush                            ActiveBorderBrush;                                 // 0x00C0(0x00B0)
	struct FSlateBrush                            HoveredBorderBrush;                                // 0x0170(0x00B0)
	struct FSlateBrush                            SelectorBrush;                                     // 0x0220(0x00B0)
	float                                         SelectorWidth;                                     // 0x02D0(0x0004)
	uint8                                         Pad_2D4[0xC];                                      // 0x02D4(0x000C)
};

}

