#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Bison_GroundConform_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "ControlRig_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Bison_GroundConform_AnimBP.Bison_GroundConform_AnimBP_C
// 0x0BB0 (0x0F80 - 0x03D0)
class UBison_GroundConform_AnimBP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3C8[0x8];                                      // 0x03C8(0x0008)
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03D8(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03E0(0x0008)
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x03E8(0x00C8)
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x04B0(0x0080)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x0530(0x0028)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x0558(0x0028)
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig;                          // 0x0580(0x04E0)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0A60(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0A80(0x0020)
	struct FAnimNode_MakeDynamicAdditive          AnimGraphNode_MakeDynamicAdditive;                 // 0x0AA0(0x0038)
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x0AD8(0x00C8)
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0BA0(0x0080)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x0C20(0x0028)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x0C48(0x0028)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x0C70(0x0020)
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0C90(0x00E8)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x0D78(0x0040)
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0DB8(0x0048)
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0E00(0x00B8)
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x0EB8(0x0048)
	struct FVector                                K2Node_PropertyAccess;                             // 0x0F00(0x0018)
	double                                        __CustomProperty_BabyScale_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F18(0x0008)
	bool                                          __CustomProperty_IsTorpid_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F20(0x0001)
	bool                                          __CustomProperty_bHasDynamicBase_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F21(0x0001)
	bool                                          __CustomProperty_GroundConform_IsFalling_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F22(0x0001)
	bool                                          __CustomProperty_GroundConform_Interpolate_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F23(0x0001)
	bool                                          __CustomProperty_Swimming_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F24(0x0001)
	bool                                          __CustomProperty_GroundConform_IsBeingDragged_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F25(0x0001)
	uint8                                         Pad_F26[0x2];                                      // 0x0F26(0x0002)
	struct FVector                                __CustomProperty_MeshScale_C1C9C347419C45FF622085A5BEBEBBC0; // 0x0F28(0x0018)
	bool                                          WasBeingDragged;                                   // 0x0F40(0x0001)
	uint8                                         Pad_F41[0x7];                                      // 0x0F41(0x0007)
	class UAnimInstance*                          AnimInstance;                                      // 0x0F48(0x0008)
	bool                                          Is_Being_Dragged;                                  // 0x0F50(0x0001)
	bool                                          bSwimmingMovement;                                 // 0x0F51(0x0001)
	bool                                          GroundConform_Interpolate;                         // 0x0F52(0x0001)
	bool                                          bFallingMovement;                                  // 0x0F53(0x0001)
	bool                                          Has_Dynamic_Base;                                  // 0x0F54(0x0001)
	bool                                          Is_Sleeping;                                       // 0x0F55(0x0001)
	bool                                          HasHitTheGroundOnce;                               // 0x0F56(0x0001)
	uint8                                         Pad_F57[0x1];                                      // 0x0F57(0x0001)
	class APrimalDinoCharacter*                   As_Primal_Dino_Character;                          // 0x0F58(0x0008)
	struct FVector                                WorldScale;                                        // 0x0F60(0x0018)
	bool                                          isTorpid;                                          // 0x0F78(0x0001)
	uint8                                         Pad_F79[0x3];                                      // 0x0F79(0x0003)
	float                                         BabyScale;                                         // 0x0F7C(0x0004)

public:
	void ExecuteUbergraph_Bison_GroundConform_AnimBP(int32 EntryPoint);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Bison_GroundConform_AnimBP_AnimGraphNode_TwoWayBlend_C7B59A6E466B8C0E925CFD9D980307C3();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Bison_GroundConform_AnimBP_AnimGraphNode_ApplyAdditive_3DE94F7145BC284A1A5878818C84A81F();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintThreadSafeUpdateAnimation(float DeltaTime);
	void BlueprintInitializeAnimation();
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Bison_GroundConform_AnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Bison_GroundConform_AnimBP_C")
	}
	static class UBison_GroundConform_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBison_GroundConform_AnimBP_C>();
	}
};

}

