#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BuoyancyData

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_BuoyancyData.BP_BuoyancyData_C
// 0x0050 (0x0120 - 0x00D0)
class UBP_BuoyancyData_C final : public UActorComponent
{
public:
	double                                        C_Buoyancy_Offset;                                 // 0x00D0(0x0008)
	double                                        C_Damping_Factor_1;                                // 0x00D8(0x0008)
	double                                        C_Damping_Factor_2;                                // 0x00E0(0x0008)
	double                                        C_Max_Force;                                       // 0x00E8(0x0008)
	double                                        C_Coefficient;                                     // 0x00F0(0x0008)
	double                                        C_Ocean_Waves_Drag;                                // 0x00F8(0x0008)
	double                                        C_Drag_Coefficient;                                // 0x0100(0x0008)
	double                                        C_Drag_Coefficient_2;                              // 0x0108(0x0008)
	double                                        C_Max_Drag_Speed;                                  // 0x0110(0x0008)
	double                                        C_Angular_Drag;                                    // 0x0118(0x0008)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_BuoyancyData_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_BuoyancyData_C")
	}
	static class UBP_BuoyancyData_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_BuoyancyData_C>();
	}
};

}

