#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_VFX_Wind_Explosion

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_VFX_Wind_Explosion.BP_VFX_Wind_Explosion_C
// 0x0098 (0x0528 - 0x0490)
class ABP_VFX_Wind_Explosion_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)
	class UBP_PrimalWindSourceComponent_Base_C*   BP_PrimalWindSourceComponent_Base;                 // 0x0498(0x0008)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04A0(0x0008)
	float                                         Timeline_NewTrack_1_ECC6D5AE4F6A12C617778A98B1A23356; // 0x04A8(0x0004)
	float                                         Timeline_NewTrack_0_ECC6D5AE4F6A12C617778A98B1A23356; // 0x04AC(0x0004)
	ETimelineDirection                            Timeline__Direction_ECC6D5AE4F6A12C617778A98B1A23356; // 0x04B0(0x0001)
	uint8                                         Pad_4B1[0x7];                                      // 0x04B1(0x0007)
	class UTimelineComponent*                     Timeline;                                          // 0x04B8(0x0008)
	float                                         Timeline_0_NewTrack_1_E9A77AF144570B1F010A67B192E2D9BA; // 0x04C0(0x0004)
	float                                         Timeline_0_NewTrack_0_E9A77AF144570B1F010A67B192E2D9BA; // 0x04C4(0x0004)
	ETimelineDirection                            Timeline_0__Direction_E9A77AF144570B1F010A67B192E2D9BA; // 0x04C8(0x0001)
	uint8                                         Pad_4C9[0x7];                                      // 0x04C9(0x0007)
	class UTimelineComponent*                     Timeline_0;                                        // 0x04D0(0x0008)
	float                                         Strength_C;                                        // 0x04D8(0x0004)
	float                                         Radius_Outer_C;                                    // 0x04DC(0x0004)
	struct FVector                                Location_C;                                        // 0x04E0(0x0018)
	bool                                          Do_A;                                              // 0x04F8(0x0001)
	bool                                          OnlyDoMPC;                                         // 0x04F9(0x0001)
	uint8                                         Pad_4FA[0x6];                                      // 0x04FA(0x0006)
	double                                        Strength_MPC;                                      // 0x0500(0x0008)
	int32                                         Do_This;                                           // 0x0508(0x0004)
	uint8                                         Pad_50C[0x4];                                      // 0x050C(0x0004)
	double                                        TimelineLength_C;                                  // 0x0510(0x0008)
	bool                                          NewVar;                                            // 0x0518(0x0001)
	uint8                                         Pad_519[0x7];                                      // 0x0519(0x0007)
	double                                        Plasticity_Amount_C;                               // 0x0520(0x0008)

public:
	void Timeline__UpdateFunc();
	void Timeline__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_VFX_Wind_Explosion(int32 EntryPoint);
	void Die();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_VFX_Wind_Explosion_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_VFX_Wind_Explosion_C")
	}
	static class ABP_VFX_Wind_Explosion_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_VFX_Wind_Explosion_C>();
	}
};

}

