#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPP_GiantBranch_D

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPP_GiantBranch_D.BPP_GiantBranch_D_C
// 0x0010 (0x0548 - 0x0538)
class ABPP_GiantBranch_D_C final : public APackedLevelActor
{
public:
	class UInstancedStaticMeshComponent*          InstancedStaticMesh1;                              // 0x0538(0x0008)
	class UInstancedStaticMeshComponent*          InstancedStaticMesh;                               // 0x0540(0x0008)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BPP_GiantBranch_D_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BPP_GiantBranch_D_C")
	}
	static class ABPP_GiantBranch_D_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABPP_GiantBranch_D_C>();
	}
};

}

