#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_BogSpiderBioGrappled

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.TryStruggle
// 0x0088 (0x0088 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_TryStruggle final
{
public:
	bool                                          success;                                           // 0x0000(0x0001)
	bool                                          retVal;                                            // 0x0001(0x0001)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0002(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0003(0x0001)
	bool                                          CallFunc_BPIsTamed_ReturnValue;                    // 0x0004(0x0001)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0008(0x0008)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0010(0x0008)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x0018(0x0001)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0020(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)
	bool                                          CallFunc_BPIsConscious_ReturnValue;                // 0x0029(0x0001)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)
	class AController*                            CallFunc_GetInstigatorController_ReturnValue;      // 0x0030(0x0008)
	class APlayerController*                      K2Node_DynamicCast_AsPlayer_Controller;            // 0x0038(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0041(0x0001)
	uint8                                         Pad_42[0x6];                                       // 0x0042(0x0006)
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0048(0x0008)
	double                                        CallFunc_SelectFloat_ReturnValue_1;                // 0x0050(0x0008)
	double                                        CallFunc_SelectFloat_ReturnValue_2;                // 0x0058(0x0008)
	double                                        CallFunc_RandomFloat_ReturnValue;                  // 0x0060(0x0008)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0068(0x0008)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0070(0x0001)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0078(0x0008)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0080(0x0001)
	bool                                          CallFunc_IsTimeSince_ReturnValue;                  // 0x0081(0x0001)
	uint8                                         Pad_82[0x2];                                       // 0x0082(0x0002)
	float                                         CallFunc_IsTimeSince_CheckTimeSince_ImplicitCast;  // 0x0084(0x0004)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.ToggleEnsnareVFX
// 0x0060 (0x0060 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_ToggleEnsnareVFX final
{
public:
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0000(0x0001)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)
	struct FStatusValueModifierDescription        K2Node_MakeStruct_StatusValueModifierDescription;  // 0x0008(0x0050)
	ENetworkModeResult                            CallFunc_CanRunCosmeticEvents_OutNetworkMode;      // 0x0058(0x0001)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0059(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.SyncGrapplingBogSpider
// 0x0010 (0x0010 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_SyncGrapplingBogSpider final
{
public:
	class ABogSpider_Character_BP_C*              SpiderRef;                                         // 0x0000(0x0008)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0008(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.StartMaterialTransition
// 0x0001 (0x0001 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_StartMaterialTransition final
{
public:
	bool                                          fwd;                                               // 0x0000(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.ReleaseBioGrapple
// 0x0001 (0x0001 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_ReleaseBioGrapple final
{
public:
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0000(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.OnEnsnared
// 0x0018 (0x0018 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_OnEnsnared final
{
public:
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0000(0x0001)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0008(0x0008)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0010(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.OnBioGrappled
// 0x0010 (0x0010 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_OnBioGrappled final
{
public:
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0000(0x0008)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0008(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.Multi_OnBioGrappleEvent
// 0x0001 (0x0001 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_Multi_OnBioGrappleEvent final
{
public:
	bool                                          bEnsnare;                                          // 0x0000(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.ExecuteUbergraph_Buff_BogSpiderBioGrappled
// 0x0090 (0x0090 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_ExecuteUbergraph_Buff_BogSpiderBioGrappled final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0004(0x0001)
	bool                                          CallFunc_TryStruggle_success;                      // 0x0005(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0006(0x0001)
	bool                                          K2Node_CustomEvent_bEnsnare;                       // 0x0007(0x0001)
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0008(0x0008)
	class ABogSpider_Character_BP_C*              K2Node_DynamicCast_AsBog_Spider_Character_BP;      // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0020(0x0008)
	bool                                          CallFunc_IsPrimalDino_ReturnValue;                 // 0x0028(0x0001)
	bool                                          K2Node_CustomEvent_Fwd;                            // 0x0029(0x0001)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0030(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	class UMaterialInstanceDynamic*               CallFunc_CreateDynamicMaterialInstance_ReturnValue; // 0x0040(0x0008)
	class UMaterialInstanceDynamic*               K2Node_DynamicCast_AsMaterial_Instance_Dynamic;    // 0x0048(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0050(0x0001)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character_1;           // 0x0058(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	class AActor*                                 K2Node_Event_ForInstigator;                        // 0x0068(0x0008)
	ENetworkModeResult                            CallFunc_CanRunCosmeticEvents_OutNetworkMode;      // 0x0070(0x0001)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0071(0x0001)
	uint8                                         Pad_72[0x6];                                       // 0x0072(0x0006)
	class AActor*                                 K2Node_Event_DamageCauser;                         // 0x0078(0x0008)
	ENetworkModeResult                            CallFunc_CanRunCosmeticEvents_OutNetworkMode_1;    // 0x0080(0x0001)
	bool                                          K2Node_SwitchEnum_CmpSuccess_1;                    // 0x0081(0x0001)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0088(0x0008)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BuffTickServer
// 0x0040 (0x0040 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BuffTickServer final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)
	bool                                          bShouldDeactivate;                                 // 0x0004(0x0001)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0008(0x0008)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_1;              // 0x0010(0x0008)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0018(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0028(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)
	bool                                          CallFunc_BPIsConscious_ReturnValue;                // 0x0031(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0032(0x0001)
	bool                                          CallFunc_BPIsTamed_ReturnValue;                    // 0x0033(0x0001)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0034(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0035(0x0001)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue;      // 0x0036(0x0001)
	bool                                          CallFunc_BPIsConscious_ReturnValue_1;              // 0x0037(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x0038(0x0001)
	bool                                          CallFunc_EqualEqual_ObjectObject_ReturnValue_1;    // 0x0039(0x0001)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x003A(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BuffTickClient
// 0x0048 (0x0048 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BuffTickClient final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0004(0x0001)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0008(0x0018)
	struct FLinearColor                           CallFunc_Conv_VectorToLinearColor_ReturnValue;     // 0x0020(0x0010)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	class UMaterialInstanceDynamic*               CallFunc_GetBuffPostprocessMaterial_ReturnValue;   // 0x0038(0x0008)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x0040(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPSetupForInstigator
// 0x0008 (0x0008 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPSetupForInstigator final
{
public:
	class AActor*                                 ForInstigator;                                     // 0x0000(0x0008)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPServerHandleNetExecCommand
// 0x0090 (0x0090 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPServerHandleNetExecCommand final
{
public:
	class APlayerController*                      FromPC;                                            // 0x0000(0x0008)
	class FName                                   CommandName;                                       // 0x0008(0x0008)
	struct FBPNetExecParams                       ExecParams;                                        // 0x0010(0x0078)
	bool                                          ReturnValue;                                       // 0x0088(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0089(0x0001)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x008A(0x0001)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue_1;        // 0x008B(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPLocalExecCommand
// 0x0088 (0x0088 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPLocalExecCommand final
{
public:
	class FName                                   CommandName;                                       // 0x0000(0x0008)
	struct FBPNetExecParams                       ExecParams;                                        // 0x0008(0x0078)
	bool                                          ReturnValue;                                       // 0x0080(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0081(0x0001)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x0082(0x0001)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue_1;        // 0x0083(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPInstigatorDied
// 0x0008 (0x0008 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPInstigatorDied final
{
public:
	class AActor*                                 DamageCauser;                                      // 0x0000(0x0008)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPHandleOnStartFire
// 0x0018 (0x0018 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPHandleOnStartFire final
{
public:
	bool                                          bFromGamepad;                                      // 0x0000(0x0001)
	bool                                          CallFunc_TryStruggle_success;                      // 0x0001(0x0001)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0008(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0011(0x0001)
	bool                                          CallFunc_BPIsA_ReturnValue;                        // 0x0012(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x0013(0x0001)
	bool                                          CallFunc_IsShooterCharacter_ReturnValue;           // 0x0014(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0015(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPHandleOnStartAltFire
// 0x0004 (0x0004 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPHandleOnStartAltFire final
{
public:
	bool                                          bFromGamepad;                                      // 0x0000(0x0001)
	bool                                          CallFunc_TryStruggle_success;                      // 0x0001(0x0001)
	bool                                          CallFunc_IsShooterCharacter_ReturnValue;           // 0x0002(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0003(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPGetHUDElements
// 0x0178 (0x0178 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPGetHUDElements final
{
public:
	class APlayerController*                      ForPC;                                             // 0x0000(0x0008)
	TArray<struct FHUDElement>                    OutElements;                                       // 0x0008(0x0010)
	TArray<struct FHUDElement>                    RetElements;                                       // 0x0018(0x0010)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	class UPrimalGameData*                        CallFunc_BPGetGameData_ReturnValue;                // 0x0030(0x0008)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0038(0x0008)
	class UObject*                                CallFunc_GetClassDefaultObject_ReturnValue;        // 0x0040(0x0008)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0048(0x0008)
	class UGlobalUIData_BP_C*                     K2Node_DynamicCast_AsGlobal_UIData_BP;             // 0x0050(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)
	int32                                         CallFunc_Round_ReturnValue;                        // 0x005C(0x0004)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0060(0x0010)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0070(0x0048)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x00B8(0x0010)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x00C8(0x0010)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00D8(0x0010)
	class FString                                 CallFunc_Concat_StrStr_ReturnValue;                // 0x00E8(0x0010)
	TArray<struct FHUDElement>                    CallFunc_BPGetHUDElements_Module_Struggle_Elements; // 0x00F8(0x0010)
	struct FHUDRichTextOverlayData                CallFunc_BPGetHUDElements_Module_Struggle_OutHUDRichTextOverlay; // 0x0108(0x0070)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPDeactivated
// 0x0058 (0x0058 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPDeactivated final
{
public:
	class AActor*                                 ForInstigator;                                     // 0x0000(0x0008)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0008(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)
	class APlayerController*                      CallFunc_GetOwnerController_ReturnValue;           // 0x0018(0x0008)
	class AShooterPlayerController*               K2Node_DynamicCast_AsShooter_Player_Controller;    // 0x0020(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	class AShooterHUD*                            CallFunc_GetShooterHUD_ReturnValue;                // 0x0030(0x0008)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0038(0x0001)
	ENetworkModeResult                            CallFunc_CanRunCosmeticEvents_OutNetworkMode;      // 0x0039(0x0001)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x003A(0x0001)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)
	class APlayerController*                      CallFunc_GetOwnerController_ReturnValue_1;         // 0x0040(0x0008)
	class APrimalBuff*                            CallFunc_StaticAddBuff_ReturnValue;                // 0x0048(0x0008)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x0050(0x0001)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_2;      // 0x0051(0x0001)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0052(0x0001)
};

// Function Buff_BogSpiderBioGrappled.Buff_BogSpiderBioGrappled_C.BPCheckPreventInput
// 0x0018 (0x0018 - 0x0000)
struct Buff_BogSpiderBioGrappled_C_BPCheckPreventInput final
{
public:
	EPrimalCharacterInputType                     inputType;                                         // 0x0000(0x0001)
	bool                                          ReturnValue;                                       // 0x0001(0x0001)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0002(0x0001)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0003(0x0001)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	double                                        CallFunc_GetGameTimeInSeconds_ReturnValue;         // 0x0008(0x0008)
	bool                                          CallFunc_IsTimeSince_ReturnValue;                  // 0x0010(0x0001)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)
	float                                         CallFunc_IsTimeSince_CheckTimeSince_ImplicitCast;  // 0x0014(0x0004)
};

}

