#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_ForceFlee_Base

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_ForceFlee_Base.Buff_ForceFlee_Base_C.Set Flee State
// 0x0070 (0x0070 - 0x0000)
struct Buff_ForceFlee_Base_C_Set_Flee_State final
{
public:
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0000(0x0008)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0008(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0011(0x0001)
	uint8                                         Pad_12[0x6];                                       // 0x0012(0x0006)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0018(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0028(0x0008)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController;     // 0x0030(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	class ADino_Character_BP_Climber_C*           K2Node_DynamicCast_AsDino_Character_BP_Climber;    // 0x0040(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0048(0x0001)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue;                // 0x0050(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0058(0x0001)
	bool                                          CallFunc_TamedProcessOrder_ReturnValue;            // 0x0059(0x0001)
	bool                                          CallFunc_BPIsTamed_ReturnValue;                    // 0x005A(0x0001)
	uint8                                         Pad_5B[0x5];                                       // 0x005B(0x0005)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character_1;           // 0x0060(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x0068(0x0001)
};

// Function Buff_ForceFlee_Base.Buff_ForceFlee_Base_C.Restore Flee State
// 0x0060 (0x0060 - 0x0000)
struct Buff_ForceFlee_Base_C_Restore_Flee_State final
{
public:
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0000(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0001(0x0001)
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0002(0x0001)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x0003(0x0001)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x0004(0x0001)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0008(0x0008)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue_1;            // 0x0010(0x0008)
	class UObject*                                CallFunc_GetDefaultObject_ReturnValue;             // 0x0018(0x0008)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0020(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character_1;      // 0x0030(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0038(0x0001)
	bool                                          CallFunc_TamedProcessOrder_ReturnValue;            // 0x0039(0x0001)
	bool                                          CallFunc_BPIsTamed_ReturnValue;                    // 0x003A(0x0001)
	uint8                                         Pad_3B[0x5];                                       // 0x003B(0x0005)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0040(0x0008)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController;     // 0x0048(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0050(0x0001)
	bool                                          CallFunc_BPIsTamed_ReturnValue_1;                  // 0x0051(0x0001)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue;                // 0x0058(0x0008)
};

// Function Buff_ForceFlee_Base.Buff_ForceFlee_Base_C.ReEnterFleeState
// 0x0050 (0x0050 - 0x0000)
struct Buff_ForceFlee_Base_C_ReEnterFleeState final
{
public:
	bool                                          CallFunc_IsServer_ReturnValue;                     // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	class FName                                   CallFunc_MakeLiteralName_ReturnValue;              // 0x0004(0x0008)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0020(0x0008)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController;     // 0x0028(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	class ADino_Character_BP_Climber_C*           K2Node_DynamicCast_AsDino_Character_BP_Climber;    // 0x0038(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class UBlackboardComponent*                   CallFunc_GetBlackboard_ReturnValue;                // 0x0048(0x0008)
};

// Function Buff_ForceFlee_Base.Buff_ForceFlee_Base_C.BPDeactivated
// 0x0020 (0x0020 - 0x0000)
struct Buff_ForceFlee_Base_C_BPDeactivated final
{
public:
	class AActor*                                 ForInstigator;                                     // 0x0000(0x0008)
	class AController*                            CallFunc_GetController_ReturnValue;                // 0x0008(0x0008)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController;     // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
};

// Function Buff_ForceFlee_Base.Buff_ForceFlee_Base_C.BPActivated
// 0x0010 (0x0010 - 0x0000)
struct Buff_ForceFlee_Base_C_BPActivated final
{
public:
	class AActor*                                 ForInstigator;                                     // 0x0000(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)
};

// Function Buff_ForceFlee_Base.Buff_ForceFlee_Base_C.BPCustomAllowAddBuff
// 0x0070 (0x0070 - 0x0000)
struct Buff_ForceFlee_Base_C_BPCustomAllowAddBuff final
{
public:
	class APrimalCharacter*                       ForCharacter;                                      // 0x0000(0x0008)
	class AActor*                                 DamageCauser;                                      // 0x0008(0x0008)
	bool                                          ReturnValue;                                       // 0x0010(0x0001)
	bool                                          CallFunc_BPCustomAllowAddBuff_ReturnValue;         // 0x0011(0x0001)
	uint8                                         Pad_12[0x2];                                       // 0x0012(0x0002)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0014(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0018(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)
	TSoftClassPtr<class UClass>                   CallFunc_Array_Get_Item;                           // 0x0020(0x0028)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0048(0x0004)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)
	TSubclassOf<class UObject>                    CallFunc_Conv_SoftClassReferenceToClass_ReturnValue; // 0x0050(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0058(0x0001)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)
	class UClass*                                 K2Node_ClassDynamicCast_AsPrimal_Buff;             // 0x0060(0x0008)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0068(0x0001)
	bool                                          CallFunc_HasBuff_ReturnValue;                      // 0x0069(0x0001)
};

}

