#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_State_SBear_RootBurst

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buff_State_Server_SBear_Base_classes.hpp"
#include "Struct_WeapAnimWith3P_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_State_SBear_RootBurst.Buff_State_SBear_RootBurst_C
// 0x00C0 (0x0D98 - 0x0CD8)
class ABuff_State_SBear_RootBurst_C : public ABuff_State_Server_SBear_Base_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Buff_State_SBear_RootBurst_C;       // 0x0CD8(0x0008)
	float                                         Timeline_NewTrack_0_34219163427495EA3147E2B8B02A2511; // 0x0CE0(0x0004)
	ETimelineDirection                            Timeline__Direction_34219163427495EA3147E2B8B02A2511; // 0x0CE4(0x0001)
	uint8                                         Pad_CE5[0x3];                                      // 0x0CE5(0x0003)
	class UTimelineComponent*                     Timeline;                                          // 0x0CE8(0x0008)
	class FString                                 land_string;                                       // 0x0CF0(0x0010)
	TArray<class USoundCue*>                      Entered_State_SFX_Sound_Cues;                      // 0x0D00(0x0010)
	TArray<struct FStruct_WeapAnimWith3P>         Entered_State_Animations;                          // 0x0D10(0x0010)
	TArray<class USoundCue*>                      Completed_State_SFX_Sound_Cues;                    // 0x0D20(0x0010)
	TArray<struct FStruct_WeapAnimWith3P>         Completed_State_Animations;                        // 0x0D30(0x0010)
	double                                        FOV_multiplier;                                    // 0x0D40(0x0008)
	float                                         distance_in_front_of_bear_to_spawn_thorn_AOE_origin; // 0x0D48(0x0004)
	uint8                                         Pad_D4C[0x4];                                      // 0x0D4C(0x0004)
	class UClass*                                 root_AOE_buff;                                     // 0x0D50(0x0008)
	float                                         delay_before_AOE_creation;                         // 0x0D58(0x0004)
	uint8                                         Pad_D5C[0x4];                                      // 0x0D5C(0x0004)
	class UClass*                                 Camera_Shake_Class;                                // 0x0D60(0x0008)
	float                                         Delay_before_camera_shake;                         // 0x0D68(0x0004)
	uint8                                         Pad_D6C[0x4];                                      // 0x0D6C(0x0004)
	class FString                                 jump_string;                                       // 0x0D70(0x0010)
	struct FRotator                               control_rotation_before_delay;                     // 0x0D80(0x0018)

public:
	void Timeline__UpdateFunc();
	void Timeline__FinishedFunc();
	void One_Time_Deactivation_Logic(class AActor* Instigator_0, bool Instigator_Is_Valid);
	void On_State_Begin(const struct FVector& Player_Held_Direction_In_World_Space, bool Debug_Enabled, bool Advanced_Debug_Enabled, bool Player_Is_FPV);
	void make_root_AOE();
	void ExecuteUbergraph_Buff_State_SBear_RootBurst(int32 EntryPoint);
	void Client_Tick(double Delta_Seconds);
	float BP_ModifyCharacterFOV(float inFOV);
	bool AllowPlayMontage(class UAnimMontage* Montage);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_State_SBear_RootBurst_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_State_SBear_RootBurst_C")
	}
	static class ABuff_State_SBear_RootBurst_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_State_SBear_RootBurst_C>();
	}
};

}

