#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_CannonHumanLaunch

#include "Basic.hpp"

#include "Buff_CannonHumanLaunch_classes.hpp"
#include "Buff_CannonHumanLaunch_parameters.hpp"


namespace SDK
{

// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.WeaponEquipped
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AShooterWeapon*                   Weapon                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_CannonHumanLaunch_C::WeaponEquipped(class AShooterWeapon* Weapon)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "WeaponEquipped");

	Params::Buff_CannonHumanLaunch_C_WeaponEquipped Parms{};

	Parms.Weapon = Weapon;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.ReceiveEndPlay
// (Event, Protected, BlueprintEvent)
// Parameters:
// EEndPlayReason                          EndPlayReason                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_CannonHumanLaunch_C::ReceiveEndPlay(EEndPlayReason EndPlayReason)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "ReceiveEndPlay");

	Params::Buff_CannonHumanLaunch_C_ReceiveEndPlay Parms{};

	Parms.EndPlayReason = EndPlayReason;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABuff_CannonHumanLaunch_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.ExecuteUbergraph_Buff_CannonHumanLaunch
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_CannonHumanLaunch_C::ExecuteUbergraph_Buff_CannonHumanLaunch(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "ExecuteUbergraph_Buff_CannonHumanLaunch");

	Params::Buff_CannonHumanLaunch_C_ExecuteUbergraph_Buff_CannonHumanLaunch Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.DeactivateGlidingVisuals
// (Public, BlueprintCallable, BlueprintEvent)

void ABuff_CannonHumanLaunch_C::DeactivateGlidingVisuals()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "DeactivateGlidingVisuals");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.BuffTickServer
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_CannonHumanLaunch_C::BuffTickServer(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "BuffTickServer");

	Params::Buff_CannonHumanLaunch_C_BuffTickServer Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.BPSetupForInstigator
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ForInstigator                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_CannonHumanLaunch_C::BPSetupForInstigator(class AActor* ForInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "BPSetupForInstigator");

	Params::Buff_CannonHumanLaunch_C_BPSetupForInstigator Parms{};

	Parms.ForInstigator = ForInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_CannonHumanLaunch.Buff_CannonHumanLaunch_C.BPNotifyOtherBuffActivated
// (Event, Public, BlueprintEvent)
// Parameters:
// class APrimalBuff*                      OtherBuff                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_CannonHumanLaunch_C::BPNotifyOtherBuffActivated(class APrimalBuff* OtherBuff)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_CannonHumanLaunch_C", "BPNotifyOtherBuffActivated");

	Params::Buff_CannonHumanLaunch_C_BPNotifyOtherBuffActivated Parms{};

	Parms.OtherBuff = OtherBuff;

	UObject::ProcessEvent(Func, &Parms);
}

}

