#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_SBear_SpiritTotem

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buff_Base_AoE_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_SBear_SpiritTotem.Buff_SBear_SpiritTotem_C
// 0x0298 (0x0E90 - 0x0BF8)
class ABuff_SBear_SpiritTotem_C final : public ABuff_Base_AoE_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Buff_SBear_SpiritTotem_C;           // 0x0BF8(0x0008)
	class UStaticMeshComponent*                   FX_Rock_Mound_01;                                  // 0x0C00(0x0008)
	class USkeletalMeshComponent*                 SK_SpiritBear_VFX;                                 // 0x0C08(0x0008)
	class UNiagaraComponent*                      NS_SpiritBear_Totem_Radius;                        // 0x0C10(0x0008)
	class USkeletalMeshComponent*                 SkeletalMesh;                                      // 0x0C18(0x0008)
	class UStaticMeshComponent*                   Sphere;                                            // 0x0C20(0x0008)
	class USphereComponent*                       AreaOfEffect;                                      // 0x0C28(0x0008)
	float                                         Timeline_0_track_70002BB84840D4BBD748B3859998C91E; // 0x0C30(0x0004)
	ETimelineDirection                            Timeline_0__Direction_70002BB84840D4BBD748B3859998C91E; // 0x0C34(0x0001)
	uint8                                         Pad_C35[0x3];                                      // 0x0C35(0x0003)
	class UTimelineComponent*                     Timeline_0;                                        // 0x0C38(0x0008)
	float                                         Timeline_NewTrack_0_A5E6AFBE45387AC9C21009973C051ED7; // 0x0C40(0x0004)
	ETimelineDirection                            Timeline__Direction_A5E6AFBE45387AC9C21009973C051ED7; // 0x0C44(0x0001)
	uint8                                         Pad_C45[0x3];                                      // 0x0C45(0x0003)
	class UTimelineComponent*                     Timeline;                                          // 0x0C48(0x0008)
	float                                         scale_radius_NewTrack_0_51838141473A24C1ECBAB1A8F77B7412; // 0x0C50(0x0004)
	ETimelineDirection                            scale_radius__Direction_51838141473A24C1ECBAB1A8F77B7412; // 0x0C54(0x0001)
	uint8                                         Pad_C55[0x3];                                      // 0x0C55(0x0003)
	class UTimelineComponent*                     scale_radius;                                      // 0x0C58(0x0008)
	double                                        LastTimeDidTrace;                                  // 0x0C60(0x0008)
	double                                        Nearby_Player_Trace_Check_Interval;                // 0x0C68(0x0008)
	ECollisionChannel                             Trace_Channel;                                     // 0x0C70(0x0001)
	uint8                                         Pad_C71[0x7];                                      // 0x0C71(0x0007)
	TSubclassOf<class APrimalBuff>                Nearby_Totem_Character_Teammate_Buff;              // 0x0C78(0x0008)
	uint8                                         Current_Stacks;                                    // 0x0C80(0x0001)
	uint8                                         Pad_C81[0x3];                                      // 0x0C81(0x0003)
	int32                                         Max_Possible_Stacks;                               // 0x0C84(0x0004)
	TSubclassOf<class APrimalBuff>                Nearby_Totem_Character_Enemy_Debuff;               // 0x0C88(0x0008)
	TSubclassOf<class UDamageType>                detonated_totem_damage_type;                       // 0x0C90(0x0008)
	class USoundBase*                             On_Detonate_Totem_Explosion_Sound;                 // 0x0C98(0x0008)
	float                                         detonated_totem_damage_at_1_stack;                 // 0x0CA0(0x0004)
	float                                         detonated_totem_damage_at_200_stacks;              // 0x0CA4(0x0004)
	class UNiagaraSystem*                         totem_detonate_explosion_niagara_vfx_template;     // 0x0CA8(0x0008)
	TSubclassOf<class APrimalBuff>                Bear_Empowered_Buff;                               // 0x0CB0(0x0008)
	int32                                         minimum_number_of_stacks_to_increase_in_size;      // 0x0CB8(0x0004)
	float                                         smaller_radius_when_under_100_stacks;              // 0x0CBC(0x0004)
	float                                         larger_radius_when_over_100_stacks;                // 0x0CC0(0x0004)
	float                                         detonated_totem_healing_at_1_stack;                // 0x0CC4(0x0004)
	float                                         detonated_totem_healing_at_200_stacks;             // 0x0CC8(0x0004)
	uint8                                         Pad_CCC[0x4];                                      // 0x0CCC(0x0004)
	double                                        Bear_Food_Stat;                                    // 0x0CD0(0x0008)
	struct FVector                                sphere_mesh_scale;                                 // 0x0CD8(0x0018)
	class UAnimationAsset*                        stage_1_animation;                                 // 0x0CF0(0x0008)
	class UAnimationAsset*                        stage_2_animation;                                 // 0x0CF8(0x0008)
	class UAnimationAsset*                        stage_3_animation;                                 // 0x0D00(0x0008)
	int32                                         current_stage;                                     // 0x0D08(0x0004)
	uint8                                         Pad_D0C[0x4];                                      // 0x0D0C(0x0004)
	class UNiagaraSystem*                         NS_TotemCharge;                                    // 0x0D10(0x0008)
	double                                        lerped_affecting_radius;                           // 0x0D18(0x0008)
	struct FVector                                Placed_Location;                                   // 0x0D20(0x0018)
	TArray<class UStaticMesh*>                    StaticMeshesArray;                                 // 0x0D38(0x0010)
	TArray<class UMaterialInstanceDynamic*>       CharacterDynamicMaterials;                         // 0x0D48(0x0010)
	TArray<class UMaterialInstanceDynamic*>       CharacterDynamicMaterials_Nanite;                  // 0x0D58(0x0010)
	float                                         delay_before_damaging_targets_via_detonation;      // 0x0D68(0x0004)
	uint8                                         Pad_D6C[0x4];                                      // 0x0D6C(0x0004)
	class FString                                 DelayDetonateDamage_name;                          // 0x0D70(0x0010)
	class AActor*                                 detonation_Requesting_Actor;                       // 0x0D80(0x0008)
	bool                                          Has_Detonated;                                     // 0x0D88(0x0001)
	uint8                                         Pad_D89[0x7];                                      // 0x0D89(0x0007)
	class UNiagaraSystem*                         totem_non_detonate_deactivate_niagara_vfx_template; // 0x0D90(0x0008)
	class USoundBase*                             On_non_Detonate_deactivate_Totem_Explosion_Sound;  // 0x0D98(0x0008)
	class FName                                   grow_name;                                         // 0x0DA0(0x0008)
	struct FLinearColor                           teammate_color_stage_initial;                      // 0x0DA8(0x0010)
	struct FLinearColor                           teammate_color_stage_2;                            // 0x0DB8(0x0010)
	struct FLinearColor                           teammate_color_stage_final;                        // 0x0DC8(0x0010)
	struct FLinearColor                           enemy_color_stage_initial;                         // 0x0DD8(0x0010)
	struct FLinearColor                           enemy_color_stage_2;                               // 0x0DE8(0x0010)
	struct FLinearColor                           enemy_color_stage_final;                           // 0x0DF8(0x0010)
	bool                                          is_enemy;                                          // 0x0E08(0x0001)
	bool                                          Debug;                                             // 0x0E09(0x0001)
	ETraceTypeQuery                               teleport_line_trace_check_channel_for_tek_shield;  // 0x0E0A(0x0001)
	uint8                                         Pad_E0B[0x5];                                      // 0x0E0B(0x0005)
	class FString                                 Function_Name;                                     // 0x0E10(0x0010)
	class UNiagaraSystem*                         Stage_Increase_Niagara_VFX;                        // 0x0E20(0x0008)
	struct FVector                                Totem_Line_of_Sight_LOS_trace_height;              // 0x0E28(0x0018)
	class USoundBase*                             stage_2_change_sound_cue_sfx;                      // 0x0E40(0x0008)
	class USoundBase*                             stage_end_sound_cue_sfx;                           // 0x0E48(0x0008)
	bool                                          Is_Detatched;                                      // 0x0E50(0x0001)
	uint8                                         Pad_E51[0x3];                                      // 0x0E51(0x0003)
	int32                                         recursive_depth;                                   // 0x0E54(0x0004)
	class FName                                   Color_name;                                        // 0x0E58(0x0008)
	class FName                                   stage_name;                                        // 0x0E60(0x0008)
	class FName                                   DissolvePercent_name;                              // 0x0E68(0x0008)
	double                                        Totem_Scale_At_Final_Stage;                        // 0x0E70(0x0008)
	double                                        Totem_Scale_at_stage_2;                            // 0x0E78(0x0008)
	class FName                                   radius_name;                                       // 0x0E80(0x0008)
	class FName                                   Stack_name;                                        // 0x0E88(0x0008)

public:
	void UserConstructionScript();
	void Timeline__UpdateFunc();
	void Timeline__FinishedFunc();
	void Timeline_0__UpdateFunc();
	void Timeline_0__FinishedFunc();
	struct FVector skeletal_mesh_location();
	void Set_Totem_Colors_On_Dynamic_Materials();
	void set_initial_totem_colors();
	void scale_radius__UpdateFunc();
	void scale_radius__FinishedFunc();
	void Restrict_Tick();
	void Restrict_Stack_Vfx();
	void RecusiveForceSetChildComponentLocations(class USceneComponent* Parent);
	void ReceiveBeginPlay();
	void PerformanceThrottledTick();
	void OnRep_Current_Stacks();
	void On_Set_Stage_to_3();
	void On_Set_Stage_to_2();
	void Multicast_Detonate();
	void lerp_scale_to_new_radius();
	void Lerp_Grow_Param();
	void Interface_Placed_Sprit_Totem_Set_Current_Stacks(int32 Override_Current_Stacks, int32* Current_Stacks_After_Attempted_Set);
	void Interface_Placed_Sprit_Totem_Get_Max_Possible_Stacks(int32* Max_Stacks);
	void Interface_Placed_Sprit_Totem_Get_Current_Stacks(int32* Current_Stacks_0);
	void Interface_Placed_Sprit_Totem_Get_Current_Radius(double* Radius);
	void Interface_Placed_Sprit_Totem_Detonate_Totem(class AActor* Requesting_Actor, bool* success);
	void initialize_totem(int32 Targeting_Team);
	void InitDynamicMats();
	void GetAllActorMeshes(class AActor* Target_0, TArray<class UMeshComponent*>* Meshes);
	struct FLinearColor Get_Totem_Color();
	void Get_Furthest_Sweeped_Valid_Spot_Trace_UsingChannel(const struct FVector& trace_start, const struct FVector& End_TP_Spot, const TArray<class AActor*>& ActorsToIgnore, ETraceTypeQuery TraceChannel, bool in_debug, bool* is_blocked_by_something, struct FVector* Validated_Spot);
	void Get_Furthest_Sweeped_Valid_Spot_Trace(const struct FVector& trace_start, const struct FVector& End_TP_Spot, const TArray<class AActor*>& ActorsToIgnore, bool in_debug, bool* Ret_Is_Blocked_By_Something, struct FVector* Validated_Spot);
	bool Get_All_Targets_Inside_Sphere(TArray<struct FHitResult>* OutHits);
	void fade_out();
	void ExecuteUbergraph_Buff_SBear_SpiritTotem(int32 EntryPoint);
	void Detach();
	void delay_fade_out();
	void Delay_Detonate_Damage();
	void Check_If_Character_Isn_t_Blocked_By_Something(TArray<struct FVector>& Additional_Trace_offsets, class ACharacter*& Target_0, bool* Character_Is_Blocked);
	void Can_Recieve_Totem_Debuff(class AActor* Actor, bool trace_if_blocked, bool force_trace, bool expensive_trace, bool* can_buff);
	void Can_Recieve_Totem_Buff(class AActor* Actor, bool trace_if_blocked, bool* can_buff);
	void BPSetupForInstigator(class AActor* ForInstigator);
	void BPDeactivated(class AActor* ForInstigator);
	void Apply_Buffs_To_Teammates_And_Enemies_Inside(class AActor* ForInstigator);
	void adjust_totem_appearance();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_SBear_SpiritTotem_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_SBear_SpiritTotem_C")
	}
	static class ABuff_SBear_SpiritTotem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_SBear_SpiritTotem_C>();
	}
};

}

