#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_State_SBear_HoldRT

#include "Basic.hpp"

#include "Struct_WeapAnimWith3P_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Buff_State_SBear_HoldRT.Buff_State_SBear_HoldRT_C.One Time Deactivation Logic
// 0x0010 (0x0010 - 0x0000)
struct Buff_State_SBear_HoldRT_C_One_Time_Deactivation_Logic final
{
public:
	class AActor*                                 Instigator_0;                                      // 0x0000(0x0008)
	bool                                          Instigator_Is_Valid;                               // 0x0008(0x0001)
};

// Function Buff_State_SBear_HoldRT.Buff_State_SBear_HoldRT_C.On State Begin
// 0x0020 (0x0020 - 0x0000)
struct Buff_State_SBear_HoldRT_C_On_State_Begin final
{
public:
	struct FVector                                Player_Held_Direction_In_World_Space;              // 0x0000(0x0018)
	bool                                          Debug_Enabled;                                     // 0x0018(0x0001)
	bool                                          Advanced_Debug_Enabled;                            // 0x0019(0x0001)
	bool                                          Player_Is_FPV;                                     // 0x001A(0x0001)
};

// Function Buff_State_SBear_HoldRT.Buff_State_SBear_HoldRT_C.ExecuteUbergraph_Buff_State_SBear_HoldRT
// 0x0150 (0x0150 - 0x0000)
struct Buff_State_SBear_HoldRT_C_ExecuteUbergraph_Buff_State_SBear_HoldRT final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0014(0x0004)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0018(0x0001)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x001C(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0020(0x0001)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x0024(0x0004)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_1;        // 0x0028(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0029(0x0001)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x002A(0x0001)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_2;        // 0x002B(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x002C(0x0001)
	uint8                                         Pad_2D[0x3];                                       // 0x002D(0x0003)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x0030(0x0004)
	bool                                          Temp_bool_True_if_break_was_hit_Variable_3;        // 0x0034(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue_3;                // 0x0035(0x0001)
	uint8                                         Pad_36[0x2];                                       // 0x0036(0x0002)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0038(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x003C(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x0040(0x0004)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)
	class USoundCue*                              CallFunc_Array_Get_Item;                           // 0x0048(0x0008)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0050(0x0001)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x0054(0x0004)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x005C(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x005D(0x0001)
	uint8                                         Pad_5E[0x2];                                       // 0x005E(0x0002)
	struct FStruct_WeapAnimWith3P                 CallFunc_Array_Get_Item_1;                         // 0x0060(0x0018)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0078(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x007C(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x007D(0x0001)
	uint8                                         Pad_7E[0x2];                                       // 0x007E(0x0002)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue;                // 0x0080(0x0008)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0088(0x0018)
	class USoundCue*                              CallFunc_Array_Get_Item_2;                         // 0x00A0(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x00A8(0x0004)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue_1;      // 0x00AC(0x0001)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x00AD(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x00AE(0x0001)
	uint8                                         Pad_AF[0x1];                                       // 0x00AF(0x0001)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_1;              // 0x00B0(0x0008)
	struct FStruct_WeapAnimWith3P                 CallFunc_Array_Get_Item_3;                         // 0x00B8(0x0018)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x00D0(0x0018)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x00E8(0x0004)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue_1;          // 0x00EC(0x0001)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x00ED(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x00EE(0x0001)
	bool                                          CallFunc_Is_Current_State_Still_Active_ReturnValue; // 0x00EF(0x0001)
	struct FVector                                K2Node_Event_Player_Held_Direction_In_World_Space; // 0x00F0(0x0018)
	bool                                          K2Node_Event_Debug_Enabled;                        // 0x0108(0x0001)
	bool                                          K2Node_Event_Advanced_Debug_Enabled;               // 0x0109(0x0001)
	bool                                          K2Node_Event_Player_Is_FPV;                        // 0x010A(0x0001)
	uint8                                         Pad_10B[0x5];                                      // 0x010B(0x0005)
	class AActor*                                 K2Node_Event_Instigator;                           // 0x0110(0x0008)
	bool                                          K2Node_Event_Instigator_Is_Valid;                  // 0x0118(0x0001)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)
	double                                        K2Node_Event_delta_seconds;                        // 0x0120(0x0008)
	class APawn*                                  CallFunc_GetInstigator_ReturnValue_2;              // 0x0128(0x0008)
	TScriptInterface<class IInterface_SpiritBear_C> K2Node_DynamicCast_AsInterface_Spirit_Bear;      // 0x0130(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0140(0x0001)
	bool                                          CallFunc_Interface_SpiritBear__Is_Totem_Placed_Totem_Is_Placed; // 0x0141(0x0001)
	uint8                                         Pad_142[0x6];                                      // 0x0142(0x0006)
	double                                        K2Node_VariableSet_FOV_multiplier_ImplicitCast;    // 0x0148(0x0008)
};

// Function Buff_State_SBear_HoldRT.Buff_State_SBear_HoldRT_C.Client Tick
// 0x0008 (0x0008 - 0x0000)
struct Buff_State_SBear_HoldRT_C_Client_Tick final
{
public:
	double                                        Delta_Seconds;                                     // 0x0000(0x0008)
};

// Function Buff_State_SBear_HoldRT.Buff_State_SBear_HoldRT_C.BP_ModifyCharacterFOV
// 0x0028 (0x0028 - 0x0000)
struct Buff_State_SBear_HoldRT_C_BP_ModifyCharacterFOV final
{
public:
	float                                         inFOV;                                             // 0x0000(0x0004)
	float                                         ReturnValue;                                       // 0x0004(0x0004)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0008(0x0008)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0010(0x0008)
	double                                        CallFunc_Multiply_DoubleDouble_A_ImplicitCast;     // 0x0018(0x0008)
	float                                         K2Node_FunctionResult_ReturnValue_ImplicitCast;    // 0x0020(0x0004)
};

// Function Buff_State_SBear_HoldRT.Buff_State_SBear_HoldRT_C.AllowPlayMontage
// 0x0028 (0x0028 - 0x0000)
struct Buff_State_SBear_HoldRT_C_AllowPlayMontage final
{
public:
	class UAnimMontage*                           Montage;                                           // 0x0000(0x0008)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)
	bool                                          CallFunc_Is_Current_State_Still_Active_ReturnValue; // 0x0009(0x0001)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)
	class FString                                 CallFunc_GetDisplayName_ReturnValue;               // 0x0010(0x0010)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	bool                                          CallFunc_Contains_ReturnValue;                     // 0x0021(0x0001)
};

}

