#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_HotbarReplacer

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_HotbarReplacer.Buff_HotbarReplacer_C
// 0x0000 (0x0C60 - 0x0C60)
class ABuff_HotbarReplacer_C : public APrimalBuff_HotbarReplacer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_HotbarReplacer_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_HotbarReplacer_C")
	}
	static class ABuff_HotbarReplacer_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_HotbarReplacer_C>();
	}
};

}

