#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Pinned

#include "Basic.hpp"

#include "Buff_Pinned_classes.hpp"
#include "Buff_Pinned_parameters.hpp"


namespace SDK
{

// Function Buff_Pinned.Buff_Pinned_C.ServerStruggle
// (Net, NetReliable, NetServer, BlueprintCallable, BlueprintEvent)

void ABuff_Pinned_C::ServerStruggle()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "ServerStruggle");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_Pinned.Buff_Pinned_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABuff_Pinned_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_Pinned.Buff_Pinned_C.PreventBlockingWithShield
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_Pinned_C::PreventBlockingWithShield()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "PreventBlockingWithShield");

	Params::Buff_Pinned_C_PreventBlockingWithShield Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_Pinned.Buff_Pinned_C.PlaySleepingAnim
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABuff_Pinned_C::PlaySleepingAnim()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "PlaySleepingAnim");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_Pinned.Buff_Pinned_C.InpActEvt_Fire_K2Node_InputActionEvent_0
// (BlueprintEvent)
// Parameters:
// const struct FKey&                      Key                                                    (BlueprintVisible, BlueprintReadOnly, Parm, HasGetValueTypeHash)

void ABuff_Pinned_C::InpActEvt_Fire_K2Node_InputActionEvent_0(const struct FKey& Key)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "InpActEvt_Fire_K2Node_InputActionEvent_0");

	Params::Buff_Pinned_C_InpActEvt_Fire_K2Node_InputActionEvent_0 Parms{};

	Parms.Key = std::move(Key);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Pinned.Buff_Pinned_C.InitBuff
// (BlueprintCallable, BlueprintEvent)

void ABuff_Pinned_C::InitBuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "InitBuff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_Pinned.Buff_Pinned_C.ExecuteUbergraph_Buff_Pinned
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_Pinned_C::ExecuteUbergraph_Buff_Pinned(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "ExecuteUbergraph_Buff_Pinned");

	Params::Buff_Pinned_C_ExecuteUbergraph_Buff_Pinned Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Pinned.Buff_Pinned_C.BuffTickServer
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_Pinned_C::BuffTickServer(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "BuffTickServer");

	Params::Buff_Pinned_C_BuffTickServer Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Pinned.Buff_Pinned_C.BPPreventFirstPerson
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_Pinned_C::BPPreventFirstPerson()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "BPPreventFirstPerson");

	Params::Buff_Pinned_C_BPPreventFirstPerson Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_Pinned.Buff_Pinned_C.BPDeactivated
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ForInstigator                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_Pinned_C::BPDeactivated(class AActor* ForInstigator)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "BPDeactivated");

	Params::Buff_Pinned_C_BPDeactivated Parms{};

	Parms.ForInstigator = ForInstigator;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Pinned.Buff_Pinned_C.BPCheckPreventInput
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPrimalCharacterInputType               inputType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_Pinned_C::BPCheckPreventInput(EPrimalCharacterInputType inputType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Pinned_C", "BPCheckPreventInput");

	Params::Buff_Pinned_C_BPCheckPreventInput Parms{};

	Parms.inputType = inputType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

