#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_SBear_Attk_Server_Base

#include "Basic.hpp"

#include "Buff_SBear_Attk_Server_Base_classes.hpp"
#include "Buff_SBear_Attk_Server_Base_parameters.hpp"


namespace SDK
{

// Function Buff_SBear_Attk_Server_Base.Buff_SBear_Attk_Server_Base_C.AllowPlayMontage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAnimMontage*                     Montage                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_SBear_Attk_Server_Base_C::AllowPlayMontage(class UAnimMontage* Montage)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_SBear_Attk_Server_Base_C", "AllowPlayMontage");

	Params::Buff_SBear_Attk_Server_Base_C_AllowPlayMontage Parms{};

	Parms.Montage = Montage;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

