#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_PreventInputMolerat

#include "Basic.hpp"


namespace SDK::Params
{

// Function Buff_PreventInputMolerat.Buff_PreventInputMolerat_C.BPSetupForInstigator
// 0x0018 (0x0018 - 0x0000)
struct Buff_PreventInputMolerat_C_BPSetupForInstigator final
{
public:
	class AActor*                                 ForInstigator;                                     // 0x0000(0x0008)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0008(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0011(0x0001)
};

// Function Buff_PreventInputMolerat.Buff_PreventInputMolerat_C.BPPreventFirstPerson
// 0x0001 (0x0001 - 0x0000)
struct Buff_PreventInputMolerat_C_BPPreventFirstPerson final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)
};

// Function Buff_PreventInputMolerat.Buff_PreventInputMolerat_C.BPDeactivated
// 0x0018 (0x0018 - 0x0000)
struct Buff_PreventInputMolerat_C_BPDeactivated final
{
public:
	class AActor*                                 ForInstigator;                                     // 0x0000(0x0008)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0008(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)
	bool                                          CallFunc_IsLocallyControlled_ReturnValue;          // 0x0011(0x0001)
};

}

