#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_PreventEncapsulated

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_PreventEncapsulated.Buff_PreventEncapsulated_C
// 0x0000 (0x0BE0 - 0x0BE0)
class ABuff_PreventEncapsulated_C final : public APrimalBuff
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_PreventEncapsulated_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_PreventEncapsulated_C")
	}
	static class ABuff_PreventEncapsulated_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_PreventEncapsulated_C>();
	}
};

}

