#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_AmmoContainerHelper

#include "Basic.hpp"

#include "AmmoCount_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.SyncHUDElements
// 0x0210 (0x0210 - 0x0000)
struct Buff_AmmoContainerHelper_C_SyncHUDElements final
{
public:
	struct FHUDElement                            TempHUDElement;                                    // 0x0000(0x01D8)
	TArray<class UClass*>                         CallFunc_GetAmmoInfo_AmmoTypeList;                 // 0x01D8(0x0010)
	TArray<int32>                                 CallFunc_GetAmmoInfo_AmmoCountList;                // 0x01E8(0x0010)
	TArray<struct FAmmoCount>                     CallFunc_GetAmmoInfo_AmmoCounts;                   // 0x01F8(0x0010)
	bool                                          CallFunc_NotEqual_ObjectObject_ReturnValue;        // 0x0208(0x0001)
	bool                                          CallFunc_IsOwningClient_ReturnValue;               // 0x0209(0x0001)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.ProvidedAmmoQuantity
// 0x0050 (0x0050 - 0x0000)
struct Buff_AmmoContainerHelper_C_ProvidedAmmoQuantity final
{
public:
	class APrimalStructureItemContainer*          TurretStructureItemContainer;                      // 0x0000(0x0008)
	class UClass*                                 AmmoItemTemplate;                                  // 0x0008(0x0008)
	int32                                         Quantity;                                          // 0x0010(0x0004)
	bool                                          AnyAmmoContainersInRange;                          // 0x0014(0x0001)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x0018)
	class APrimalStructureTurretBallista*         K2Node_DynamicCast_AsPrimal_Structure_Turret_Ballista; // 0x0030(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)
	int32                                         CallFunc_GetAllAmmoNearby_FinalQuantity;           // 0x003C(0x0004)
	bool                                          CallFunc_GetAllAmmoNearby_AnyAmmoContainersInRange; // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	double                                        CallFunc_GetAllAmmoNearby_Range_ImplicitCast;      // 0x0048(0x0008)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.GetAmmoInfo
// 0x0360 (0x0360 - 0x0000)
struct Buff_AmmoContainerHelper_C_GetAmmoInfo final
{
public:
	TArray<class UClass*>                         AmmoTypeList;                                      // 0x0000(0x0010)
	TArray<int32>                                 AmmoCountList;                                     // 0x0010(0x0010)
	TArray<struct FAmmoCount>                     AmmoCounts;                                        // 0x0020(0x0010)
	TArray<struct FAmmoCount>                     OutAmmoCounts;                                     // 0x0030(0x0010)
	TArray<class UClass*>                         OutAmmoTypes;                                      // 0x0040(0x0010)
	TArray<int32>                                 OutAmmoQuantity;                                   // 0x0050(0x0010)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0060(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0064(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0070(0x0018)
	class APrimalStructureItemContainer*          K2Node_DynamicCast_AsPrimal_Structure_Item_Container; // 0x0088(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0090(0x0001)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)
	class APrimalStructureTurretBallista*         K2Node_DynamicCast_AsPrimal_Structure_Turret_Ballista; // 0x0098(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00A0(0x0001)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x00A8(0x0018)
	class UClass*                                 CallFunc_Array_Get_Item;                           // 0x00C0(0x0008)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x00C8(0x0001)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)
	int32                                         CallFunc_GetAllAmmoNearby_FinalQuantity;           // 0x00CC(0x0004)
	bool                                          CallFunc_GetAllAmmoNearby_AnyAmmoContainersInRange; // 0x00D0(0x0001)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)
	struct FAmmoCount                             K2Node_MakeStruct_AmmoCount;                       // 0x00D8(0x0010)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip; // 0x00E8(0x0020)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0108(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x010C(0x0001)
	uint8                                         Pad_10D[0x3];                                      // 0x010D(0x0003)
	int32                                         CallFunc_Array_Add_ReturnValue_1;                  // 0x0110(0x0004)
	int32                                         CallFunc_GetItemTemplateQuantity_ReturnValue;      // 0x0114(0x0004)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_1; // 0x0118(0x0020)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0138(0x0001)
	uint8                                         Pad_139[0x7];                                      // 0x0139(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_2;        // 0x0140(0x0018)
	int32                                         CallFunc_GetAllAmmoNearby_FinalQuantity_1;         // 0x0158(0x0004)
	bool                                          CallFunc_GetAllAmmoNearby_AnyAmmoContainersInRange_1; // 0x015C(0x0001)
	uint8                                         Pad_15D[0x3];                                      // 0x015D(0x0003)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_2; // 0x0160(0x0020)
	int32                                         CallFunc_Array_Add_ReturnValue_2;                  // 0x0180(0x0004)
	uint8                                         Pad_184[0x4];                                      // 0x0184(0x0004)
	struct FAmmoCount                             K2Node_MakeStruct_AmmoCount_1;                     // 0x0188(0x0010)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_3; // 0x0198(0x0020)
	int32                                         CallFunc_Array_Add_ReturnValue_3;                  // 0x01B8(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue_4;                  // 0x01BC(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x01C0(0x0001)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_3;             // 0x01C1(0x0001)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_4;             // 0x01C2(0x0001)
	uint8                                         Pad_1C3[0x1];                                      // 0x01C3(0x0001)
	int32                                         CallFunc_Array_Add_ReturnValue_5;                  // 0x01C4(0x0004)
	class UClass*                                 K2Node_ClassDynamicCast_AsPrimal_Item;             // 0x01C8(0x0008)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x01D0(0x0001)
	bool                                          CallFunc_NotEqual_ClassClass_ReturnValue;          // 0x01D1(0x0001)
	uint8                                         Pad_1D2[0x6];                                      // 0x01D2(0x0006)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_4; // 0x01D8(0x0020)
	int32                                         CallFunc_Array_Add_ReturnValue_6;                  // 0x01F8(0x0004)
	int32                                         CallFunc_GetAllAmmoNearby_FinalQuantity_2;         // 0x01FC(0x0004)
	bool                                          CallFunc_GetAllAmmoNearby_AnyAmmoContainersInRange_2; // 0x0200(0x0001)
	uint8                                         Pad_201[0x7];                                      // 0x0201(0x0007)
	struct FAmmoCount                             K2Node_MakeStruct_AmmoCount_2;                     // 0x0208(0x0010)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_5; // 0x0218(0x0020)
	int32                                         CallFunc_Array_Add_ReturnValue_7;                  // 0x0238(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue_8;                  // 0x023C(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_5;             // 0x0240(0x0001)
	uint8                                         Pad_241[0x3];                                      // 0x0241(0x0003)
	int32                                         CallFunc_Array_Add_ReturnValue_9;                  // 0x0244(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue_10;                 // 0x0248(0x0004)
	uint8                                         Pad_24C[0x4];                                      // 0x024C(0x0004)
	class APrimalStructureTurret*                 K2Node_DynamicCast_AsPrimal_Structure_Turret;      // 0x0250(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0258(0x0001)
	uint8                                         Pad_259[0x7];                                      // 0x0259(0x0007)
	class AStructure_AmmoContainerBaseBP_C*       K2Node_DynamicCast_AsStructure_Ammo_Container_Base_BP; // 0x0260(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0268(0x0001)
	uint8                                         Pad_269[0x7];                                      // 0x0269(0x0007)
	class UClass*                                 CallFunc_Array_Get_Item_1;                         // 0x0270(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0278(0x0004)
	int32                                         CallFunc_BPGetQuantityOfItemWithoutCheckingInventory_ReturnValue; // 0x027C(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0280(0x0001)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)
	struct FAmmoCount                             K2Node_MakeStruct_AmmoCount_3;                     // 0x0288(0x0010)
	int32                                         CallFunc_Array_Add_ReturnValue_11;                 // 0x0298(0x0004)
	uint8                                         Pad_29C[0x4];                                      // 0x029C(0x0004)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_6; // 0x02A0(0x0020)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_6;             // 0x02C0(0x0001)
	uint8                                         Pad_2C1[0x3];                                      // 0x02C1(0x0003)
	int32                                         CallFunc_Array_Add_ReturnValue_12;                 // 0x02C4(0x0004)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_3;        // 0x02C8(0x0018)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_7; // 0x02E0(0x0020)
	int32                                         CallFunc_GetAllAmmoNearby_FinalQuantity_3;         // 0x0300(0x0004)
	bool                                          CallFunc_GetAllAmmoNearby_AnyAmmoContainersInRange_3; // 0x0304(0x0001)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_7;             // 0x0305(0x0001)
	uint8                                         Pad_306[0x2];                                      // 0x0306(0x0002)
	struct FAmmoCount                             K2Node_MakeStruct_AmmoCount_4;                     // 0x0308(0x0010)
	struct FItemToDisplayInStructureTooltip       K2Node_MakeStruct_ItemToDisplayInStructureTooltip_8; // 0x0318(0x0020)
	int32                                         CallFunc_Array_Add_ReturnValue_13;                 // 0x0338(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_8;             // 0x033C(0x0001)
	uint8                                         Pad_33D[0x3];                                      // 0x033D(0x0003)
	int32                                         CallFunc_Array_Add_ReturnValue_14;                 // 0x0340(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue_15;                 // 0x0344(0x0004)
	double                                        CallFunc_GetAllAmmoNearby_Range_ImplicitCast;      // 0x0348(0x0008)
	double                                        CallFunc_GetAllAmmoNearby_Range_ImplicitCast_1;    // 0x0350(0x0008)
	double                                        CallFunc_GetAllAmmoNearby_Range_ImplicitCast_2;    // 0x0358(0x0008)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.GetAmmoContainerIcon
// 0x0058 (0x0058 - 0x0000)
struct Buff_AmmoContainerHelper_C_GetAmmoContainerIcon final
{
public:
	class UTexture2D*                             Icon;                                              // 0x0000(0x0008)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0008(0x0008)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)
	class APlayerController*                      CallFunc_GetOwnerController_ReturnValue;           // 0x0020(0x0008)
	class AShooterPlayerController*               K2Node_DynamicCast_AsShooter_Player_Controller;    // 0x0028(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	class FString                                 CallFunc_StaticGetItemNameAndIcon_OutItemName;     // 0x0038(0x0010)
	class UTexture2D*                             CallFunc_StaticGetItemNameAndIcon_OutItemIcon;     // 0x0048(0x0008)
	bool                                          CallFunc_StaticGetItemNameAndIcon_ReturnValue;     // 0x0050(0x0001)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.GetAllAmmoNearby
// 0x0100 (0x0100 - 0x0000)
struct Buff_AmmoContainerHelper_C_GetAllAmmoNearby final
{
public:
	double                                        Range;                                             // 0x0000(0x0008)
	int32                                         InitialQuantity;                                   // 0x0008(0x0004)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)
	struct FVector                                StartingLocation;                                  // 0x0010(0x0018)
	class UClass*                                 AmmoClass;                                         // 0x0028(0x0008)
	class APrimalStructure*                       TurretToCheck;                                     // 0x0030(0x0008)
	int32                                         finalQuantity;                                     // 0x0038(0x0004)
	bool                                          AnyAmmoContainersInRange;                          // 0x003C(0x0001)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)
	TArray<double>                                Distances;                                         // 0x0040(0x0010)
	bool                                          bFoundValidAmmoContainer;                          // 0x0050(0x0001)
	uint8                                         Pad_51[0x3];                                       // 0x0051(0x0003)
	int32                                         RetQuantity;                                       // 0x0054(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0058(0x0004)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)
	TArray<class AActor*>                         CallFunc_ServerOctreeOverlapActorsBitMask_ReturnValue; // 0x0060(0x0010)
	class AActor*                                 CallFunc_Array_Get_Item;                           // 0x0070(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0078(0x0004)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)
	class AStructure_AmmoContainerBaseBP_C*       K2Node_DynamicCast_AsStructure_Ammo_Container_Base_BP; // 0x0080(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0088(0x0001)
	uint8                                         Pad_89[0x3];                                       // 0x0089(0x0003)
	int32                                         CallFunc_BPGetQuantityOfItemWithoutCheckingInventory_ReturnValue; // 0x008C(0x0004)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0090(0x0018)
	float                                         CallFunc_VectorDistance_ReturnValue;               // 0x00A8(0x0004)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x00AC(0x0001)
	uint8                                         Pad_AD[0x3];                                       // 0x00AD(0x0003)
	int32                                         CallFunc_MinOfFloatArray_IndexOfMinValue;          // 0x00B0(0x0004)
	float                                         CallFunc_MinOfFloatArray_MinValue;                 // 0x00B4(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00B8(0x0004)
	uint8                                         Pad_BC[0x4];                                       // 0x00BC(0x0004)
	class AActor*                                 CallFunc_Array_Get_Item_1;                         // 0x00C0(0x0008)
	class AStructure_AmmoContainerBaseBP_C*       K2Node_DynamicCast_AsStructure_Ammo_Container_Base_BP_1; // 0x00C8(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00D0(0x0001)
	uint8                                         Pad_D1[0x3];                                       // 0x00D1(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00D4(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00D8(0x0001)
	uint8                                         Pad_D9[0x3];                                       // 0x00D9(0x0003)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00DC(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00E0(0x0004)
	float                                         CallFunc_ServerOctreeOverlapActorsBitMask_Radius_ImplicitCast; // 0x00E4(0x0004)
	double                                        CallFunc_Array_Add_NewItem_ImplicitCast;           // 0x00E8(0x0008)
	TArray<float>                                 CallFunc_MinOfFloatArray_FloatArray_ImplicitCast;  // 0x00F0(0x0010)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.ExecuteUbergraph_Buff_AmmoContainerHelper
// 0x02C8 (0x02C8 - 0x0000)
struct Buff_AmmoContainerHelper_C_ExecuteUbergraph_Buff_AmmoContainerHelper final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	float                                         K2Node_Event_DeltaTime;                            // 0x0004(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0008(0x0008)
	class APrimalStructure*                       K2Node_DynamicCast_AsPrimal_Structure;             // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)
	class APlayerController*                      CallFunc_GetOwnerController_ReturnValue;           // 0x0020(0x0008)
	struct FVector                                CallFunc_GetPlayerViewPoint_Location;              // 0x0028(0x0018)
	struct FRotator                               CallFunc_GetPlayerViewPoint_Rotation;              // 0x0040(0x0018)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0058(0x0001)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)
	struct FVector                                CallFunc_GreaterGreater_VectorRotator_ReturnValue; // 0x0060(0x0018)
	struct FVector                                CallFunc_Add_VectorVector_ReturnValue;             // 0x0078(0x0018)
	class AActor*                                 CallFunc_GetOwner_ReturnValue_1;                   // 0x0090(0x0008)
	struct FHitResult                             CallFunc_VTraceSingleBP_OutHit;                    // 0x0098(0x0108)
	bool                                          CallFunc_VTraceSingleBP_ReturnValue;               // 0x01A0(0x0001)
	bool                                          CallFunc_BreakHitResult_bBlockingHit;              // 0x01A1(0x0001)
	bool                                          CallFunc_BreakHitResult_bInitialOverlap;           // 0x01A2(0x0001)
	uint8                                         Pad_1A3[0x1];                                      // 0x01A3(0x0001)
	float                                         CallFunc_BreakHitResult_Time;                      // 0x01A4(0x0004)
	float                                         CallFunc_BreakHitResult_Distance;                  // 0x01A8(0x0004)
	uint8                                         Pad_1AC[0x4];                                      // 0x01AC(0x0004)
	struct FVector                                CallFunc_BreakHitResult_Location;                  // 0x01B0(0x0018)
	struct FVector                                CallFunc_BreakHitResult_ImpactPoint;               // 0x01C8(0x0018)
	struct FVector                                CallFunc_BreakHitResult_Normal;                    // 0x01E0(0x0018)
	struct FVector                                CallFunc_BreakHitResult_ImpactNormal;              // 0x01F8(0x0018)
	class UPhysicalMaterial*                      CallFunc_BreakHitResult_PhysMat;                   // 0x0210(0x0008)
	class AActor*                                 CallFunc_BreakHitResult_HitActor;                  // 0x0218(0x0008)
	class UPrimitiveComponent*                    CallFunc_BreakHitResult_HitComponent;              // 0x0220(0x0008)
	class FName                                   CallFunc_BreakHitResult_HitBoneName;               // 0x0228(0x0008)
	class FName                                   CallFunc_BreakHitResult_BoneName;                  // 0x0230(0x0008)
	int32                                         CallFunc_BreakHitResult_HitItem;                   // 0x0238(0x0004)
	int32                                         CallFunc_BreakHitResult_ElementIndex;              // 0x023C(0x0004)
	int32                                         CallFunc_BreakHitResult_FaceIndex;                 // 0x0240(0x0004)
	uint8                                         Pad_244[0x4];                                      // 0x0244(0x0004)
	struct FVector                                CallFunc_BreakHitResult_TraceStart;                // 0x0248(0x0018)
	struct FVector                                CallFunc_BreakHitResult_TraceEnd;                  // 0x0260(0x0018)
	class APrimalStructureItemContainer*          K2Node_DynamicCast_AsPrimal_Structure_Item_Container; // 0x0278(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0280(0x0001)
	uint8                                         Pad_281[0x7];                                      // 0x0281(0x0007)
	class APrimalStructureItemContainer*          K2Node_DynamicCast_AsPrimal_Structure_Item_Container_1; // 0x0288(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0290(0x0001)
	uint8                                         Pad_291[0x7];                                      // 0x0291(0x0007)
	class APrimalStructureTurretBallista*         K2Node_DynamicCast_AsPrimal_Structure_Turret_Ballista; // 0x0298(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x02A0(0x0001)
	uint8                                         Pad_2A1[0x7];                                      // 0x02A1(0x0007)
	class APrimalStructureTurret*                 K2Node_DynamicCast_AsPrimal_Structure_Turret;      // 0x02A8(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x02B0(0x0001)
	uint8                                         Pad_2B1[0x7];                                      // 0x02B1(0x0007)
	class AStructure_AmmoContainerBaseBP_C*       K2Node_DynamicCast_AsStructure_Ammo_Container_Base_BP; // 0x02B8(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_5;                     // 0x02C0(0x0001)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.DrawBuffFloatingHUD
// 0x0020 (0x0020 - 0x0000)
struct Buff_AmmoContainerHelper_C_DrawBuffFloatingHUD final
{
public:
	int32                                         BuffIndex;                                         // 0x0000(0x0004)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	class AShooterHUD*                            HUD;                                               // 0x0008(0x0008)
	float                                         CenterX;                                           // 0x0010(0x0004)
	float                                         CenterY;                                           // 0x0014(0x0004)
	float                                         DrawScale;                                         // 0x0018(0x0004)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.CalculateWidgetLocation
// 0x0068 (0x0068 - 0x0000)
struct Buff_AmmoContainerHelper_C_CalculateWidgetLocation final
{
public:
	int32                                         SlotIndex;                                         // 0x0000(0x0004)
	int32                                         NumSlots;                                          // 0x0004(0x0004)
	struct FVector2D                              NewLocation;                                       // 0x0008(0x0010)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0018(0x0004)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x001C(0x0004)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0020(0x0008)
	double                                        CallFunc_BreakVector2D_X;                          // 0x0028(0x0008)
	double                                        CallFunc_BreakVector2D_Y;                          // 0x0030(0x0008)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0038(0x0008)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0040(0x0008)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x0048(0x0010)
	struct FVector2D                              CallFunc_Add_Vector2DVector2D_ReturnValue;         // 0x0058(0x0010)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.BuffTickClient
// 0x0004 (0x0004 - 0x0000)
struct Buff_AmmoContainerHelper_C_BuffTickClient final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)
};

// Function Buff_AmmoContainerHelper.Buff_AmmoContainerHelper_C.BPGetHUDElements
// 0x0068 (0x0068 - 0x0000)
struct Buff_AmmoContainerHelper_C_BPGetHUDElements final
{
public:
	class APlayerController*                      ForPC;                                             // 0x0000(0x0008)
	TArray<struct FHUDElement>                    OutElements;                                       // 0x0008(0x0010)
	TArray<struct FHUDElement>                    HudElements;                                       // 0x0018(0x0010)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	TArray<class UClass*>                         CallFunc_GetAmmoInfo_AmmoTypeList;                 // 0x0030(0x0010)
	TArray<int32>                                 CallFunc_GetAmmoInfo_AmmoCountList;                // 0x0040(0x0010)
	TArray<struct FAmmoCount>                     CallFunc_GetAmmoInfo_AmmoCounts;                   // 0x0050(0x0010)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0060(0x0001)
};

}

