#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_ForceFlee_Base

#include "Basic.hpp"

#include "Buff_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_ForceFlee_Base.Buff_ForceFlee_Base_C
// 0x0038 (0x0C28 - 0x0BF0)
class ABuff_ForceFlee_Base_C : public ABuff_Base_C
{
public:
	uint8                                         Pad_BE9[0x7];                                      // 0x0BE9(0x0007)
	class AActor*                                 RunAwayFrom;                                       // 0x0BF0(0x0008)
	bool                                          UnsetPassiveFlee;                                  // 0x0BF8(0x0001)
	uint8                                         Pad_BF9[0x7];                                      // 0x0BF9(0x0007)
	class APrimalCharacter*                       OldFollowTarget;                                   // 0x0C00(0x0008)
	int32                                         OldTamedAgressionLevel;                            // 0x0C08(0x0004)
	uint8                                         Pad_C0C[0x4];                                      // 0x0C0C(0x0004)
	class AActor*                                 OldWanderAroundActor;                              // 0x0C10(0x0008)
	TArray<TSoftClassPtr<class UClass>>           PreventAddingBuffClasses;                          // 0x0C18(0x0010)

public:
	void Set_Flee_State();
	void Restore_Flee_State();
	void ReEnterFleeState();
	void BPDeactivated(class AActor* ForInstigator);
	void BPActivated(class AActor* ForInstigator);

	bool BPCustomAllowAddBuff(class APrimalCharacter* ForCharacter, class AActor* DamageCauser) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_ForceFlee_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_ForceFlee_Base_C")
	}
	static class ABuff_ForceFlee_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_ForceFlee_Base_C>();
	}
};

}

