#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Pet_WarnOwnerOfDinos

#include "Basic.hpp"

#include "Buff_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_Pet_WarnOwnerOfDinos.Buff_Pet_WarnOwnerOfDinos_C
// 0x0000 (0x0BF0 - 0x0BF0)
class ABuff_Pet_WarnOwnerOfDinos_C final : public ABuff_Base_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_Pet_WarnOwnerOfDinos_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_Pet_WarnOwnerOfDinos_C")
	}
	static class ABuff_Pet_WarnOwnerOfDinos_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_Pet_WarnOwnerOfDinos_C>();
	}
};

}

