#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_BasedOnDesertKaiju

#include "Basic.hpp"

#include "Buff_Base_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_BasedOnDesertKaiju.Buff_BasedOnDesertKaiju_C
// 0x0008 (0x0BF8 - 0x0BF0)
class ABuff_BasedOnDesertKaiju_C final : public ABuff_Base_C
{
public:
	uint8                                         Pad_BE9[0x7];                                      // 0x0BE9(0x0007)
	double                                        CachedMaxWalkSpeed;                                // 0x0BF0(0x0008)

public:
	void BPDeactivated(class AActor* ForInstigator);
	void BPSetupForInstigator(class AActor* ForInstigator);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_BasedOnDesertKaiju_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_BasedOnDesertKaiju_C")
	}
	static class ABuff_BasedOnDesertKaiju_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_BasedOnDesertKaiju_C>();
	}
};

}

