#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_Mission_HuntDino

#include "Basic.hpp"

#include "Buff_Mission_HuntDino_classes.hpp"
#include "Buff_Mission_HuntDino_parameters.hpp"


namespace SDK
{

// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.SetFleeing
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   destination                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_Mission_HuntDino_C::SetFleeing(const struct FVector& destination)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "SetFleeing");

	Params::Buff_Mission_HuntDino_C_SetFleeing Parms{};

	Parms.destination = std::move(destination);

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.ReceiveBeginPlay
// (Event, Protected, BlueprintCallable, BlueprintEvent)

void ABuff_Mission_HuntDino_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.NotifyDamage
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DamageAmount                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UDamageType>          DamageClass                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// class AController*                      EventInstigator                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_Mission_HuntDino_C::NotifyDamage(float DamageAmount, TSubclassOf<class UDamageType> DamageClass, class AController* EventInstigator, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "NotifyDamage");

	Params::Buff_Mission_HuntDino_C_NotifyDamage Parms{};

	Parms.DamageAmount = DamageAmount;
	Parms.DamageClass = DamageClass;
	Parms.EventInstigator = EventInstigator;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.InitHuntBuff
// (Public, BlueprintCallable, BlueprintEvent)

void ABuff_Mission_HuntDino_C::InitHuntBuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "InitHuntBuff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.BuffOverrideFinalWanderLocation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FVector*                         outVec                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_Mission_HuntDino_C::BuffOverrideFinalWanderLocation(struct FVector* outVec)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "BuffOverrideFinalWanderLocation");

	Params::Buff_Mission_HuntDino_C_BuffOverrideFinalWanderLocation Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (outVec != nullptr)
		*outVec = std::move(Parms.outVec);

	return Parms.ReturnValue;
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.BuffAdjustDamage
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AController*                      EventInstigator                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TheDamageCauser                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UDamageType>          TheDamgeType                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ABuff_Mission_HuntDino_C::BuffAdjustDamage(float Damage, const struct FHitResult& HitInfo, class AController* EventInstigator, class AActor* TheDamageCauser, TSubclassOf<class UDamageType> TheDamgeType)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "BuffAdjustDamage");

	Params::Buff_Mission_HuntDino_C_BuffAdjustDamage Parms{};

	Parms.Damage = Damage;
	Parms.HitInfo = std::move(HitInfo);
	Parms.EventInstigator = EventInstigator;
	Parms.TheDamageCauser = TheDamageCauser;
	Parms.TheDamgeType = TheDamgeType;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.BPOverrideTargetingDesire
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           ForTarget                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   ForTargetingDesireValue                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ABuff_Mission_HuntDino_C::BPOverrideTargetingDesire(class AActor* ForTarget, float ForTargetingDesireValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "BPOverrideTargetingDesire");

	Params::Buff_Mission_HuntDino_C_BPOverrideTargetingDesire Parms{};

	Parms.ForTarget = ForTarget;
	Parms.ForTargetingDesireValue = ForTargetingDesireValue;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.BPInstigatorPossessed
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AController*                      ByController                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ABuff_Mission_HuntDino_C::BPInstigatorPossessed(class AController* ByController)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "BPInstigatorPossessed");

	Params::Buff_Mission_HuntDino_C_BPInstigatorPossessed Parms{};

	Parms.ByController = ByController;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_Mission_HuntDino.Buff_Mission_HuntDino_C.BPAdjustStatusValueModification
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPrimalCharacterStatusComponent*  ForComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// EPrimalCharacterStatusValue             ValueType                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   InAmount                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TSubclassOf<class UDamageType>          DamageTypeClass                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)
// bool                                    bManualModification                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ABuff_Mission_HuntDino_C::BPAdjustStatusValueModification(class UPrimalCharacterStatusComponent* ForComponent, EPrimalCharacterStatusValue ValueType, float InAmount, TSubclassOf<class UDamageType> DamageTypeClass, bool bManualModification)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_Mission_HuntDino_C", "BPAdjustStatusValueModification");

	Params::Buff_Mission_HuntDino_C_BPAdjustStatusValueModification Parms{};

	Parms.ForComponent = ForComponent;
	Parms.ValueType = ValueType;
	Parms.InAmount = InAmount;
	Parms.DamageTypeClass = DamageTypeClass;
	Parms.bManualModification = bManualModification;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

