#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_RootAOE_SBear

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buff_Base_AoE_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Buff_RootAOE_SBear.Buff_RootAOE_SBear_C
// 0x0188 (0x0D80 - 0x0BF8)
class ABuff_RootAOE_SBear_C : public ABuff_Base_AoE_C
{
public:
	class UBoxComponent*                          EndTraceLocation;                                  // 0x0BF8(0x0008)
	class UBoxComponent*                          StartTraceLocation;                                // 0x0C00(0x0008)
	class UBoxComponent*                          Box1;                                              // 0x0C08(0x0008)
	bool                                          TriedRoot;                                         // 0x0C10(0x0001)
	uint8                                         Pad_C11[0x7];                                      // 0x0C11(0x0007)
	double                                        LastTimeDidTrace;                                  // 0x0C18(0x0008)
	double                                        Root_Trace_Check_Interval;                         // 0x0C20(0x0008)
	ECollisionChannel                             Trace_Channel;                                     // 0x0C28(0x0001)
	uint8                                         Pad_C29[0x3];                                      // 0x0C29(0x0003)
	float                                         BaseFoliageDamage;                                 // 0x0C2C(0x0004)
	TSubclassOf<class APrimalBuff>                Rooted_Character_Debuff;                           // 0x0C30(0x0008)
	TArray<TSoftClassPtr<class UClass>>           blacklisted_foliage_that_root_burst_doesnt_work_on; // 0x0C38(0x0010)
	bool                                          Debug;                                             // 0x0C48(0x0001)
	uint8                                         Pad_C49[0x7];                                      // 0x0C49(0x0007)
	double                                        root_burst_MaximumHeightThreshold;                 // 0x0C50(0x0008)
	class UClass*                                 FoliageHarvestDamageType;                          // 0x0C58(0x0008)
	double                                        root_burst_MaximumHarvestHealthThreshold;          // 0x0C60(0x0008)
	double                                        travel_duration;                                   // 0x0C68(0x0008)
	bool                                          did_final_trace;                                   // 0x0C70(0x0001)
	uint8                                         Pad_C71[0x7];                                      // 0x0C71(0x0007)
	struct FVector                                Last_Trace_Location;                               // 0x0C78(0x0018)
	double                                        delay_before_traces;                               // 0x0C90(0x0008)
	class UClass*                                 wind_source_class;                                 // 0x0C98(0x0008)
	TSoftClassPtr<class UClass>                   forest_kaiju_Class;                                // 0x0CA0(0x0028)
	TSoftClassPtr<class UClass>                   ice_kaiju_class;                                   // 0x0CC8(0x0028)
	TSoftClassPtr<class UClass>                   desert_kaiju_class;                                // 0x0CF0(0x0028)
	TSubclassOf<class IInterface>                 king_kaiju_class_interface;                        // 0x0D18(0x0008)
	class FName                                   spirit_bear_tag;                                   // 0x0D20(0x0008)
	ETraceTypeQuery                               teleport_line_trace_check_channel_for_tek_shield;  // 0x0D28(0x0001)
	uint8                                         Pad_D29[0x3];                                      // 0x0D29(0x0003)
	float                                         RootedDamage;                                      // 0x0D2C(0x0004)
	TSoftClassPtr<class UClass>                   parent_rooted_buff_ref;                            // 0x0D30(0x0028)
	TSoftClassPtr<class UClass>                   post_rooted_protection_buff_ref;                   // 0x0D58(0x0028)

public:
	void ShouldHarvestFoliage(const struct FOverlappedFoliageElement& CheckFoliage, const struct FVector& override_harvest_loc, double Radius, const struct FVector& center_point, bool* bResult);
	void RootEnemiesInside(class AActor* ForInstigator);
	void ReceiveBeginPlay();
	void PerformanceThrottledTick();
	void Is_Foliage_Valid_to_be_Destroyed_by_root_burst(class UHierarchicalInstancedStaticMeshComponent* FoliageAsHierarchical_InstancedStaticMeshComp, class UPrimalHarvestingComponent* HarvestingComponent, const class UStaticMesh* Foliage_Static_Mesh, bool* IsValid, bool* IsHarvestable, bool* IsNotOnlyHarvestableByBlacklistedDamageTypes, bool* IsWithinHeightThreshold, bool* IsWithinHarvestDamageThreshold);
	void Get_Furthest_Sweeped_Valid_Spot_Trace_UsingChannel(const struct FVector& trace_start, const struct FVector& End_TP_Spot, const TArray<class AActor*>& ActorsToIgnore, ETraceTypeQuery TraceChannel, bool in_debug, bool* is_blocked_by_something, struct FVector* Validated_Spot);
	void Get_Furthest_Sweeped_Valid_Spot_Trace(const struct FVector& trace_start, const struct FVector& End_TP_Spot, const TArray<class AActor*>& ActorsToIgnore, bool in_debug, bool* Ret_Is_Blocked_By_Something, struct FVector* Validated_Spot);
	void Check_If_Character_Isn_t_Blocked_By_Something(class APrimalDinoCharacter* For_Character, TArray<struct FVector>& Additional_Trace_offsets, class ACharacter* Target_0, bool* Character_Is_Blocked);
	void Can_Root_Actor(class AActor* Actor, bool* can_root);
	void BPDeactivated(class AActor* ForInstigator);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Buff_RootAOE_SBear_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Buff_RootAOE_SBear_C")
	}
	static class ABuff_RootAOE_SBear_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABuff_RootAOE_SBear_C>();
	}
};

}

