#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated

#include "Basic.hpp"

#include "Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_classes.hpp"
#include "Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_parameters.hpp"


namespace SDK
{

// Function Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated.Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C.BuffTickClient
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C::BuffTickClient(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C", "BuffTickClient");

	Params::Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C_BuffTickClient Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated.Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C.BPServerHandleNetExecCommand
// (Event, Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APlayerController*                FromPC                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class FName                             CommandName                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FBPNetExecParams&          ExecParams                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABuff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C::BPServerHandleNetExecCommand(class APlayerController* FromPC, class FName CommandName, const struct FBPNetExecParams& ExecParams)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C", "BPServerHandleNetExecCommand");

	Params::Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C_BPServerHandleNetExecCommand Parms{};

	Parms.FromPC = FromPC;
	Parms.CommandName = CommandName;
	Parms.ExecParams = std::move(ExecParams);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated.Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C.ExtraConditionCheck
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// bool*                                   success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABuff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C::ExtraConditionCheck(bool* success) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C", "ExtraConditionCheck");

	Params::Buff_DebugMissionWeapon_Fishing_EquipRodWhileSeated_C_ExtraConditionCheck Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (success != nullptr)
		*success = Parms.success;
}

}

