#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Carno_GroundConform_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Carno_GroundConform_AnimBP.Carno_GroundConform_AnimBP_C.ExecuteUbergraph_Carno_GroundConform_AnimBP
// 0x0070 (0x0070 - 0x0000)
struct Carno_GroundConform_AnimBP_C_ExecuteUbergraph_Carno_GroundConform_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0008(0x0008)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)
	float                                         CallFunc_GetBabyScale_ReturnValue;                 // 0x001C(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0020(0x0001)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0024(0x0004)
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue;            // 0x0028(0x0008)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue_1;            // 0x0030(0x0008)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character_1;      // 0x0038(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0040(0x0001)
	bool                                          CallFunc_HasDynamicBase_ReturnValue;               // 0x0041(0x0001)
	bool                                          CallFunc_InitializeGroundConformVariables_Interpolate; // 0x0042(0x0001)
	bool                                          CallFunc_UpdateGroundConformVariables_IsBeingDragged; // 0x0043(0x0001)
	bool                                          CallFunc_UpdateGroundConformVariables_IsSwimming;  // 0x0044(0x0001)
	bool                                          CallFunc_UpdateGroundConformVariables_IsFalling;   // 0x0045(0x0001)
	bool                                          CallFunc_UpdateGroundConformVariables_Should_Mark_Has_Hit_Ground_once; // 0x0046(0x0001)
	bool                                          CallFunc_UpdateGroundConformVariables_Interpolate; // 0x0047(0x0001)
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue_1;          // 0x0048(0x0008)
	float                                         CallFunc_GetCurveValue_ReturnValue;                // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	double                                        CallFunc_Conv_BoolToDouble_ReturnValue_2;          // 0x0058(0x0008)
	float                                         K2Node_StructMemberSet_Alpha_ImplicitCast;         // 0x0060(0x0004)
	float                                         K2Node_StructMemberSet_Alpha_ImplicitCast_1;       // 0x0064(0x0004)
	float                                         K2Node_StructMemberSet_Alpha_ImplicitCast_2;       // 0x0068(0x0004)
	float                                         K2Node_StructMemberSet_Alpha_ImplicitCast_3;       // 0x006C(0x0004)
};

// Function Carno_GroundConform_AnimBP.Carno_GroundConform_AnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct Carno_GroundConform_AnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)
};

// Function Carno_GroundConform_AnimBP.Carno_GroundConform_AnimBP_C.BlueprintThreadSafeUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct Carno_GroundConform_AnimBP_C_BlueprintThreadSafeUpdateAnimation final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)
};

// Function Carno_GroundConform_AnimBP.Carno_GroundConform_AnimBP_C.AnimGraph
// 0x0020 (0x0020 - 0x0000)
struct Carno_GroundConform_AnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)
	struct FPoseLink                              AnimGraph_0;                                       // 0x0010(0x0010)
};

}

