#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ChalicoProj_Base

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ChalicoProj_Base.ChalicoProj_Base_C
// 0x0008 (0x07B8 - 0x07B0)
class AChalicoProj_Base_C : public AShooterProjectile
{
public:
	double                                        notAChalicoDamage;                                 // 0x07B0(0x0008)

public:
	void OnExplode(const struct FHitResult& Result);
	void ReceiveBeginPlay();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ChalicoProj_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ChalicoProj_Base_C")
	}
	static class AChalicoProj_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AChalicoProj_Base_C>();
	}
};

}

