#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Chest_AnimBP_Base

#include "Basic.hpp"

#include "AnimGraphRuntime_structs.hpp"
#include "Chest_AnimBP_Base_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Chest_AnimBP_Base.Chest_AnimBP_Base_C
// 0x0170 (0x0540 - 0x03D0)
class UChest_AnimBP_Base_C : public UAnimInstance
{
public:
	uint8                                         Pad_3C8[0x8];                                      // 0x03C8(0x0008)
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)
	struct Chest_AnimBP_Base::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;            // 0x03D8(0x0002)
	uint8                                         Pad_3DA[0x6];                                      // 0x03DA(0x0006)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03E0(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03E8(0x0008)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03F0(0x0020)
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x0410(0x0048)
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x0458(0x0048)
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x04A0(0x0048)
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x04E8(0x0048)
	bool                                          bIsUnlocked;                                       // 0x0530(0x0001)

public:
	void ExecuteUbergraph_Chest_AnimBP_Base(int32 EntryPoint);
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void AnimGraph(struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Chest_AnimBP_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Chest_AnimBP_Base_C")
	}
	static class UChest_AnimBP_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UChest_AnimBP_Base_C>();
	}
};

}

