#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DataListButtonVariable_Wardrobe_Widget_ASA

#include "Basic.hpp"


namespace SDK::Params
{

// Function DataListButtonVariable_Wardrobe_Widget_ASA.DataListButtonVariable_Wardrobe_Widget_ASA_C.GetDyeSelectorData
// 0x0020 (0x0020 - 0x0000)
struct DataListButtonVariable_Wardrobe_Widget_ASA_C_GetDyeSelectorData final
{
public:
	class UDyeItemSelector_WIdget_C*              Dye;                                               // 0x0000(0x0008)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0008(0x0008)
	class UDyeItemSelector_WIdget_C*              K2Node_DynamicCast_AsDye_Item_Selector_WIdget;     // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
};

// Function DataListButtonVariable_Wardrobe_Widget_ASA.DataListButtonVariable_Wardrobe_Widget_ASA_C.SetupTextValue
// 0x0070 (0x0070 - 0x0000)
struct DataListButtonVariable_Wardrobe_Widget_ASA_C_SetupTextValue final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0010)
	class FText                                   ReturnText;                                        // 0x0010(0x0010)
	class FText                                   CallFunc_SetupTextValue_ReturnText;                // 0x0020(0x0010)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0030(0x0010)
	class UWidget*                                CallFunc_GetChildAt_ReturnValue;                   // 0x0040(0x0008)
	int32                                         CallFunc_Conv_StringToInt_ReturnValue;             // 0x0048(0x0004)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)
	class USelector_ASA_Widget_C*                 K2Node_DynamicCast_AsSelector_ASA_Widget;          // 0x0050(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0058(0x0001)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0060(0x0010)
};

}

