#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DayCycleManager_Genesis

#include "Basic.hpp"

#include "DayCycleManager_Genesis_classes.hpp"
#include "DayCycleManager_Genesis_parameters.hpp"


namespace SDK
{

// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.UpdateAreaBuff
// (BlueprintCallable, BlueprintEvent)

void ADayCycleManager_Genesis_C::UpdateAreaBuff()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "UpdateAreaBuff");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.SetNewWindSettings
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   WindDir                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   OldWindDir                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FS_DayWeather_WindSettings&NewPrimWindSettings                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FS_DayWeather_WindSettings&OldPrimWindSettings                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FS_DayWeather_WindSettings&NewGustWindSettings                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FS_DayWeather_WindSettings&OldGustWindSettings                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TransitionBeginTime                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  TransitionDuratiion                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::SetNewWindSettings(const struct FVector& WindDir, const struct FVector& OldWindDir, const struct FS_DayWeather_WindSettings& NewPrimWindSettings, const struct FS_DayWeather_WindSettings& OldPrimWindSettings, const struct FS_DayWeather_WindSettings& NewGustWindSettings, const struct FS_DayWeather_WindSettings& OldGustWindSettings, double TransitionBeginTime, double TransitionDuratiion)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "SetNewWindSettings");

	Params::DayCycleManager_Genesis_C_SetNewWindSettings Parms{};

	Parms.WindDir = std::move(WindDir);
	Parms.OldWindDir = std::move(OldWindDir);
	Parms.NewPrimWindSettings = std::move(NewPrimWindSettings);
	Parms.OldPrimWindSettings = std::move(OldPrimWindSettings);
	Parms.NewGustWindSettings = std::move(NewGustWindSettings);
	Parms.OldGustWindSettings = std::move(OldGustWindSettings);
	Parms.TransitionBeginTime = TransitionBeginTime;
	Parms.TransitionDuratiion = TransitionDuratiion;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.ReceiveTick
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaSeconds                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::ReceiveTick(float DeltaSeconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "ReceiveTick");

	Params::DayCycleManager_Genesis_C_ReceiveTick Parms{};

	Parms.DeltaSeconds = DeltaSeconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ADayCycleManager_Genesis_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.ManageStormVectors
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// TArray<struct FVector>&                 BiomeVectorArray                                       (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// double                                  ChanceToAddStorm                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   MaxNumStorms                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BiomeXMin                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BiomeXMax                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BiomeYMin                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  BiomeYMax                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  StormRateOfTravel                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<double>&                         StormTimeArray                                         (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// double                                  StormLifetime                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// TArray<int32>&                          SwampInfectedSwarms                                    (BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// bool                                    ProcessSwampStorms                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   BiomeHasActiveStorm                                    (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::ManageStormVectors(TArray<struct FVector>& BiomeVectorArray, double ChanceToAddStorm, int32 MaxNumStorms, double BiomeXMin, double BiomeXMax, double BiomeYMin, double BiomeYMax, double StormRateOfTravel, TArray<double>& StormTimeArray, double StormLifetime, TArray<int32>& SwampInfectedSwarms, bool ProcessSwampStorms, bool* BiomeHasActiveStorm)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "ManageStormVectors");

	Params::DayCycleManager_Genesis_C_ManageStormVectors Parms{};

	Parms.BiomeVectorArray = std::move(BiomeVectorArray);
	Parms.ChanceToAddStorm = ChanceToAddStorm;
	Parms.MaxNumStorms = MaxNumStorms;
	Parms.BiomeXMin = BiomeXMin;
	Parms.BiomeXMax = BiomeXMax;
	Parms.BiomeYMin = BiomeYMin;
	Parms.BiomeYMax = BiomeYMax;
	Parms.StormRateOfTravel = StormRateOfTravel;
	Parms.StormTimeArray = std::move(StormTimeArray);
	Parms.StormLifetime = StormLifetime;
	Parms.SwampInfectedSwarms = std::move(SwampInfectedSwarms);
	Parms.ProcessSwampStorms = ProcessSwampStorms;

	UObject::ProcessEvent(Func, &Parms);

	BiomeVectorArray = std::move(Parms.BiomeVectorArray);
	StormTimeArray = std::move(Parms.StormTimeArray);
	SwampInfectedSwarms = std::move(Parms.SwampInfectedSwarms);

	if (BiomeHasActiveStorm != nullptr)
		*BiomeHasActiveStorm = Parms.BiomeHasActiveStorm;
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.IsLocationInWeatherEvent
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::IsLocationInWeatherEvent(bool Location)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "IsLocationInWeatherEvent");

	Params::DayCycleManager_Genesis_C_IsLocationInWeatherEvent Parms{};

	Parms.Location = Location;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.Get VR World PP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APostProcessVolume**              PP                                                     (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::Get_VR_World_PP(class APostProcessVolume** PP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "Get VR World PP");

	Params::DayCycleManager_Genesis_C_Get_VR_World_PP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PP != nullptr)
		*PP = Parms.PP;
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.Get Teleport Transfer World PP
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class APostProcessVolume**              PP                                                     (Parm, OutParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::Get_Teleport_Transfer_World_PP(class APostProcessVolume** PP)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "Get Teleport Transfer World PP");

	Params::DayCycleManager_Genesis_C_Get_Teleport_Transfer_World_PP Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (PP != nullptr)
		*PP = Parms.PP;
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.ExecuteUbergraph_DayCycleManager_Genesis
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::ExecuteUbergraph_DayCycleManager_Genesis(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "ExecuteUbergraph_DayCycleManager_Genesis");

	Params::DayCycleManager_Genesis_C_ExecuteUbergraph_DayCycleManager_Genesis Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.Earth Quake Drop Item at Location
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   AtLoc                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   BiomeArea                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FRotator&                  AtRot                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void ADayCycleManager_Genesis_C::Earth_Quake_Drop_Item_at_Location(const struct FVector& AtLoc, int32 BiomeArea, const struct FRotator& AtRot)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "Earth Quake Drop Item at Location");

	Params::DayCycleManager_Genesis_C_Earth_Quake_Drop_Item_at_Location Parms{};

	Parms.AtLoc = std::move(AtLoc);
	Parms.BiomeArea = BiomeArea;
	Parms.AtRot = std::move(AtRot);

	UObject::ProcessEvent(Func, &Parms);
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.BPAdjustTemperature
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TemperatureIn                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class ABiomeZoneVolume*                 BiomeZoneVolume                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   AtLocation                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APrimalCharacter*                 ForPrimalCharacter                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float ADayCycleManager_Genesis_C::BPAdjustTemperature(float TemperatureIn, class ABiomeZoneVolume* BiomeZoneVolume, const struct FVector& AtLocation, class APrimalCharacter* ForPrimalCharacter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "BPAdjustTemperature");

	Params::DayCycleManager_Genesis_C_BPAdjustTemperature Parms{};

	Parms.TemperatureIn = TemperatureIn;
	Parms.BiomeZoneVolume = BiomeZoneVolume;
	Parms.AtLocation = std::move(AtLocation);
	Parms.ForPrimalCharacter = ForPrimalCharacter;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.IsRainingAtLocation
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ADayCycleManager_Genesis_C::IsRainingAtLocation(const struct FVector& Location) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "IsRainingAtLocation");

	Params::DayCycleManager_Genesis_C_IsRainingAtLocation Parms{};

	Parms.Location = std::move(Location);

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function DayCycleManager_Genesis.DayCycleManager_Genesis_C.CompareWeatherLocation
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure, Const)
// Parameters:
// const struct FVector&                   StormLocaiton                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   LocationToCompare                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  StormBaseRadius                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   InStormRadius                                          (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ADayCycleManager_Genesis_C::CompareWeatherLocation(const struct FVector& StormLocaiton, const struct FVector& LocationToCompare, double StormBaseRadius, bool* InStormRadius) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("DayCycleManager_Genesis_C", "CompareWeatherLocation");

	Params::DayCycleManager_Genesis_C_CompareWeatherLocation Parms{};

	Parms.StormLocaiton = std::move(StormLocaiton);
	Parms.LocationToCompare = std::move(LocationToCompare);
	Parms.StormBaseRadius = StormBaseRadius;

	UObject::ProcessEvent(Func, &Parms);

	if (InStormRadius != nullptr)
		*InStormRadius = Parms.InStormRadius;
}

}

