#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DeathEssenceInventoryTooltipWidget

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass DeathEssenceInventoryTooltipWidget.DeathEssenceInventoryTooltipWidget_C
// 0x0028 (0x0728 - 0x0700)
class UDeathEssenceInventoryTooltipWidget_C final : public UPrimalCryopodTooltipWidget
{
public:
	class UImage*                                 DinoIcon;                                          // 0x0700(0x0008)
	class UImage*                                 FatherIcon;                                        // 0x0708(0x0008)
	class UImage*                                 GenderIcon;                                        // 0x0710(0x0008)
	class UImage*                                 MotherIcon;                                        // 0x0718(0x0008)
	class UToolTipWidgetPrimalItem_Inventory_C*   TooltipEmptyCryopod;                               // 0x0720(0x0008)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DeathEssenceInventoryTooltipWidget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DeathEssenceInventoryTooltipWidget_C")
	}
	static class UDeathEssenceInventoryTooltipWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDeathEssenceInventoryTooltipWidget_C>();
	}
};

}

