#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Dimetrodon_GroundConform_AnimBP

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "ControlRig_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Dimetrodon_GroundConform_AnimBP.Dimetrodon_GroundConform_AnimBP_C
// 0x0D10 (0x10E0 - 0x03D0)
class UDimetrodon_GroundConform_AnimBP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3C8[0x8];                                      // 0x03C8(0x0008)
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03D0(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03D8(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03E0(0x0008)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03E8(0x0020)
	struct FAnimNode_ControlRig                   AnimGraphNode_ControlRig;                          // 0x0408(0x04E0)
	struct FAnimNode_TwoWayBlend                  AnimGraphNode_TwoWayBlend;                         // 0x08E8(0x00C8)
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose_1;                    // 0x09B0(0x0080)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_3;                     // 0x0A30(0x0028)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_2;                     // 0x0A58(0x0028)
	struct FAnimNode_LayeredBoneBlend             AnimGraphNode_LayeredBoneBlend;                    // 0x0A80(0x00E8)
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0B68(0x00B8)
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x0C20(0x01A0)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0DC0(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0DE0(0x0020)
	struct FAnimNode_MakeDynamicAdditive          AnimGraphNode_MakeDynamicAdditive;                 // 0x0E00(0x0038)
	struct FAnimNode_ApplyAdditive                AnimGraphNode_ApplyAdditive;                       // 0x0E38(0x00C8)
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x0F00(0x0048)
	struct FAnimNode_SequenceEvaluator            AnimGraphNode_SequenceEvaluator;                   // 0x0F48(0x0040)
	struct FAnimNode_SaveCachedPose               AnimGraphNode_SaveCachedPose;                      // 0x0F88(0x0080)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose_1;                     // 0x1008(0x0028)
	struct FAnimNode_UseCachedPose                AnimGraphNode_UseCachedPose;                       // 0x1030(0x0028)
	struct FAnimNode_Slot                         AnimGraphNode_Slot;                                // 0x1058(0x0048)
	double                                        __CustomProperty_BabyScale_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10A0(0x0008)
	bool                                          __CustomProperty_bHasDynamicBase_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10A8(0x0001)
	bool                                          __CustomProperty_IsFalling_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10A9(0x0001)
	bool                                          __CustomProperty_Interpolate_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10AA(0x0001)
	bool                                          __CustomProperty_Swimming_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10AB(0x0001)
	bool                                          __CustomProperty_GroundConform_IsBeingDragged_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10AC(0x0001)
	uint8                                         Pad_10AD[0x3];                                     // 0x10AD(0x0003)
	struct FVector                                __CustomProperty_MeshScale_40490BDE487F9ECFB50D8EBA67F78C82; // 0x10B0(0x0018)
	class UAnimInstance*                          AnimInstance;                                      // 0x10C8(0x0008)
	bool                                          Is_Being_Dragged;                                  // 0x10D0(0x0001)
	bool                                          bSwimmingMovement;                                 // 0x10D1(0x0001)
	bool                                          HasHitTheGroundOnce;                               // 0x10D2(0x0001)
	bool                                          bFallingMovement;                                  // 0x10D3(0x0001)
	bool                                          GroundConform_Interpolate;                         // 0x10D4(0x0001)
	bool                                          WasBeingDragged;                                   // 0x10D5(0x0001)
	bool                                          Is_Sleeping;                                       // 0x10D6(0x0001)
	bool                                          HasDynamicBase;                                    // 0x10D7(0x0001)
	float                                         BabyScale;                                         // 0x10D8(0x0004)

public:
	void ExecuteUbergraph_Dimetrodon_GroundConform_AnimBP(int32 EntryPoint);
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Dimetrodon_GroundConform_AnimBP_AnimGraphNode_TwoWayBlend_D935905A46D64273B21A5398F9F07511();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Dimetrodon_GroundConform_AnimBP_AnimGraphNode_ModifyBone_0228449545B58B870DBE7C9BB0CA7035();
	void EvaluateGraphExposedInputs_ExecuteUbergraph_Dimetrodon_GroundConform_AnimBP_AnimGraphNode_ApplyAdditive_2D7FBF6C430B70A05A398B9FD4D88934();
	void BlueprintUpdateAnimation(float DeltaTimeX);
	void BlueprintInitializeAnimation();
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Dimetrodon_GroundConform_AnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Dimetrodon_GroundConform_AnimBP_C")
	}
	static class UDimetrodon_GroundConform_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDimetrodon_GroundConform_AnimBP_C>();
	}
};

}

