#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoSettings_Herbivore_Huge_Sauro

#include "Basic.hpp"

#include "DinoSettings_Herbivore_Huge_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoSettings_Herbivore_Huge_Sauro.DinoSettings_Herbivore_Huge_Sauro_C
// 0x0000 (0x0108 - 0x0108)
class UDinoSettings_Herbivore_Huge_Sauro_C final : public UDinoSettings_Herbivore_Huge_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DinoSettings_Herbivore_Huge_Sauro_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DinoSettings_Herbivore_Huge_Sauro_C")
	}
	static class UDinoSettings_Herbivore_Huge_Sauro_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoSettings_Herbivore_Huge_Sauro_C>();
	}
};

}

