#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure

#include "Basic.hpp"

#include "DinoDropInventoryComponent_Carnivore_Small_Dilo_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure.DinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure_C
// 0x0000 (0x0830 - 0x0830)
class UDinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure_C final : public UDinoDropInventoryComponent_Carnivore_Small_Dilo_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure_C")
	}
	static class UDinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoDropInventoryComponent_Carnivore_Small_Dilo_Treasure_C>();
	}
};

}

