#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoAttackStateAoEFlee_Para

#include "Basic.hpp"

#include "DinoAttackStateAoEFlee_Base_classes.hpp"
#include "ShooterGame_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoAttackStateAoEFlee_Para.DinoAttackStateAoEFlee_Para_C
// 0x0020 (0x0090 - 0x0070)
class UDinoAttackStateAoEFlee_Para_C final : public UDinoAttackStateAoEFlee_Base_C
{
public:
	TArray<TSoftClassPtr<class UClass>>           FrightenExtraDinoTypes;                            // 0x0070(0x0010)
	double                                        FrightenMassThresholdCarnivore;                    // 0x0080(0x0008)
	double                                        FrightenMassThresholdHerbivore;                    // 0x0088(0x0008)

public:
	void Should_Frighten_Character(class APrimalCharacter* Character, bool* ShouldFrighten);
	void Get_Octree_Group(EServerOctreeGroup* OctreeGroup);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DinoAttackStateAoEFlee_Para_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DinoAttackStateAoEFlee_Para_C")
	}
	static class UDinoAttackStateAoEFlee_Para_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoAttackStateAoEFlee_Para_C>();
	}
};

}

