#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DinoColorSet_Raptor_Bionic

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DinoColorSet_Raptor_Bionic.DinoColorSet_Raptor_Bionic_C
// 0x0000 (0x0268 - 0x0268)
class UDinoColorSet_Raptor_Bionic_C final : public UPrimalColorSet
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("DinoColorSet_Raptor_Bionic_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"DinoColorSet_Raptor_Bionic_C")
	}
	static class UDinoColorSet_Raptor_Bionic_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDinoColorSet_Raptor_Bionic_C>();
	}
};

}

