#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Doed_Anim_Blueprint

#include "Basic.hpp"

#include "DinoBlueprintBase_RootBoneName_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Doed-Anim-Blueprint.Doed-Anim-Blueprint_C
// 0x0000 (0x3300 - 0x3300)
class UDoed_Anim_Blueprint_C final : public UDinoBlueprintBase_RootBoneName_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Doed-Anim-Blueprint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Doed-Anim-Blueprint_C")
	}
	static class UDoed_Anim_Blueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDoed_Anim_Blueprint_C>();
	}
};

}

