#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_AB_Weathers

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_AB_Weathers.E_AB_Weathers
// NumValues: 0x0006
enum class E_AB_Weathers : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	NewEnumerator4                           = 4,
	E_AB_MAX                                 = 5,
};

}

