#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EscortMoveAroundBlockade_DR

#include "Basic.hpp"

#include "AIModule_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function EscortMoveAroundBlockade_DR.EscortMoveAroundBlockade_DR_C.ReceiveExecutionStart
// 0x0008 (0x0008 - 0x0000)
struct EscortMoveAroundBlockade_DR_C_ReceiveExecutionStart final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)
};

// Function EscortMoveAroundBlockade_DR.EscortMoveAroundBlockade_DR_C.ReceiveExecutionFinish
// 0x0010 (0x0010 - 0x0000)
struct EscortMoveAroundBlockade_DR_C_ReceiveExecutionFinish final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)
	EBTNodeResult                                 NodeResult;                                        // 0x0008(0x0001)
};

// Function EscortMoveAroundBlockade_DR.EscortMoveAroundBlockade_DR_C.ReceiveConditionCheck
// 0x0008 (0x0008 - 0x0000)
struct EscortMoveAroundBlockade_DR_C_ReceiveConditionCheck final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)
};

// Function EscortMoveAroundBlockade_DR.EscortMoveAroundBlockade_DR_C.ExecuteUbergraph_EscortMoveAroundBlockade_DR
// 0x0110 (0x0110 - 0x0000)
struct EscortMoveAroundBlockade_DR_C_ExecuteUbergraph_EscortMoveAroundBlockade_DR final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	class AActor*                                 K2Node_Event_OwnerActor;                           // 0x0008(0x0008)
	class AActor*                                 K2Node_Event_OwnerActor_2;                         // 0x0010(0x0008)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController;     // 0x0018(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController_1;   // 0x0028(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0038(0x0008)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_1;                 // 0x0040(0x0008)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0048(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0050(0x0001)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)
	struct FVector                                CallFunc_GetVelocity_ReturnValue;                  // 0x0058(0x0018)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x0070(0x0008)
	class UPrimalCharacterMovement*               CallFunc_CharacterMovementToPCM_ReturnValue;       // 0x0078(0x0008)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x0080(0x0001)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0088(0x0018)
	class AActor*                                 K2Node_Event_OwnerActor_1;                         // 0x00A0(0x0008)
	EBTNodeResult                                 K2Node_Event_NodeResult;                           // 0x00A8(0x0001)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00B0(0x0018)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController_2;   // 0x00C8(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x00D0(0x0001)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)
	double                                        CallFunc_VSize_ReturnValue_1;                      // 0x00D8(0x0008)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue_1;          // 0x00E0(0x0001)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x00E1(0x0001)
	uint8                                         Pad_E2[0x6];                                       // 0x00E2(0x0006)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue_2;                 // 0x00E8(0x0008)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character_1;           // 0x00F0(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_4;                     // 0x00F8(0x0001)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)
	double                                        CallFunc_Subtract_DoubleDouble_ReturnValue;        // 0x0100(0x0008)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0108(0x0001)
};

}

