#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Female_Hair_Mohawk_Long_CtrlRig

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ControlRig_classes.hpp"


namespace SDK
{

// RigVMBlueprintGeneratedClass Female_Hair_Mohawk_Long_CtrlRig.Female_Hair_Mohawk_Long_CtrlRig_C
// 0x00B0 (0x0B80 - 0x0AD0)
class UFemale_Hair_Mohawk_Long_CtrlRig_C final : public UControlRig
{
public:
	TArray<struct FVector>                        BoneArraySpringSolver_CurrentSpringPositionGlobal; // 0x0AD0(0x0010)
	TArray<struct FVector>                        BoneArraySpringSolver_LastFrameSpringPositionGlobal; // 0x0AE0(0x0010)
	TArray<struct FVector>                        BoneArraySpringSolver_CurrentVelocity;             // 0x0AF0(0x0010)
	TArray<struct FVector>                        BoneArraySpringSolver_CurrentVelocityGlobal;       // 0x0B00(0x0010)
	float                                         BoneArraySpringSolver_SpringStrength_0;            // 0x0B10(0x0004)
	float                                         BoneArraySpringSolver_SpringDamping_0;             // 0x0B14(0x0004)
	TArray<struct FVector>                        BoneArraySpringSolver_CurrentSpringPositionWorld;  // 0x0B18(0x0010)
	TArray<double>                                BoneArraySpringSolver_1_Alphas;                    // 0x0B28(0x0010)
	bool                                          Swimming;                                          // 0x0B38(0x0001)
	uint8                                         Pad_B39[0x7];                                      // 0x0B39(0x0007)
	TArray<double>                                SwimStrength;                                      // 0x0B40(0x0010)
	TArray<double>                                SwimDamping;                                       // 0x0B50(0x0010)
	TArray<float>                                 BoneArraySpringSolver_1_SpringStrength;            // 0x0B60(0x0010)
	TArray<float>                                 BoneArraySpringSolver_1_SpringDamping;             // 0x0B70(0x0010)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Female_Hair_Mohawk_Long_CtrlRig_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Female_Hair_Mohawk_Long_CtrlRig_C")
	}
	static class UFemale_Hair_Mohawk_Long_CtrlRig_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFemale_Hair_Mohawk_Long_CtrlRig_C>();
	}
};

}

