#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GameComp_Input

#include "Basic.hpp"

#include "SimplifiedButtonRefs_structs.hpp"


namespace SDK::Params
{

// Function GameComp_Input.GameComp_Input_C.Is Currently Holding Inputs?
// 0x01E0 (0x01E0 - 0x0000)
struct GameComp_Input_C_Is_Currently_Holding_Inputs_ final
{
public:
	TArray<ESimplifiedButtonRefs>                 Required_Buttons_Held;                             // 0x0000(0x0010)
	bool                                          Are_All_Held_;                                     // 0x0010(0x0001)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)
	TMap<ESimplifiedButtonRefs, double>           Held_Button_Info;                                  // 0x0018(0x0050)
	class ABuff_InputComp_Helper_C*               NewLocalVar;                                       // 0x0068(0x0008)
	bool                                          local_are_all_held;                                // 0x0070(0x0001)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)
	TMap<ESimplifiedButtonRefs, double>           local_held_button_infos;                           // 0x0078(0x0050)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00C8(0x0004)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00CC(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00D0(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x00D4(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00D8(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00DC(0x0001)
	uint8                                         Pad_DD[0x3];                                       // 0x00DD(0x0003)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00E0(0x0004)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)
	double                                        Temp_real_Variable;                                // 0x00E8(0x0008)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x00F0(0x0004)
	uint8                                         Pad_F4[0x4];                                       // 0x00F4(0x0004)
	TMap<ESimplifiedButtonRefs, double>           K2Node_MakeVariable_MakeVariableOutput;            // 0x00F8(0x0050)
	ESimplifiedButtonRefs                         CallFunc_Array_Get_Item;                           // 0x0148(0x0001)
	bool                                          CallFunc_GetCreatureRef_Valid;                     // 0x0149(0x0001)
	uint8                                         Pad_14A[0x6];                                      // 0x014A(0x0006)
	class APrimalDinoCharacter*                   CallFunc_GetCreatureRef_CreatureRef;               // 0x0150(0x0008)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue;                      // 0x0158(0x0008)
	double                                        CallFunc_Map_Find_Value;                           // 0x0160(0x0008)
	bool                                          CallFunc_Map_Find_ReturnValue;                     // 0x0168(0x0001)
	uint8                                         Pad_169[0x7];                                      // 0x0169(0x0007)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper;       // 0x0170(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0178(0x0001)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)
	TArray<ESimplifiedButtonRefs>                 CallFunc_Map_Keys_Keys;                            // 0x0180(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0190(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0194(0x0001)
	bool                                          CallFunc_GetShooterCharRef_Valid;                  // 0x0195(0x0001)
	uint8                                         Pad_196[0x2];                                      // 0x0196(0x0002)
	class AShooterCharacter*                      CallFunc_GetShooterCharRef_PlayerRef;              // 0x0198(0x0008)
	class APrimalDinoCharacter*                   CallFunc_GetRidingDino_ReturnValue;                // 0x01A0(0x0008)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue_1;                    // 0x01A8(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x01B0(0x0001)
	uint8                                         Pad_1B1[0x7];                                      // 0x01B1(0x0007)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper_1;     // 0x01B8(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x01C0(0x0001)
	uint8                                         Pad_1C1[0x7];                                      // 0x01C1(0x0007)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue_2;                    // 0x01C8(0x0008)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper_2;     // 0x01D0(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x01D8(0x0001)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x01D9(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x01DA(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01DB(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.GetCurrentlyHeldInputs
// 0x00E0 (0x00E0 - 0x0000)
struct GameComp_Input_C_GetCurrentlyHeldInputs final
{
public:
	TMap<ESimplifiedButtonRefs, double>           CurrentlyHeldControls;                             // 0x0000(0x0050)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0050(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0054(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0058(0x0004)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x005C(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0060(0x0004)
	bool                                          CallFunc_GetShooterCharRef_Valid;                  // 0x0064(0x0001)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)
	class AShooterCharacter*                      CallFunc_GetShooterCharRef_PlayerRef;              // 0x0068(0x0008)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue;                      // 0x0070(0x0008)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper;       // 0x0078(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0080(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0081(0x0001)
	uint8                                         Pad_82[0x6];                                       // 0x0082(0x0006)
	TArray<ESimplifiedButtonRefs>                 CallFunc_Map_Keys_Keys;                            // 0x0088(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0098(0x0004)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue_1;                    // 0x00A0(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00A8(0x0001)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper_1;     // 0x00B0(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00B8(0x0001)
	uint8                                         Pad_B9[0x7];                                       // 0x00B9(0x0007)
	TArray<ESimplifiedButtonRefs>                 CallFunc_Map_Keys_Keys_1;                          // 0x00C0(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00D0(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00D4(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00D8(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.GetBufferedLastPressedButtonCombination
// 0x0078 (0x0078 - 0x0000)
struct GameComp_Input_C_GetBufferedLastPressedButtonCombination final
{
public:
	TArray<ESimplifiedButtonRefs>                 BufferedLastPressedButtonCombination;              // 0x0000(0x0010)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0018(0x0004)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x001C(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0020(0x0004)
	bool                                          CallFunc_GetShooterCharRef_Valid;                  // 0x0024(0x0001)
	uint8                                         Pad_25[0x3];                                       // 0x0025(0x0003)
	class AShooterCharacter*                      CallFunc_GetShooterCharRef_PlayerRef;              // 0x0028(0x0008)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue;                      // 0x0030(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper;       // 0x0040(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)
	class APrimalBuff*                            CallFunc_GetBuff_ReturnValue_1;                    // 0x0050(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0058(0x0004)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)
	class ABuff_InputComp_Helper_C*               K2Node_DynamicCast_AsBuff_Input_Comp_Helper_1;     // 0x0060(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0068(0x0001)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0069(0x0001)
	uint8                                         Pad_6A[0x2];                                       // 0x006A(0x0002)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x006C(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x0070(0x0001)
	uint8                                         Pad_71[0x3];                                       // 0x0071(0x0003)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0074(0x0004)
};

// Function GameComp_Input.GameComp_Input_C.ExecuteUbergraph_GameComp_Input
// 0x0038 (0x0038 - 0x0000)
struct GameComp_Input_C_ExecuteUbergraph_GameComp_Input final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x0004(0x0001)
	bool                                          CallFunc_GetShooterCharRef_Valid;                  // 0x0005(0x0001)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)
	class AShooterCharacter*                      CallFunc_GetShooterCharRef_PlayerRef;              // 0x0008(0x0008)
	bool                                          CallFunc_GetCreatureRef_Valid;                     // 0x0010(0x0001)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)
	class APrimalDinoCharacter*                   CallFunc_GetCreatureRef_CreatureRef;               // 0x0018(0x0008)
	class APrimalBuff*                            CallFunc_StaticAddBuff_ReturnValue;                // 0x0020(0x0008)
	class APrimalBuff*                            CallFunc_StaticAddBuff_ReturnValue_1;              // 0x0028(0x0008)
	bool                                          CallFunc_HasBuff_ReturnValue;                      // 0x0030(0x0001)
	bool                                          CallFunc_HasBuff_ReturnValue_1;                    // 0x0031(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnUse_E_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnUse_E_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnTargetingReleaseHold
// 0x0070 (0x0070 - 0x0000)
struct GameComp_Input_C_depreciated_OnTargetingReleaseHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0018(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0030(0x0010)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0048(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0050(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0064(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x006D(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnTargeting_RightClick_StartHold
// 0x0078 (0x0078 - 0x0000)
struct GameComp_Input_C_depreciated_OnTargeting_RightClick_StartHold final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0004(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0005(0x0001)
	uint8                                         Pad_6[0x2];                                        // 0x0006(0x0002)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0008(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x000C(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0018(0x0001)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0020(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0038(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0048(0x0004)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0050(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0058(0x0001)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0060(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0070(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0071(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnSlowMovement_LeftAlt_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnSlowMovement_LeftAlt_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnRunToggle_LeftThumbstick_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnRunToggle_LeftThumbstick_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnRun_Shift_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnRun_Shift_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnReloadReleaseHold
// 0x0070 (0x0070 - 0x0000)
struct GameComp_Input_C_depreciated_OnReloadReleaseHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0018(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0030(0x0010)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0048(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0050(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0064(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x006D(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnReload_R_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnReload_R_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnProne_X_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnProne_X_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnJump_Space_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnJump_Space_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnFire_LeftClick_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnFire_LeftClick_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnCrouchProne_RightThumbstick_ToggleStartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnCrouchProne_RightThumbstick_ToggleStartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnCrouch_C_StartHold
// 0x0068 (0x0068 - 0x0000)
struct GameComp_Input_C_depreciated_OnCrouch_C_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0018(0x0010)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0040(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0048(0x0004)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0050(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0061(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0062(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0063(0x0001)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0064(0x0004)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnAltFireReleaseHold
// 0x0070 (0x0070 - 0x0000)
struct GameComp_Input_C_depreciated_OnAltFireReleaseHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0018(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0030(0x0010)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0048(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0050(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0064(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x006D(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnAltFire_LeftCtrl_StartHold
// 0x0070 (0x0070 - 0x0000)
struct GameComp_Input_C_depreciated_OnAltFire_LeftCtrl_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0010(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0018(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0028(0x0001)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0030(0x0010)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0048(0x0008)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0050(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)
	uint8                                         Pad_61[0x3];                                       // 0x0061(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0064(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0068(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x006C(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x006D(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_OnAccessInventory_F_StartHold
// 0x0080 (0x0080 - 0x0000)
struct GameComp_Input_C_depreciated_OnAccessInventory_F_StartHold final
{
public:
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0004(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x000C(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0010(0x0004)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0018(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs; // 0x0028(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0038(0x0001)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)
	TArray<class UActorComponent*>                CallFunc_GetComponentsByInterface_ReturnValue;     // 0x0040(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class UActorComponent*                        CallFunc_Array_Get_Item;                           // 0x0058(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0060(0x0001)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)
	TScriptInterface<class IInterface_ReceiveInputs_C> K2Node_DynamicCast_AsInterface_Receive_Inputs_1; // 0x0068(0x0010)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0078(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0079(0x0001)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_Interface_ClientTick_PerformanceThrottled
// 0x0018 (0x0018 - 0x0000)
struct GameComp_Input_C_depreciated_Interface_ClientTick_PerformanceThrottled final
{
public:
	double                                        Delta_Seconds;                                     // 0x0000(0x0008)
	bool                                          success;                                           // 0x0008(0x0001)
	bool                                          CallFunc_GetPlayerControllerRef_Valid;             // 0x0009(0x0001)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)
	class AShooterPlayerController*               CallFunc_GetPlayerControllerRef_ControllerRef;     // 0x0010(0x0008)
};

// Function GameComp_Input.GameComp_Input_C.depreciated_Check Button Fire State
// 0x0008 (0x0008 - 0x0000)
struct GameComp_Input_C_depreciated_Check_Button_Fire_State final
{
public:
	class AShooterPlayerController*               Controller;                                        // 0x0000(0x0008)
};

// Function GameComp_Input.GameComp_Input_C.DebugPrint
// 0x0070 (0x0070 - 0x0000)
struct GameComp_Input_C_DebugPrint final
{
public:
	class FString                                 Line1;                                             // 0x0000(0x0010)
	class FString                                 Line2;                                             // 0x0010(0x0010)
	class FString                                 Line3;                                             // 0x0020(0x0010)
	class FString                                 Line4;                                             // 0x0030(0x0010)
	class FString                                 Line5;                                             // 0x0040(0x0010)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0050(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0058(0x0001)
	uint8                                         Pad_59[0x7];                                       // 0x0059(0x0007)
	class UGameComp_CheatDebug_C*                 CallFunc_GetComponentByClass_ReturnValue;          // 0x0060(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0068(0x0001)
	bool                                          CallFunc_DebugPrint_Success;                       // 0x0069(0x0001)
};

}

