#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Gen_AreaBuff_Ocean

#include "Basic.hpp"

#include "Gen_AreaBuff_Ocean_classes.hpp"
#include "Gen_AreaBuff_Ocean_parameters.hpp"


namespace SDK
{

// Function Gen_AreaBuff_Ocean.Gen_AreaBuff_Ocean_C.BuffTickServer
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AGen_AreaBuff_Ocean_C::BuffTickServer(float DeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Gen_AreaBuff_Ocean_C", "BuffTickServer");

	Params::Gen_AreaBuff_Ocean_C_BuffTickServer Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

