#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenesisBossArenaKiller

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GenesisBossArenaKiller.GenesisBossArenaKiller_C
// 0x00A0 (0x0530 - 0x0490)
class AGenesisBossArenaKiller_C final : public ASaveGameActorTickable
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0490(0x0008)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0498(0x0008)
	bool                                          bResetOnBeginPlay;                                 // 0x04A0(0x0001)
	uint8                                         Pad_4A1[0x7];                                      // 0x04A1(0x0007)
	double                                        TeleportActorsGatherRadius;                        // 0x04A8(0x0008)
	struct FVector                                BossArenaCenterLocation;                           // 0x04B0(0x0018)
	struct FVector                                PlayerReturnPos;                                   // 0x04C8(0x0018)
	struct FVector                                ReturnTeleportPosOffset;                           // 0x04E0(0x0018)
	TArray<class UClass*>                         PreventDeletionStructureClasses;                   // 0x04F8(0x0010)
	bool                                          bOnlyResetIfLoadingSaveGame;                       // 0x0508(0x0001)
	uint8                                         Pad_509[0x7];                                      // 0x0509(0x0007)
	class AVolume*                                VictimContainerVolume;                             // 0x0510(0x0008)
	TArray<class UClass*>                         MissionTypesToCheckForActivity;                    // 0x0518(0x0010)
	bool                                          bWasMissionActive;                                 // 0x0528(0x0001)

public:
	void Teleport_Back_to_Home();
	void ReceiveTick(float DeltaSeconds);
	void ReceiveBeginPlay();
	void KillThem();
	void Kill_All_Occupants();
	void IsMissionActive(bool* OutVal);
	void Get_All_Actors_in_Boss_Arena(bool bIncludeUnconscious, bool bIncludeUntamedCreatures, bool bIncludeDead, bool bIgnorePlayers, bool bIgnoreDinos, bool bIgnoreAttached, TArray<class AActor*>* TheActors);
	void ExecuteUbergraph_GenesisBossArenaKiller(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GenesisBossArenaKiller_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GenesisBossArenaKiller_C")
	}
	static class AGenesisBossArenaKiller_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AGenesisBossArenaKiller_C>();
	}
};

}

