#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HarnessStructureBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass HarnessStructureBase.HarnessStructureBase_C
// 0x0060 (0x0D08 - 0x0CA8)
class AHarnessStructureBase_C final : public APrimalStructure
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0CA8(0x0008)
	class UBoxComponent*                          BuildingBounds;                                    // 0x0CB0(0x0008)
	class UAudioComponent*                        HarnessSounds;                                     // 0x0CB8(0x0008)
	class USphereComponent*                       StasisComponent;                                   // 0x0CC0(0x0008)
	double                                        OverrideAttachedTurretMaxYawRange;                 // 0x0CC8(0x0008)
	bool                                          IsCreatureMoving;                                  // 0x0CD0(0x0001)
	bool                                          IsCreatureRunning;                                 // 0x0CD1(0x0001)
	uint8                                         Pad_CD2[0x6];                                      // 0x0CD2(0x0006)
	class USoundCue*                              MovingSound;                                       // 0x0CD8(0x0008)
	class USoundCue*                              RunningSound;                                      // 0x0CE0(0x0008)
	class USoundCue*                              LandingSound;                                      // 0x0CE8(0x0008)
	double                                        ConsumablesTransferInterval;                       // 0x0CF0(0x0008)
	double                                        ConsumablesTransferRange;                          // 0x0CF8(0x0008)
	struct FTimerHandle                           TransferConsumableTimer;                           // 0x0D00(0x0008)

public:
	void BPPostLoadedFromSaveGame();
	void ClientSpeedUpdate();
	void ExecuteUbergraph_HarnessStructureBase(int32 EntryPoint);
	struct FVector GetAttachedTurretYawLimitsOverride(class APrimalStructure* ForStructure, double* ReturnValue_X, double* ReturnValue_Y, double* ReturnValue_Z);
	void MovementModeChanged(EMovementMode PrevMode, EMovementMode NewMode);
	void Multi_PlayLandingSound();
	void MySpeedChanged(bool bIsMoving, bool bIsRunning);
	void ReceiveBeginPlay();
	void SpeedChanged();
	void TryTransferConsumable();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HarnessStructureBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HarnessStructureBase_C")
	}
	static class AHarnessStructureBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AHarnessStructureBase_C>();
	}
};

}

