#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HF_Metal_Pants_PPAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass HF_Metal_Pants_PPAnimBP.HF_Metal_Pants_PPAnimBP_C
// 0x0C80 (0x1050 - 0x03D0)
class UHF_Metal_Pants_PPAnimBP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_3C8[0x8];                                      // 0x03C8(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x03D0(0x0008)
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x03D8(0x0008)
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x03E0(0x0020)
	struct FAnimNode_CopyPoseFromMesh             AnimGraphNode_CopyPoseFromMesh;                    // 0x0400(0x0158)
	uint8                                         Pad_558[0x8];                                      // 0x0558(0x0008)
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0560(0x09F0)
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x0F50(0x0020)
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x0F70(0x0020)
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x0F90(0x00B8)

public:
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("HF_Metal_Pants_PPAnimBP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"HF_Metal_Pants_PPAnimBP_C")
	}
	static class UHF_Metal_Pants_PPAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHF_Metal_Pants_PPAnimBP_C>();
	}
};

}

