#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ImpactEffect_ShipCannon

#include "Basic.hpp"

#include "ImpactEffect_ShipCannon_classes.hpp"
#include "ImpactEffect_ShipCannon_parameters.hpp"


namespace SDK
{

// Function ImpactEffect_ShipCannon.ImpactEffect_ShipCannon_C.ExecuteUbergraph_ImpactEffect_ShipCannon
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AImpactEffect_ShipCannon_C::ExecuteUbergraph_ImpactEffect_ShipCannon(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ImpactEffect_ShipCannon_C", "ExecuteUbergraph_ImpactEffect_ShipCannon");

	Params::ImpactEffect_ShipCannon_C_ExecuteUbergraph_ImpactEffect_ShipCannon Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ImpactEffect_ShipCannon.ImpactEffect_ShipCannon_C.BPOnEmitterSpawned
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UFXSystemComponent*               FXComponent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SurfaceHit                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// const struct FVector&                   Velocity                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class APrimalCharacter*                 InstigatorChar                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AImpactEffect_ShipCannon_C::BPOnEmitterSpawned(class UFXSystemComponent* FXComponent, const struct FHitResult& SurfaceHit, const struct FVector& Velocity, class APrimalCharacter* InstigatorChar)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("ImpactEffect_ShipCannon_C", "BPOnEmitterSpawned");

	Params::ImpactEffect_ShipCannon_C_BPOnEmitterSpawned Parms{};

	Parms.FXComponent = FXComponent;
	Parms.SurfaceHit = std::move(SurfaceHit);
	Parms.Velocity = std::move(Velocity);
	Parms.InstigatorChar = InstigatorChar;

	UObject::ProcessEvent(Func, &Parms);
}

}

