#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interface_SpiritBear_LegIK_AnimBP

#include "Basic.hpp"

#include "Interface_SpiritBear_LegIK_AnimBP_classes.hpp"
#include "Interface_SpiritBear_LegIK_AnimBP_parameters.hpp"


namespace SDK
{

// Function Interface_SpiritBear_LegIK_AnimBP.Interface_SpiritBear_LegIK_AnimBP_C.Interface_SpiritBear_LegIK_AnimBP Set Totem Bone World Location
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   Location                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool*                                   success                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void IInterface_SpiritBear_LegIK_AnimBP_C::Interface_SpiritBear_LegIK_AnimBP_Set_Totem_Bone_World_Location(const struct FVector& Location, bool* success)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = AsUObject()->Class->GetFunction("Interface_SpiritBear_LegIK_AnimBP_C", "Interface_SpiritBear_LegIK_AnimBP Set Totem Bone World Location");

	Params::Interface_SpiritBear_LegIK_AnimBP_C_Interface_SpiritBear_LegIK_AnimBP_Set_Totem_Bone_World_Location Parms{};

	Parms.Location = std::move(Location);

	AsUObject()->ProcessEvent(Func, &Parms);

	if (success != nullptr)
		*success = Parms.success;
}

}

