#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interface_ReceiveInputs

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "SimplifiedButtonRefs_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Interface_ReceiveInputs.Interface_ReceiveInputs_C
// 0x0000 (0x0000 - 0x0000)
class IInterface_ReceiveInputs_C final
{
public:
	void Interface_Inputs_Client_On_ButtonReleased(ESimplifiedButtonRefs Last_Button_Released, bool* success);
	void Interface_Inputs_Client_On_ButtonPressed(ESimplifiedButtonRefs Latest_Button_Pressed, bool Doubleclicked, double doubleclick_time_between_clicks, bool* success);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Interface_ReceiveInputs_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Interface_ReceiveInputs_C")
	}
	static class IInterface_ReceiveInputs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IInterface_ReceiveInputs_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

