#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interface_Gamecomp_Xray_Manager_Users

#include "Basic.hpp"


namespace SDK::Params
{

// Function Interface_Gamecomp_Xray_Manager_Users.Interface_Gamecomp_Xray_Manager_Users_C.Interface_Gamecomp_XrayHighlight_ Wants To Highlight (Show Custom Depth)
// 0x0001 (0x0001 - 0x0000)
struct Interface_Gamecomp_Xray_Manager_Users_C_Interface_Gamecomp_XrayHighlight__Wants_To_Highlight__Show_Custom_Depth_ final
{
public:
	bool                                          Wants_To_Show_Custom_Depth;                        // 0x0000(0x0001)
};

}

