#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LootItemSet_Missions_Retrieve_Volcanic_Cherufe

#include "Basic.hpp"

#include "LootItemSet_Missions_Retrieve_Volcanic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LootItemSet_Missions_Retrieve_Volcanic_Cherufe.LootItemSet_Missions_Retrieve_Volcanic_Cherufe_C
// 0x0000 (0x0068 - 0x0068)
class ULootItemSet_Missions_Retrieve_Volcanic_Cherufe_C final : public ULootItemSet_Missions_Retrieve_Volcanic_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("LootItemSet_Missions_Retrieve_Volcanic_Cherufe_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"LootItemSet_Missions_Retrieve_Volcanic_Cherufe_C")
	}
	static class ULootItemSet_Missions_Retrieve_Volcanic_Cherufe_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULootItemSet_Missions_Retrieve_Volcanic_Cherufe_C>();
	}
};

}

