#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MassSignals

#include "Basic.hpp"

#include "MassEntity_classes.hpp"


namespace SDK
{

// Class MassSignals.MassSignalProcessorBase
// 0x03E0 (0x0490 - 0x00B0)
class UMassSignalProcessorBase : public UMassProcessor
{
public:
	uint8                                         Pad_B0[0x3E0];                                     // 0x00B0(0x03E0)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MassSignalProcessorBase")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MassSignalProcessorBase")
	}
	static class UMassSignalProcessorBase* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMassSignalProcessorBase>();
	}
};

// Class MassSignals.MassSignalSubsystem
// 0x0068 (0x00B0 - 0x0048)
class UMassSignalSubsystem final : public UMassTickableSubsystemBase
{
public:
	uint8                                         Pad_48[0x60];                                      // 0x0048(0x0060)
	class UWorld*                                 CachedWorld;                                       // 0x00A8(0x0008)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("MassSignalSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MassSignalSubsystem")
	}
	static class UMassSignalSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMassSignalSubsystem>();
	}
};

}

