#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MediumFootstepCameraShake

#include "Basic.hpp"

#include "EngineCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MediumFootstepCameraShake.MediumFootstepCameraShake_C
// 0x0000 (0x0200 - 0x0200)
class UMediumFootstepCameraShake_C final : public ULegacyCameraShake
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MediumFootstepCameraShake_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MediumFootstepCameraShake_C")
	}
	static class UMediumFootstepCameraShake_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMediumFootstepCameraShake_C>();
	}
};

}

