#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Megatherium_GroundConform_AnimBlueprint

#include "Basic.hpp"

#include "Megatherium_GroundConform_AnimBlueprint_classes.hpp"
#include "Megatherium_GroundConform_AnimBlueprint_parameters.hpp"


namespace SDK
{

// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMegatherium_GroundConform_AnimBlueprint_C::ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint");

	Params::Megatherium_GroundConform_AnimBlueprint_C_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_0A33DD6B48A78534F9E8D5B469687748
// (BlueprintEvent)

void UMegatherium_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_0A33DD6B48A78534F9E8D5B469687748()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_0A33DD6B48A78534F9E8D5B469687748");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_AF2B0B1B4C1391F7543B96943D7B9EB8
// (BlueprintEvent)

void UMegatherium_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_AF2B0B1B4C1391F7543B96943D7B9EB8()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_AF2B0B1B4C1391F7543B96943D7B9EB8");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ControlRig_2B62A4CA48C6FE43F958F3A03AED75F7
// (BlueprintEvent)

void UMegatherium_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ControlRig_2B62A4CA48C6FE43F958F3A03AED75F7()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ControlRig_2B62A4CA48C6FE43F958F3A03AED75F7");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_2E5BE43041EBADB77AF26D9D355B0DFE
// (BlueprintEvent)

void UMegatherium_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_2E5BE43041EBADB77AF26D9D355B0DFE()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Megatherium_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_2E5BE43041EBADB77AF26D9D355B0DFE");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UMegatherium_GroundConform_AnimBlueprint_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "BlueprintUpdateAnimation");

	Params::Megatherium_GroundConform_AnimBlueprint_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UMegatherium_GroundConform_AnimBlueprint_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Megatherium_GroundConform_AnimBlueprint.Megatherium_GroundConform_AnimBlueprint_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UMegatherium_GroundConform_AnimBlueprint_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Megatherium_GroundConform_AnimBlueprint_C", "AnimGraph");

	Params::Megatherium_GroundConform_AnimBlueprint_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

