#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionType_Escort_Lunar_LanternPets_Hard

#include "Basic.hpp"

#include "MissionType_Escort_Lunar_LanternPets_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionType_Escort_Lunar_LanternPets_Hard.MissionType_Escort_Lunar_LanternPets_Hard_C
// 0x0000 (0x1A10 - 0x1A10)
class AMissionType_Escort_Lunar_LanternPets_Hard_C final : public AMissionType_Escort_Lunar_LanternPets_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("MissionType_Escort_Lunar_LanternPets_Hard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"MissionType_Escort_Lunar_LanternPets_Hard_C")
	}
	static class AMissionType_Escort_Lunar_LanternPets_Hard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AMissionType_Escort_Lunar_LanternPets_Hard_C>();
	}
};

}

