#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionType_Escort_Ocean_Turtle

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.TryIncrementCheckpoint
// 0x0010 (0x0010 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_TryIncrementCheckpoint final
{
public:
	class AMissionTrigger*                        HitTrigger;                                        // 0x0000(0x0008)
	bool                                          Succes;                                            // 0x0008(0x0001)
	bool                                          AtEnd;                                             // 0x0009(0x0001)
	bool                                          CallFunc_TryIncrementCheckpoint_Succes;            // 0x000A(0x0001)
	bool                                          CallFunc_TryIncrementCheckpoint_AtEnd;             // 0x000B(0x0001)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.SpawnCyclones
// 0x00D0 (0x00D0 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_SpawnCyclones final
{
public:
	TArray<class AMissionServerSidePoint*>        CyclonePoints_0;                                   // 0x0000(0x0010)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0010(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0018(0x0001)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x001C(0x0004)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0020(0x0004)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0024(0x0004)
	class AMissionServerSidePoint*                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)
	struct FTransform                             CallFunc_GetTransform_ReturnValue;                 // 0x0030(0x0060)
	class AActor*                                 CallFunc_BeginDeferredActorSpawnFromClass_ReturnValue; // 0x0090(0x0008)
	class ABuff_CycloneBox_C*                     CallFunc_FinishSpawningActor_ReturnValue;          // 0x0098(0x0008)
	double                                        CallFunc_RandomFloatInRange_ReturnValue;           // 0x00A0(0x0008)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x00A8(0x0004)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)
	class ABuff_CycloneBox_C*                     CallFunc_Array_Get_Item_1;                         // 0x00B0(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00B8(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00BC(0x0001)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x00C0(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x00C4(0x0004)
	float                                         CallFunc_SetLifeSpan_InLifespan_ImplicitCast;      // 0x00C8(0x0004)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.SetDinoEscapeProperties
// 0x0018 (0x0018 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_SetDinoEscapeProperties final
{
public:
	class APrimalDinoCharacter*                   Dino;                                              // 0x0000(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0008(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0009(0x0001)
	uint8                                         Pad_A[0x6];                                        // 0x000A(0x0006)
	class UPrimalCharacterMovement*               CallFunc_CharacterMovementToPCM_ReturnValue;       // 0x0010(0x0008)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.MultiFXTurtlePals
// 0x0010 (0x0010 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_MultiFXTurtlePals final
{
public:
	TArray<class APrimalDinoCharacter*>           Dinos;                                             // 0x0000(0x0010)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.GetCyclonesThisCheckpoint
// 0x0048 (0x0048 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_GetCyclonesThisCheckpoint final
{
public:
	TArray<class AMissionServerSidePoint*>        RetPoints;                                         // 0x0000(0x0010)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0010(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0014(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0018(0x0004)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x001C(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	class AMissionServerSidePoint*                CallFunc_Array_Get_Item;                           // 0x0028(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x0030(0x0004)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x0034(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0038(0x0001)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x003C(0x0004)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0040(0x0001)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.ExtraFollowerSetup
// 0x0010 (0x0010 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_ExtraFollowerSetup final
{
public:
	int32                                         Index_0;                                           // 0x0000(0x0004)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	class APrimalDinoCharacter*                   CallFunc_Array_Get_Item;                           // 0x0008(0x0008)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.ExecuteUbergraph_MissionType_Escort_Ocean_Turtle
// 0x01D0 (0x01D0 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_ExecuteUbergraph_MissionType_Escort_Ocean_Turtle final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	class AShooterCharacter*                      K2Node_Event_ForPlayer;                            // 0x0008(0x0008)
	class AShooterPlayerController*               K2Node_Event_ForController;                        // 0x0010(0x0008)
	bool                                          K2Node_Event_bLastPhaseSuccess;                    // 0x0018(0x0001)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)
	float                                         K2Node_Event_XPRewarded;                           // 0x001C(0x0004)
	TArray<class UPrimalItem*>                    K2Node_Event_ItemsRewarded;                        // 0x0020(0x0010)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0030(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0034(0x0004)
	double                                        CallFunc_Multiply_IntFloat_ReturnValue;            // 0x0038(0x0008)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0040(0x0004)
	uint8                                         Pad_44[0x4];                                       // 0x0044(0x0004)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue;             // 0x0048(0x0008)
	int32                                         Temp_int_Array_Index_Variable_1;                   // 0x0050(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_1;                  // 0x0054(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue_1;                 // 0x0058(0x0004)
	int32                                         Temp_int_Array_Index_Variable_2;                   // 0x005C(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_2;                  // 0x0060(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue_2;                 // 0x0064(0x0004)
	TDelegate<void(class FName OldPhaseName, class FName NewPhaseName)> K2Node_CreateDelegate_OutputDelegate; // 0x0068(0x0010)
	class FName                                   CallFunc_Array_Get_Item;                           // 0x0078(0x0008)
	bool                                          CallFunc_Array_IsValidIndex_ReturnValue;           // 0x0080(0x0001)
	uint8                                         Pad_81[0x7];                                       // 0x0081(0x0007)
	TArray<class AMissionServerSidePoint*>        CallFunc_GetAllMissionServerSidePointsWithKey_ForSpecificMissionInstance_OutServerSidePointActors; // 0x0088(0x0010)
	class FName                                   K2Node_CustomEvent_OldPhaseName;                   // 0x0098(0x0008)
	class FName                                   K2Node_CustomEvent_NewPhaseName;                   // 0x00A0(0x0008)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x00A8(0x0001)
	uint8                                         Pad_A9[0x7];                                       // 0x00A9(0x0007)
	double                                        CallFunc_GetNetworkTimeInSeconds_ReturnValue;      // 0x00B0(0x0008)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue;                  // 0x00B8(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00C0(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable_3;                  // 0x00C4(0x0004)
	class APrimalDinoCharacter*                   CallFunc_Array_Get_Item_1;                         // 0x00C8(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00D0(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D1(0x0001)
	uint8                                         Pad_D2[0x6];                                       // 0x00D2(0x0006)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue_1;                // 0x00D8(0x0008)
	int32                                         CallFunc_Add_IntInt_ReturnValue_3;                 // 0x00E0(0x0004)
	int32                                         CallFunc_Array_Length_ReturnValue_1;               // 0x00E4(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_1;                // 0x00E8(0x0001)
	uint8                                         Pad_E9[0x3];                                       // 0x00E9(0x0003)
	int32                                         Temp_int_Array_Index_Variable_3;                   // 0x00EC(0x0004)
	TArray<class APrimalDinoCharacter*>           K2Node_CustomEvent_Dinos;                          // 0x00F0(0x0010)
	class APrimalDinoCharacter*                   CallFunc_Array_Get_Item_2;                         // 0x0100(0x0008)
	class APrimalDinoCharacter*                   CallFunc_Array_Get_Item_3;                         // 0x0108(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0110(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0111(0x0001)
	uint8                                         Pad_112[0x6];                                      // 0x0112(0x0006)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0118(0x0018)
	class USkeletalMesh*                          CallFunc_GetSkeletalMeshAsset_ReturnValue;         // 0x0130(0x0008)
	class UParticleSystemComponent*               CallFunc_SpawnEmitterAtLocation_ReturnValue;       // 0x0138(0x0008)
	double                                        CallFunc_MapRangeUnclamped_ReturnValue;            // 0x0140(0x0008)
	double                                        CallFunc_FClamp_ReturnValue;                       // 0x0148(0x0008)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0150(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue_2;               // 0x0158(0x0004)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)
	struct FVector                                CallFunc_Conv_DoubleToVector_ReturnValue;          // 0x0160(0x0018)
	bool                                          CallFunc_Less_IntInt_ReturnValue_2;                // 0x0178(0x0001)
	uint8                                         Pad_179[0x7];                                      // 0x0179(0x0007)
	double                                        CallFunc_Multiply_IntFloat_ReturnValue_1;          // 0x0180(0x0008)
	double                                        CallFunc_Add_DoubleDouble_ReturnValue_1;           // 0x0188(0x0008)
	struct FTimerHandle                           CallFunc_K2_SetTimer_ReturnValue_2;                // 0x0190(0x0008)
	class ABuff_CycloneBox_C*                     CallFunc_Array_Get_Item_4;                         // 0x0198(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue_3;               // 0x01A0(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x01A4(0x0001)
	uint8                                         Pad_1A5[0x3];                                      // 0x01A5(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue_4;               // 0x01A8(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue_3;                // 0x01AC(0x0001)
	uint8                                         Pad_1AD[0x3];                                      // 0x01AD(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue_5;               // 0x01B0(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x01B4(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x01B5(0x0001)
	uint8                                         Pad_1B6[0x2];                                      // 0x01B6(0x0002)
	float                                         CallFunc_K2_SetTimer_Time_ImplicitCast;            // 0x01B8(0x0004)
	uint8                                         Pad_1BC[0x4];                                      // 0x01BC(0x0004)
	double                                        CallFunc_MapRangeUnclamped_Value_ImplicitCast;     // 0x01C0(0x0008)
	float                                         CallFunc_K2_SetTimer_Time_ImplicitCast_1;          // 0x01C8(0x0004)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.EscapePhaseStarted
// 0x0010 (0x0010 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_EscapePhaseStarted final
{
public:
	class FName                                   OldPhaseName;                                      // 0x0000(0x0008)
	class FName                                   NewPhaseName;                                      // 0x0008(0x0008)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.BPOnMissionComplete
// 0x0028 (0x0028 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_BPOnMissionComplete final
{
public:
	class AShooterCharacter*                      ForPlayer;                                         // 0x0000(0x0008)
	class AShooterPlayerController*               ForController;                                     // 0x0008(0x0008)
	bool                                          bLastPhaseSuccess;                                 // 0x0010(0x0001)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)
	float                                         XPRewarded;                                        // 0x0014(0x0004)
	TArray<class UPrimalItem*>                    ItemsRewarded;                                     // 0x0018(0x0010)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.BPIsPhaseComplete
// 0x0014 (0x0014 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_BPIsPhaseComplete final
{
public:
	class FName                                   PhaseName;                                         // 0x0000(0x0008)
	bool                                          ReturnValue;                                       // 0x0008(0x0001)
	bool                                          retVal;                                            // 0x0009(0x0001)
	bool                                          CallFunc_EqualEqual_NameName_ReturnValue;          // 0x000A(0x0001)
	bool                                          CallFunc_BPIsPhaseComplete_ReturnValue;            // 0x000B(0x0001)
	bool                                          CallFunc_NotEqual_DoubleDouble_ReturnValue;        // 0x000C(0x0001)
	bool                                          CallFunc_IsTimeSince_Network_ReturnValue;          // 0x000D(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x000E(0x0001)
	uint8                                         Pad_F[0x1];                                        // 0x000F(0x0001)
	float                                         CallFunc_IsTimeSince_Network_CheckTimeSince_ImplicitCast; // 0x0010(0x0004)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.AttemptUpdateDeepWaterSpawnWeights
// 0x0008 (0x0008 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_AttemptUpdateDeepWaterSpawnWeights final
{
public:
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0000(0x0004)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0004(0x0001)
};

// Function MissionType_Escort_Ocean_Turtle.MissionType_Escort_Ocean_Turtle_C.AttemptSpawnTurtlePals
// 0x01B0 (0x01B0 - 0x0000)
struct MissionType_Escort_Ocean_Turtle_C_AttemptSpawnTurtlePals final
{
public:
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0000(0x0004)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0004(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0008(0x0004)
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x000C(0x0004)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue;              // 0x0010(0x0004)
	int32                                         CallFunc_Subtract_IntInt_ReturnValue_1;            // 0x0014(0x0004)
	class AMissionTrigger*                        CallFunc_Array_Get_Item;                           // 0x0018(0x0008)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	class AMissionTrigger_SpawningCheckpoint_C*   K2Node_DynamicCast_AsMission_Trigger_Spawning_Checkpoint; // 0x0028(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0034(0x0004)
	class AMissionServerSidePoint*                CallFunc_Array_Get_Item_1;                         // 0x0038(0x0008)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class AMissionServerSidePoint_HordeDinoSpawner_C* K2Node_DynamicCast_AsMission_Server_Side_Point_Horde_Dino_Spawner; // 0x0048(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0050(0x0001)
	uint8                                         Pad_51[0x7];                                       // 0x0051(0x0007)
	struct FRotator                               CallFunc_K2_GetActorRotation_ReturnValue;          // 0x0058(0x0018)
	bool                                          K2Node_SwitchInteger_CmpSuccess;                   // 0x0070(0x0001)
	uint8                                         Pad_71[0x7];                                       // 0x0071(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0078(0x0018)
	struct FDinoSetup                             K2Node_MakeStruct_DinoSetup;                       // 0x0090(0x0110)
	class APrimalDinoCharacter*                   CallFunc_SpawnMissionDino_ReturnValue;             // 0x01A0(0x0008)
	int32                                         CallFunc_Array_Add_ReturnValue;                    // 0x01A8(0x0004)
};

}

