#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Otter_Anim_BP

#include "Basic.hpp"

#include "DinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass Otter_Anim_BP.Otter_Anim_BP_C
// 0x0000 (0x2080 - 0x2080)
class UOtter_Anim_BP_C final : public UDinoBlueprintBase_RootBoneName_SwimmerWithLandAndSwimCharge_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Otter_Anim_BP_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Otter_Anim_BP_C")
	}
	static class UOtter_Anim_BP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOtter_Anim_BP_C>();
	}
};

}

