#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Para_FearTarget_TK

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function Para_FearTarget_TK.Para_FearTarget_TK_C.ReceiveExecute
// 0x0098 (0x0098 - 0x0000)
struct Para_FearTarget_TK_C_ReceiveExecute final
{
public:
	class AActor*                                 OwnerActor;                                        // 0x0000(0x0008)
	class APrimalDinoAIController*                K2Node_DynamicCast_AsPrimal_Dino_AIController;     // 0x0008(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0010(0x0001)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x0018)
	class APawn*                                  CallFunc_K2_GetPawn_ReturnValue;                   // 0x0030(0x0008)
	class AActor*                                 CallFunc_GetTarget_ReturnValue;                    // 0x0038(0x0008)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0040(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0048(0x0001)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x0050(0x0018)
	bool                                          CallFunc_DoAttack_ReturnValue;                     // 0x0068(0x0001)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x0070(0x0018)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x0088(0x0008)
	bool                                          CallFunc_CanAttack_ReturnValue;                    // 0x0090(0x0001)
	bool                                          CallFunc_LessEqual_DoubleDouble_ReturnValue;       // 0x0091(0x0001)
};

}

