#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PBIK

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ControlRig_structs.hpp"


namespace SDK
{

// Enum PBIK.EPBIKLimitType
// NumValues: 0x0004
enum class EPBIKLimitType : uint8
{
	Free                                     = 0,
	Limited                                  = 1,
	Locked                                   = 2,
	EPBIKLimitType_MAX                       = 3,
};

// Enum PBIK.EPBIKRootBehavior
// NumValues: 0x0004
enum class EPBIKRootBehavior : uint8
{
	PrePull                                  = 0,
	PinToInput                               = 1,
	Free                                     = 2,
	EPBIKRootBehavior_MAX                    = 3,
};

// ScriptStruct PBIK.PBIKBoneSetting
// 0x0050 (0x0050 - 0x0000)
struct FPBIKBoneSetting final
{
public:
	class FName                                   bone;                                              // 0x0000(0x0008)
	float                                         RotationStiffness;                                 // 0x0008(0x0004)
	float                                         PositionStiffness;                                 // 0x000C(0x0004)
	EPBIKLimitType                                X;                                                 // 0x0010(0x0001)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)
	float                                         MinX;                                              // 0x0014(0x0004)
	float                                         MaxX;                                              // 0x0018(0x0004)
	EPBIKLimitType                                Y;                                                 // 0x001C(0x0001)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)
	float                                         MinY;                                              // 0x0020(0x0004)
	float                                         MaxY;                                              // 0x0024(0x0004)
	EPBIKLimitType                                Z;                                                 // 0x0028(0x0001)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)
	float                                         MinZ;                                              // 0x002C(0x0004)
	float                                         MaxZ;                                              // 0x0030(0x0004)
	bool                                          bUsePreferredAngles;                               // 0x0034(0x0001)
	uint8                                         Pad_35[0x3];                                       // 0x0035(0x0003)
	struct FVector                                PreferredAngles;                                   // 0x0038(0x0018)
};

// ScriptStruct PBIK.RootPrePullSettings
// 0x0020 (0x0020 - 0x0000)
struct FRootPrePullSettings final
{
public:
	float                                         RotationAlpha;                                     // 0x0000(0x0004)
	float                                         RotationAlphaX;                                    // 0x0004(0x0004)
	float                                         RotationAlphaY;                                    // 0x0008(0x0004)
	float                                         RotationAlphaZ;                                    // 0x000C(0x0004)
	float                                         PositionAlpha;                                     // 0x0010(0x0004)
	float                                         PositionAlphaX;                                    // 0x0014(0x0004)
	float                                         PositionAlphaY;                                    // 0x0018(0x0004)
	float                                         PositionAlphaZ;                                    // 0x001C(0x0004)
};

// ScriptStruct PBIK.PBIKSolverSettings
// 0x0040 (0x0040 - 0x0000)
struct FPBIKSolverSettings final
{
public:
	int32                                         Iterations;                                        // 0x0000(0x0004)
	int32                                         SubIterations;                                     // 0x0004(0x0004)
	float                                         MassMultiplier;                                    // 0x0008(0x0004)
	bool                                          bAllowStretch;                                     // 0x000C(0x0001)
	EPBIKRootBehavior                             RootBehavior;                                      // 0x000D(0x0001)
	uint8                                         Pad_E[0x2];                                        // 0x000E(0x0002)
	struct FRootPrePullSettings                   PrePullRootSettings;                               // 0x0010(0x0020)
	float                                         GlobalPullChainAlpha;                              // 0x0030(0x0004)
	float                                         MaxAngle;                                          // 0x0034(0x0004)
	float                                         OverRelaxation;                                    // 0x0038(0x0004)
	bool                                          bStartSolveFromInputPose;                          // 0x003C(0x0001)
	uint8                                         Pad_3D[0x3];                                       // 0x003D(0x0003)
};

// ScriptStruct PBIK.PBIKSolver
// 0x0058 (0x0058 - 0x0000)
struct FPBIKSolver final
{
public:
	uint8                                         Pad_0[0x58];                                       // 0x0000(0x0058)
};

// ScriptStruct PBIK.PBIKDebug
// 0x0008 (0x0008 - 0x0000)
struct FPBIKDebug final
{
public:
	float                                         DrawScale;                                         // 0x0000(0x0004)
	bool                                          bDrawDebug;                                        // 0x0004(0x0001)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)
};

// ScriptStruct PBIK.PBIKEffector
// 0x0090 (0x0090 - 0x0000)
struct FPBIKEffector final
{
public:
	class FName                                   bone;                                              // 0x0000(0x0008)
	uint8                                         Pad_8[0x8];                                        // 0x0008(0x0008)
	struct FTransform                             Transform;                                         // 0x0010(0x0060)
	float                                         PositionAlpha;                                     // 0x0070(0x0004)
	float                                         RotationAlpha;                                     // 0x0074(0x0004)
	float                                         StrengthAlpha;                                     // 0x0078(0x0004)
	int32                                         ChainDepth;                                        // 0x007C(0x0004)
	float                                         PullChainAlpha;                                    // 0x0080(0x0004)
	float                                         PinRotation;                                       // 0x0084(0x0004)
	uint8                                         Pad_88[0x8];                                       // 0x0088(0x0008)
};

// ScriptStruct PBIK.PBIKWorkData
// 0x0080 (0x0080 - 0x0000)
struct FPBIKWorkData final
{
public:
	bool                                          bNeedsInit;                                        // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	uint32                                        HashInitializedWith;                               // 0x0004(0x0004)
	TArray<int32>                                 BoneSettingToSolverBoneIndex;                      // 0x0008(0x0010)
	TArray<int32>                                 SolverBoneToElementIndex;                          // 0x0018(0x0010)
	struct FPBIKSolver                            Solver;                                            // 0x0028(0x0058)
};

// ScriptStruct PBIK.RigUnit_PBIK
// 0x0110 (0x0300 - 0x01F0)
struct FRigUnit_PBIK final : public FRigUnit_HighlevelBaseMutable
{
public:
	class FName                                   Root;                                              // 0x01F0(0x0008)
	TArray<struct FPBIKEffector>                  Effectors;                                         // 0x01F8(0x0010)
	TArray<int32>                                 EffectorSolverIndices;                             // 0x0208(0x0010)
	TArray<struct FPBIKBoneSetting>               BoneSettings;                                      // 0x0218(0x0010)
	TArray<class FName>                           ExcludedBones;                                     // 0x0228(0x0010)
	struct FPBIKSolverSettings                    Settings;                                          // 0x0238(0x0040)
	struct FPBIKDebug                             Debug;                                             // 0x0278(0x0008)
	struct FPBIKWorkData                          WorkData;                                          // 0x0280(0x0080)
};

}

