#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PistolHumanAnimBlueprint

#include "Basic.hpp"

#include "BaseHumanAnimBP_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass PistolHumanAnimBlueprint.PistolHumanAnimBlueprint_C
// 0x0000 (0x1FD70 - 0x1FD70)
class UPistolHumanAnimBlueprint_C : public UBaseHumanAnimBP_C
{
public:
	void UpdateLayeringValues();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PistolHumanAnimBlueprint_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PistolHumanAnimBlueprint_C")
	}
	static class UPistolHumanAnimBlueprint_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPistolHumanAnimBlueprint_C>();
	}
};

}

