#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerHUDNew

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerHUDNew.PlayerHUDNew_C
// 0x01B0 (0x0B40 - 0x0990)
class UPlayerHUDNew_C final : public UPlayerHUDUI
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0990(0x0008)
	class UWidgetAnimation*                       GamepadActiveToAlt;                                // 0x0998(0x0008)
	class UWidgetAnimation*                       GamepadActiveToNormal;                             // 0x09A0(0x0008)
	class UBorder*                                BuldingBorder;                                     // 0x09A8(0x0008)
	class UDataListEntryWidgetPrimalItem_CraftingPlayerHUD_C* CraftingButton;                        // 0x09B0(0x0008)
	class UTextBlock*                             CurrentFastInventoryRow;                           // 0x09B8(0x0008)
	class UElementStatusBarWidget_C*              ElementBar;                                        // 0x09C0(0x0008)
	class UProgressBarWidget*                     ExtraBrogress;                                     // 0x09C8(0x0008)
	class UTextBlock*                             FI_Keybind_0;                                      // 0x09D0(0x0008)
	class UTextBlock*                             FI_Keybind_1;                                      // 0x09D8(0x0008)
	class UTextBlock*                             FI_Keybind_2;                                      // 0x09E0(0x0008)
	class UTextBlock*                             FI_Keybind_3;                                      // 0x09E8(0x0008)
	class UTextBlock*                             FI_Keybind_4;                                      // 0x09F0(0x0008)
	class UTextBlock*                             FI_Keybind_5;                                      // 0x09F8(0x0008)
	class UTextBlock*                             FI_Keybind_6;                                      // 0x0A00(0x0008)
	class UTextBlock*                             FI_Keybind_7;                                      // 0x0A08(0x0008)
	class UImage*                                 GamepadActiveBackground;                           // 0x0A10(0x0008)
	class UImage*                                 GamepadActiveForFastInventory;                     // 0x0A18(0x0008)
	class UBorder*                                GamepadFI_Next;                                    // 0x0A20(0x0008)
	class UBorder*                                GamepadFI_Previous;                                // 0x0A28(0x0008)
	class UCanvasPanel*                           GamepadQuickbarButtons;                            // 0x0A30(0x0008)
	class UCanvasPanel*                           GamepadQuickbarButtons_FastInventory;              // 0x0A38(0x0008)
	class UImage*                                 Image;                                             // 0x0A40(0x0008)
	class UImage*                                 Image_484;                                         // 0x0A48(0x0008)
	class UCanvasPanel*                           ItemSlotPanelChild;                                // 0x0A50(0x0008)
	class UTextBlock*                             KBMDeactivateButton;                               // 0x0A58(0x0008)
	class UCanvasPanel*                           KBMQuickbarButtons;                                // 0x0A60(0x0008)
	class UCanvasPanel*                           KBMQuickbarButtons_FastInventory;                  // 0x0A68(0x0008)
	class UTextBlock*                             Keybdind1;                                         // 0x0A70(0x0008)
	class UTextBlock*                             Keybdind2;                                         // 0x0A78(0x0008)
	class UTextBlock*                             Keybdind3;                                         // 0x0A80(0x0008)
	class UTextBlock*                             Keybdind4;                                         // 0x0A88(0x0008)
	class UTextBlock*                             Keybdind5;                                         // 0x0A90(0x0008)
	class UTextBlock*                             Keybdind6;                                         // 0x0A98(0x0008)
	class UTextBlock*                             Keybdind7;                                         // 0x0AA0(0x0008)
	class UTextBlock*                             Keybdind8;                                         // 0x0AA8(0x0008)
	class UTextBlock*                             Keybdind9;                                         // 0x0AB0(0x0008)
	class UTextBlock*                             Keybind0;                                          // 0x0AB8(0x0008)
	class UCanvasPanel*                           MainCanvas;                                        // 0x0AC0(0x0008)
	class UTextBlock*                             MaxStructuresInRangeLabel;                         // 0x0AC8(0x0008)
	class UTextBlock*                             MaxStructuresInSmallRangeLabel;                    // 0x0AD0(0x0008)
	class UTextBlock*                             NextFI_KBM;                                        // 0x0AD8(0x0008)
	class UCanvasPanel*                           PanelNextFastInventory;                            // 0x0AE0(0x0008)
	class UTextBlock*                             PreviousFI_KBM;                                    // 0x0AE8(0x0008)
	class UPlayerHUDStatusBarsWidget_C*           PrimaryStatusBars;                                 // 0x0AF0(0x0008)
	class UDinoHUDStatusBarsWidget_C*             SecondaryStatusBars;                               // 0x0AF8(0x0008)
	class UTextBlock*                             TetherDistance;                                    // 0x0B00(0x0008)
	class UCanvasPanel*                           TextOverlayContainer;                              // 0x0B08(0x0008)
	class UWidgetSwitcher*                        WidgetSwitcher_GamepadDeactivateKeybind;           // 0x0B10(0x0008)
	bool                                          bFastInventory;                                    // 0x0B18(0x0001)
	uint8                                         Pad_B19[0x7];                                      // 0x0B19(0x0007)
	class FString                                 InFolderString;                                    // 0x0B20(0x0010)
	class FString                                 FastInventoryString;                               // 0x0B30(0x0010)

public:
	void Construct();
	void ExecuteUbergraph_PlayerHUDNew(int32 EntryPoint);
	void FixConsoleIcons();
	void GetAllChildRecursively(class UWidget* oneWidget, TArray<class UWidget*>* AllChildWidget);
	void OnFastInventoryChangedBP(bool bActivate);
	void OnGamepadActiveChangedBP(bool bIsGamepadActive);
	void SetElementBarBoostIconHidden(bool IsHidden);
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	void UpdatedKeybindingBP();
	void UpdateRunningIcon();
	void UpdateTetherDistance();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PlayerHUDNew_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PlayerHUDNew_C")
	}
	static class UPlayerHUDNew_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerHUDNew_C>();
	}
};

}

