#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponMachinedShotgun_Gauntlet

#include "Basic.hpp"

#include "PrimalItem_WeaponMachinedShotgun_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_WeaponMachinedShotgun_Gauntlet.PrimalItem_WeaponMachinedShotgun_Gauntlet_C
// 0x0000 (0x0B90 - 0x0B90)
class UPrimalItem_WeaponMachinedShotgun_Gauntlet_C final : public UPrimalItem_WeaponMachinedShotgun_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_WeaponMachinedShotgun_Gauntlet_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItem_WeaponMachinedShotgun_Gauntlet_C")
	}
	static class UPrimalItem_WeaponMachinedShotgun_Gauntlet_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_WeaponMachinedShotgun_Gauntlet_C>();
	}
};

}

