#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemStructure_LostColony_TekBunker

#include "Basic.hpp"


namespace SDK::Params
{

// Function PrimalItemStructure_LostColony_TekBunker.PrimalItemStructure_LostColony_TekBunker_C.BPAllowCrafting
// 0x0060 (0x0060 - 0x0000)
struct PrimalItemStructure_LostColony_TekBunker_C_BPAllowCrafting final
{
public:
	class AShooterPlayerController*               ForPC;                                             // 0x0000(0x0008)
	class FString                                 ReturnValue;                                       // 0x0008(0x0010)
	class AActor*                                 CallFunc_GetOwnerActor_ReturnValue;                // 0x0018(0x0008)
	class FString                                 CallFunc_BPAllowCrafting_ReturnValue;              // 0x0020(0x0010)
	class UWorld*                                 CallFunc_K2_GetWorld_ReturnValue;                  // 0x0030(0x0008)
	class UObject*                                CallFunc_GetClassDefaultObject_ReturnValue;        // 0x0038(0x0008)
	class UTekBunker_FunctionLib_C*               K2Node_DynamicCast_AsTek_Bunker_Function_Lib;      // 0x0040(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0048(0x0001)
	bool                                          CallFunc_GetPlayerOwnsTekDrillOrLostColony_OwnsEither; // 0x0049(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x004A(0x0001)
	uint8                                         Pad_4B[0x5];                                       // 0x004B(0x0005)
	class FString                                 CallFunc_SelectString_ReturnValue;                 // 0x0050(0x0010)
};

}

