#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalBuff_ChangeMaterialScalarParamOverTime

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalBuff_ChangeMaterialScalarParamOverTime.PrimalBuff_ChangeMaterialScalarParamOverTime_C
// 0x0048 (0x0C28 - 0x0BE0)
class APrimalBuff_ChangeMaterialScalarParamOverTime_C : public APrimalBuff
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BE0(0x0008)
	float                                         ParamTimeline_Scalar_CEFDC60C489CB14F246A90BDE2569987; // 0x0BE8(0x0004)
	ETimelineDirection                            ParamTimeline__Direction_CEFDC60C489CB14F246A90BDE2569987; // 0x0BEC(0x0001)
	uint8                                         Pad_BED[0x3];                                      // 0x0BED(0x0003)
	class UTimelineComponent*                     ParamTimeline;                                     // 0x0BF0(0x0008)
	class FName                                   ParamName;                                         // 0x0BF8(0x0008)
	double                                        ForwardDuration;                                   // 0x0C00(0x0008)
	double                                        StartValue;                                        // 0x0C08(0x0008)
	double                                        EndValue;                                          // 0x0C10(0x0008)
	double                                        ReverseDuration;                                   // 0x0C18(0x0008)
	double                                        CurrentDuration;                                   // 0x0C20(0x0008)

public:
	void BPSetupForInstigator(class AActor* ForInstigator);
	void ExecuteUbergraph_PrimalBuff_ChangeMaterialScalarParamOverTime(int32 EntryPoint);
	void ParamTimeline__FinishedFunc();
	void ParamTimeline__UpdateFunc();
	void ReceiveBeginPlay();
	void Set_Param_Value(class UMeshComponent* Mesh, double Value);
	void SetValues(double Value);
	void StartTimeline(bool Forward_);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalBuff_ChangeMaterialScalarParamOverTime_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalBuff_ChangeMaterialScalarParamOverTime_C")
	}
	static class APrimalBuff_ChangeMaterialScalarParamOverTime_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<APrimalBuff_ChangeMaterialScalarParamOverTime_C>();
	}
};

}

