#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_Spawner_Mek

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "PrimalItem_DinoSpawner_Base_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItem_Spawner_Mek.PrimalItem_Spawner_Mek_C
// 0x0090 (0x0D90 - 0x0D00)
class UPrimalItem_Spawner_Mek_C final : public UPrimalItem_DinoSpawner_Base_C
{
public:
	class AShooterCharacter*                      CraftingShooterChar;                               // 0x0D00(0x0008)
	uint8                                         Pad_D08[0x8];                                      // 0x0D08(0x0008)
	struct FTransform                             SpawnTransform;                                    // 0x0D10(0x0060)
	class FString                                 MekSpawnString;                                    // 0x0D70(0x0010)
	int32                                         NumSpawnAttempts;                                  // 0x0D80(0x0004)
	uint8                                         Pad_D84[0x4];                                      // 0x0D84(0x0004)
	double                                        SpawnForwardOffset;                                // 0x0D88(0x0008)

public:
	class FString BPAllowCrafting(class AShooterPlayerController* ForPC);
	bool BPCanUse(bool bIgnoreCooldown);
	void BPCrafted();
	void GetStatDisplayString(EPrimalCharacterStatusValue Stat, int32 Value, int32 StatConvertMapIndex, class FString* StatDisplay, class FString* ValueDisplay, bool* ShowInTooltip);
	void GetValidSpawnTransform(struct FTransform* SpawnTransform_0, bool* SpawnValid);
	void SpawnCraftedMek();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItem_Spawner_Mek_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItem_Spawner_Mek_C")
	}
	static class UPrimalItem_Spawner_Mek_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItem_Spawner_Mek_C>();
	}
};

}

