#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItemArmor_BaseAccessory

#include "Basic.hpp"

#include "PrimalItemSkinGeneric_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrimalItemArmor_BaseAccessory.PrimalItemArmor_BaseAccessory_C
// 0x0060 (0x0C00 - 0x0BA0)
class UPrimalItemArmor_BaseAccessory_C : public UPrimalItemSkinGeneric_C
{
public:
	TMap<class FName, class FText>                SlotNameMap;                                       // 0x0B98(0x0050)
	class FText                                   CustomSlotName;                                    // 0x0BE8(0x0010)

public:
	class FString BPGetItemDescription(const class FString& InDescription, bool bGetLongDescription, class AShooterPlayerController* ForPC);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("PrimalItemArmor_BaseAccessory_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"PrimalItemArmor_BaseAccessory_C")
	}
	static class UPrimalItemArmor_BaseAccessory_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrimalItemArmor_BaseAccessory_C>();
	}
};

}

