#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrimalItem_WeaponScoutRemote

#include "Basic.hpp"

#include "ShooterGame_structs.hpp"
#include "ScoutRemoteReturnCode_structs.hpp"
#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.BlueprintEquipped
// 0x0001 (0x0001 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_BlueprintEquipped final
{
public:
	bool                                          bIsFromSaveGame;                                   // 0x0000(0x0001)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.BPGetItemDescription
// 0x03D0 (0x03D0 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_BPGetItemDescription final
{
public:
	class FString                                 InDescription;                                     // 0x0000(0x0010)
	bool                                          bGetLongDescription;                               // 0x0010(0x0001)
	uint8                                         Pad_11[0x7];                                       // 0x0011(0x0007)
	class AShooterPlayerController*               ForPC;                                             // 0x0018(0x0008)
	class FString                                 ReturnValue;                                       // 0x0020(0x0010)
	TArray<double>                                Stats;                                             // 0x0030(0x0010)
	class FString                                 Result;                                            // 0x0040(0x0010)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0050(0x0010)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0060(0x0004)
	uint8                                         Pad_64[0x4];                                       // 0x0064(0x0004)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData;              // 0x0068(0x0048)
	EPrimalCharacterStatusValue                   CallFunc_ConvertIntToCharacterStatusEnum_ReturnValue; // 0x00B0(0x0001)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x00B1(0x0001)
	uint8                                         Pad_B2[0x2];                                       // 0x00B2(0x0002)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x00B4(0x0004)
	TArray<double>                                CallFunc_GetScoutStats_Stats;                      // 0x00B8(0x0010)
	double                                        CallFunc_Array_Get_Item;                           // 0x00C8(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00D0(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x00D4(0x0004)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x00D8(0x0001)
	uint8                                         Pad_D9[0x7];                                       // 0x00D9(0x0007)
	class UObject*                                CallFunc_GetClassDefaultObject_ReturnValue;        // 0x00E0(0x0008)
	class UObject*                                CallFunc_GetClassDefaultObject_ReturnValue_1;      // 0x00E8(0x0008)
	class AScout_Character_BP_C*                  K2Node_DynamicCast_AsScout_Character_BP;           // 0x00F0(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x00F8(0x0001)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)
	class UPrimalItemResource_ElementDust_C*      K2Node_DynamicCast_AsPrimal_Item_Resource_Element_Dust; // 0x0100(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0108(0x0001)
	uint8                                         Pad_109[0x3];                                      // 0x0109(0x0003)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x010C(0x0004)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0110(0x0010)
	double                                        CallFunc_Array_Get_Item_1;                         // 0x0120(0x0008)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_1;            // 0x0128(0x0048)
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue;            // 0x0170(0x0010)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array;                            // 0x0180(0x0010)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_2;            // 0x0190(0x0048)
	class FText                                   CallFunc_Format_ReturnValue;                       // 0x01D8(0x0010)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_1;                          // 0x01E8(0x0010)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x01F8(0x0010)
	class FText                                   CallFunc_Format_ReturnValue_1;                     // 0x0208(0x0010)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0218(0x0010)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0228(0x0001)
	uint8                                         Pad_229[0x7];                                      // 0x0229(0x0007)
	class FString                                 CallFunc_SelectString_ReturnValue;                 // 0x0230(0x0010)
	double                                        CallFunc_FMin_ReturnValue;                         // 0x0240(0x0008)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_1;        // 0x0248(0x0001)
	uint8                                         Pad_249[0x3];                                      // 0x0249(0x0003)
	int32                                         CallFunc_FFloor_ReturnValue;                       // 0x024C(0x0004)
	class FString                                 CallFunc_SelectString_ReturnValue_1;               // 0x0250(0x0010)
	double                                        CallFunc_Conv_IntToDouble_ReturnValue;             // 0x0260(0x0008)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_2;        // 0x0268(0x0001)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue_3;        // 0x0269(0x0001)
	uint8                                         Pad_26A[0x6];                                      // 0x026A(0x0006)
	class FString                                 CallFunc_SelectString_ReturnValue_2;               // 0x0270(0x0010)
	double                                        CallFunc_SelectFloat_ReturnValue;                  // 0x0280(0x0008)
	class FString                                 CallFunc_SelectString_ReturnValue_3;               // 0x0288(0x0010)
	class FText                                   CallFunc_Conv_DoubleToText_ReturnValue_1;          // 0x0298(0x0010)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x02A8(0x0010)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_3;            // 0x02B8(0x0048)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_4;            // 0x0300(0x0048)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_3;          // 0x0348(0x0010)
	struct FFormatArgumentData                    K2Node_MakeStruct_FormatArgumentData_5;            // 0x0358(0x0048)
	TArray<struct FFormatArgumentData>            K2Node_MakeArray_Array_2;                          // 0x03A0(0x0010)
	class FText                                   CallFunc_Format_ReturnValue_2;                     // 0x03B0(0x0010)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x03C0(0x0010)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.BPGetItemIcon
// 0x0020 (0x0020 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_BPGetItemIcon final
{
public:
	class AShooterPlayerController*               ForPC;                                             // 0x0000(0x0008)
	class UTexture2D*                             ReturnValue;                                       // 0x0008(0x0008)
	class UTexture2D*                             Result;                                            // 0x0010(0x0008)
	class UTexture2D*                             CallFunc_GetItemIconJIT_ReturnValue;               // 0x0018(0x0008)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.BPGetItemName
// 0x0038 (0x0038 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_BPGetItemName final
{
public:
	class FString                                 ItemNameIn;                                        // 0x0000(0x0010)
	class AShooterPlayerController*               ForPC;                                             // 0x0010(0x0008)
	class FString                                 ReturnValue;                                       // 0x0018(0x0010)
	class FString                                 Result;                                            // 0x0028(0x0010)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.Can FireWeapon
// 0x0128 (0x0128 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_Can_FireWeapon final
{
public:
	bool                                          Result;                                            // 0x0000(0x0001)
	EScoutRemoteReturnCode                        FailReason;                                        // 0x0001(0x0001)
	uint8                                         Pad_2[0x6];                                        // 0x0002(0x0006)
	TSoftClassPtr<class UClass>                   BuffScoutVision;                                   // 0x0008(0x0028)
	EScoutRemoteReturnCode                        ReturnCode;                                        // 0x0030(0x0001)
	bool                                          retVal;                                            // 0x0031(0x0001)
	uint8                                         Pad_32[0x6];                                       // 0x0032(0x0006)
	class AWeapScoutRemote_C*                     K2Node_DynamicCast_AsWeap_Scout_Remote;            // 0x0038(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0040(0x0001)
	uint8                                         Pad_41[0x7];                                       // 0x0041(0x0007)
	class AActor*                                 CallFunc_GetOwner_ReturnValue;                     // 0x0048(0x0008)
	class AShooterCharacter*                      K2Node_DynamicCast_AsShooter_Character;            // 0x0050(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0058(0x0001)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)
	int32                                         CallFunc_GetItemTemplateQuantity_ReturnValue;      // 0x005C(0x0004)
	TSubclassOf<class UObject>                    CallFunc_Conv_SoftClassReferenceToClass_ReturnValue; // 0x0060(0x0008)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0068(0x0001)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)
	class UClass*                                 K2Node_ClassDynamicCast_AsPrimal_Buff;             // 0x0070(0x0008)
	bool                                          K2Node_ClassDynamicCast_bSuccess;                  // 0x0078(0x0001)
	bool                                          CallFunc_HasBuff_ReturnValue;                      // 0x0079(0x0001)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue;              // 0x007A(0x0001)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_1;            // 0x007B(0x0001)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x007C(0x0004)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_1;             // 0x0080(0x0004)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0084(0x0001)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_2;            // 0x0085(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0086(0x0001)
	uint8                                         Pad_87[0x1];                                       // 0x0087(0x0001)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_2;             // 0x0088(0x0004)
	uint8                                         Pad_8C[0x4];                                       // 0x008C(0x0004)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0090(0x0018)
	uint8                                         CallFunc_MakeLiteralByte_ReturnValue_3;            // 0x00A8(0x0001)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x00A9(0x0001)
	uint8                                         Pad_AA[0x2];                                       // 0x00AA(0x0002)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue_3;             // 0x00AC(0x0004)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00B0(0x0001)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue_1;        // 0x00B8(0x0018)
	struct FVector                                CallFunc_Subtract_VectorVector_ReturnValue;        // 0x00D0(0x0018)
	bool                                          CallFunc_IsValid_ReturnValue_3;                    // 0x00E8(0x0001)
	uint8                                         Pad_E9[0x7];                                       // 0x00E9(0x0007)
	double                                        CallFunc_VSize_ReturnValue;                        // 0x00F0(0x0008)
	bool                                          CallFunc_Less_DoubleDouble_ReturnValue;            // 0x00F8(0x0001)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)
	float                                         CallFunc_BPGetCurrentStatusValue_ReturnValue;      // 0x00FC(0x0004)
	bool                                          CallFunc_BooleanAND_ReturnValue_1;                 // 0x0100(0x0001)
	bool                                          CallFunc_Greater_DoubleDouble_ReturnValue;         // 0x0101(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x0102(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue_1;                // 0x0103(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue_2;                 // 0x0104(0x0001)
	uint8                                         Pad_105[0x3];                                      // 0x0105(0x0003)
	int32                                         CallFunc_SelectInt_ReturnValue;                    // 0x0108(0x0004)
	int32                                         CallFunc_GetItemTemplateQuantity_ReturnValue_1;    // 0x010C(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x0110(0x0001)
	bool                                          CallFunc_BooleanOR_ReturnValue;                    // 0x0111(0x0001)
	bool                                          CallFunc_Not_PreBool_ReturnValue_2;                // 0x0112(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue_3;                 // 0x0113(0x0001)
	int32                                         CallFunc_SelectInt_ReturnValue_1;                  // 0x0114(0x0004)
	int32                                         CallFunc_SelectInt_ReturnValue_2;                  // 0x0118(0x0004)
	uint8                                         CallFunc_Conv_IntToByte_ReturnValue;               // 0x011C(0x0001)
	uint8                                         CallFunc_GetValidValue_ReturnValue;                // 0x011D(0x0001)
	uint8                                         Pad_11E[0x2];                                      // 0x011E(0x0002)
	double                                        CallFunc_Greater_DoubleDouble_A_ImplicitCast;      // 0x0120(0x0008)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.GetScoutStats
// 0x00E8 (0x00E8 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_GetScoutStats final
{
public:
	TArray<double>                                Stats;                                             // 0x0000(0x0010)
	TArray<double>                                Result;                                            // 0x0010(0x0010)
	struct FCustomItemData                        CallFunc_GetCustomItemData_OutData;                // 0x0020(0x00A8)
	bool                                          CallFunc_GetCustomItemData_ReturnValue;            // 0x00C8(0x0001)
	uint8                                         Pad_C9[0x3];                                       // 0x00C9(0x0003)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x00CC(0x0004)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x00D0(0x0001)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)
	TArray<double>                                K2Node_VariableSet_Result_ImplicitCast;            // 0x00D8(0x0010)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.ScoutPossessedBySurvivor
// 0x0010 (0x0010 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_ScoutPossessedBySurvivor final
{
public:
	class AWeapScoutRemote_C*                     K2Node_DynamicCast_AsWeap_Scout_Remote;            // 0x0000(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0008(0x0001)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.ScoutReleasedPossessingSurvivor
// 0x0010 (0x0010 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_ScoutReleasedPossessingSurvivor final
{
public:
	class AWeapScoutRemote_C*                     K2Node_DynamicCast_AsWeap_Scout_Remote;            // 0x0000(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0008(0x0001)
};

// Function PrimalItem_WeaponScoutRemote.PrimalItem_WeaponScoutRemote_C.SetScoutCharacterStatusValues
// 0x0158 (0x0158 - 0x0000)
struct PrimalItem_WeaponScoutRemote_C_SetScoutCharacterStatusValues final
{
public:
	TArray<double>                                Stats;                                             // 0x0000(0x0010)
	class UObject*                                CallFunc_GetClassDefaultObject_ReturnValue;        // 0x0010(0x0008)
	class AScout_Character_BP_C*                  K2Node_DynamicCast_AsScout_Character_BP;           // 0x0018(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)
	TArray<class FString>                         K2Node_MakeArray_Array;                            // 0x0028(0x0010)
	TArray<class UObject*>                        K2Node_MakeArray_Array_1;                          // 0x0038(0x0010)
	int32                                         CallFunc_Conv_ByteToInt_ReturnValue;               // 0x0048(0x0004)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)
	TArray<class UClass*>                         K2Node_MakeArray_Array_2;                          // 0x0050(0x0010)
	double                                        CallFunc_Array_Get_Item;                           // 0x0060(0x0008)
	TArray<class FName>                           K2Node_MakeArray_Array_3;                          // 0x0068(0x0010)
	float                                         CallFunc_GetFloatValue_ReturnValue;                // 0x0078(0x0004)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)
	struct FCustomItemData                        K2Node_MakeStruct_CustomItemData;                  // 0x0080(0x00A8)
	double                                        CallFunc_Multiply_DoubleDouble_ReturnValue;        // 0x0128(0x0008)
	TArray<float>                                 K2Node_MakeStruct_CustomDataFloats_ImplicitCast;   // 0x0130(0x0010)
	float                                         CallFunc_GetFloatValue_InTime_ImplicitCast;        // 0x0140(0x0004)
	uint8                                         Pad_144[0x4];                                      // 0x0144(0x0004)
	double                                        CallFunc_Multiply_DoubleDouble_B_ImplicitCast;     // 0x0148(0x0008)
	float                                         K2Node_VariableSet_ItemRating_ImplicitCast;        // 0x0150(0x0004)
};

}

