#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProjYiLingFeather_Razor

#include "Basic.hpp"

#include "ProjYiLingFeather_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProjYiLingFeather_Razor.ProjYiLingFeather_Razor_C
// 0x0000 (0x07C8 - 0x07C8)
class AProjYiLingFeather_Razor_C final : public AProjYiLingFeather_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ProjYiLingFeather_Razor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ProjYiLingFeather_Razor_C")
	}
	static class AProjYiLingFeather_Razor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjYiLingFeather_Razor_C>();
	}
};

}

