#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProjTekTurret

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProjTekTurret.ProjTekTurret_C
// 0x0000 (0x07B0 - 0x07B0)
class AProjTekTurret_C final : public AShooterProjectile
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ProjTekTurret_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ProjTekTurret_C")
	}
	static class AProjTekTurret_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AProjTekTurret_C>();
	}
};

}

