#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProximitySound

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ProximitySound.ProximitySound_C
// 0x0060 (0x0130 - 0x00D0)
class UProximitySound_C final : public UActorComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00D0(0x0008)
	double                                        CheckInterval;                                     // 0x00D8(0x0008)
	double                                        MinCooldownTime;                                   // 0x00E0(0x0008)
	double                                        MaxCooldownTime;                                   // 0x00E8(0x0008)
	double                                        OverlapScale;                                      // 0x00F0(0x0008)
	class USoundBase*                             ProximitySound;                                    // 0x00F8(0x0008)
	class USoundBase*                             ExitSound;                                         // 0x0100(0x0008)
	class UAudioComponent*                        AudioComponentReferance;                           // 0x0108(0x0008)
	double                                        ChanceToPlay;                                      // 0x0110(0x0008)
	double                                        OverlapDistance;                                   // 0x0118(0x0008)
	bool                                          isOverlapping;                                     // 0x0120(0x0001)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)
	double                                        FadeOutTime;                                       // 0x0128(0x0008)

public:
	void ReceiveBeginPlay();
	void PlaySound(class USoundBase* SoundToPlay, bool* SoundValid);
	void ExecuteUbergraph_ProximitySound(int32 EntryPoint);
	void CheckOverlap();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("ProximitySound_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"ProximitySound_C")
	}
	static class UProximitySound_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UProximitySound_C>();
	}
};

}

