#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Rex_PPAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Rex_PPAnimBP.Rex_PPAnimBP_C.ExecuteUbergraph_Rex_PPAnimBP
// 0x0020 (0x0020 - 0x0000)
struct Rex_PPAnimBP_C_ExecuteUbergraph_Rex_PPAnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)
	class APawn*                                  CallFunc_TryGetPawnOwner_ReturnValue;              // 0x0008(0x0008)
	class APrimalDinoCharacter*                   K2Node_DynamicCast_AsPrimal_Dino_Character;        // 0x0010(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0018(0x0001)
	bool                                          CallFunc_IsDead_ReturnValue;                       // 0x0019(0x0001)
	uint8                                         Pad_1A[0x2];                                       // 0x001A(0x0002)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x001C(0x0004)
};

// Function Rex_PPAnimBP.Rex_PPAnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct Rex_PPAnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)
};

// Function Rex_PPAnimBP.Rex_PPAnimBP_C.BlueprintThreadSafeUpdateAnimation
// 0x0068 (0x0068 - 0x0000)
struct Rex_PPAnimBP_C_BlueprintThreadSafeUpdateAnimation final
{
public:
	float                                         DeltaTime;                                         // 0x0000(0x0004)
	float                                         CallFunc_GetCurveValueWithDefault_OutValue;        // 0x0004(0x0004)
	bool                                          CallFunc_GetCurveValueWithDefault_ReturnValue;     // 0x0008(0x0001)
	uint8                                         Pad_9[0x3];                                        // 0x0009(0x0003)
	float                                         CallFunc_GetCurveValueWithDefault_OutValue_1;      // 0x000C(0x0004)
	bool                                          CallFunc_GetCurveValueWithDefault_ReturnValue_1;   // 0x0010(0x0001)
	uint8                                         Pad_11[0x3];                                       // 0x0011(0x0003)
	float                                         CallFunc_GetCurveValueWithDefault_OutValue_2;      // 0x0014(0x0004)
	bool                                          CallFunc_GetCurveValueWithDefault_ReturnValue_2;   // 0x0018(0x0001)
	uint8                                         Pad_19[0x3];                                       // 0x0019(0x0003)
	float                                         CallFunc_GetCurveValueWithDefault_OutValue_3;      // 0x001C(0x0004)
	bool                                          CallFunc_GetCurveValueWithDefault_ReturnValue_3;   // 0x0020(0x0001)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)
	float                                         CallFunc_GetCurveValueWithDefault_OutValue_4;      // 0x0024(0x0004)
	bool                                          CallFunc_GetCurveValueWithDefault_ReturnValue_4;   // 0x0028(0x0001)
	uint8                                         Pad_29[0x3];                                       // 0x0029(0x0003)
	float                                         CallFunc_GetCurveValueWithDefault_OutValue_5;      // 0x002C(0x0004)
	bool                                          CallFunc_GetCurveValueWithDefault_ReturnValue_5;   // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	double                                        K2Node_VariableSet_r_Flex_Thigh_Rear_ImplicitCast; // 0x0038(0x0008)
	double                                        K2Node_VariableSet_r_Flex_Thigh_Front_ImplicitCast; // 0x0040(0x0008)
	double                                        K2Node_VariableSet_r_Flex_Calf_ImplicitCast;       // 0x0048(0x0008)
	double                                        K2Node_VariableSet_l_Flex_Thigh_Front_ImplicitCast; // 0x0050(0x0008)
	double                                        K2Node_VariableSet_l_Flex_Thigh_Rear_ImplicitCast; // 0x0058(0x0008)
	double                                        K2Node_VariableSet_l_Flex_Calf_ImplicitCast;       // 0x0060(0x0008)
};

// Function Rex_PPAnimBP.Rex_PPAnimBP_C.AnimGraph
// 0x0020 (0x0020 - 0x0000)
struct Rex_PPAnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)
	struct FPoseLink                              AnimGraph_0;                                       // 0x0010(0x0010)
};

}

