#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Sauropod_Character_BP

#include "Basic.hpp"


namespace SDK::Params
{

// Function Sauropod_Character_BP.Sauropod_Character_BP_C.GetSocketForMeleeTraceForHitBlockers
// 0x000C (0x000C - 0x0000)
struct Sauropod_Character_BP_C_GetSocketForMeleeTraceForHitBlockers final
{
public:
	int32                                         AttackIndex;                                       // 0x0000(0x0004)
	class FName                                   ReturnValue;                                       // 0x0004(0x0008)
};

}

