#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ScoutTrackerStates

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum ScoutTrackerStates.ScoutTrackerStates
// NumValues: 0x0008
enum class EScoutTrackerStates : uint8
{
	NewEnumerator3                           = 0,
	NewEnumerator4                           = 1,
	NewEnumerator1                           = 2,
	NewEnumerator0                           = 3,
	NewEnumerator2                           = 4,
	NewEnumerator6                           = 5,
	NewEnumerator5                           = 6,
	ScoutTrackerStates_MAX                   = 7,
};

}

