#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SE_DinoSpawnEntriesGreenDesert

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SE_DinoSpawnEntriesGreenDesert.SE_DinoSpawnEntriesGreenDesert_C
// 0x0000 (0x0050 - 0x0050)
class USE_DinoSpawnEntriesGreenDesert_C final : public UNPCSpawnEntriesContainer
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("SE_DinoSpawnEntriesGreenDesert_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"SE_DinoSpawnEntriesGreenDesert_C")
	}
	static class USE_DinoSpawnEntriesGreenDesert_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USE_DinoSpawnEntriesGreenDesert_C>();
	}
};

}

