#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: StateReq_Base

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass StateReq_Base.StateReq_Base_C
// 0x0010 (0x0040 - 0x0030)
class UStateReq_Base_C : public UObject_WithWorldContext
{
public:
	bool                                          Advanced_Debug;                                    // 0x0030(0x0001)
	bool                                          Debug;                                             // 0x0031(0x0001)
	uint8                                         Pad_32[0x2];                                       // 0x0032(0x0002)
	class FName                                   Notes;                                             // 0x0034(0x0008)

public:
	void Succeeds_Requirement_(class UObject*& Object_This_is_For, class UObject*& State_Machine_Ref, uint8 Transition_State_Byte, bool* Succeeds, class FName* Fail_Reason);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("StateReq_Base_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"StateReq_Base_C")
	}
	static class UStateReq_Base_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UStateReq_Base_C>();
	}
};

}

