#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SteamInventoryPopupUI

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK::Params
{

// Function SteamInventoryPopupUI.SteamInventoryPopupUI_C.ExecuteUbergraph_SteamInventoryPopupUI
// 0x0050 (0x0050 - 0x0000)
struct SteamInventoryPopupUI_C_ExecuteUbergraph_SteamInventoryPopupUI final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0004(0x0038)
	float                                         K2Node_Event_InDeltaTime;                          // 0x003C(0x0004)
	class APawn*                                  CallFunc_GetOwningPlayerPawn_ReturnValue;          // 0x0040(0x0008)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)
	ESlateVisibility                              CallFunc_GetVisibility_ReturnValue;                // 0x0049(0x0001)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x004A(0x0001)
};

// Function SteamInventoryPopupUI.SteamInventoryPopupUI_C.Tick
// 0x003C (0x003C - 0x0000)
struct SteamInventoryPopupUI_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)
};

}

