#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Stego_GroundConform_AnimBlueprint

#include "Basic.hpp"

#include "Stego_GroundConform_AnimBlueprint_classes.hpp"
#include "Stego_GroundConform_AnimBlueprint_parameters.hpp"


namespace SDK
{

// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPoseLink&                 InPose                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UStego_GroundConform_AnimBlueprint_C::AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "AnimGraph");

	Params::Stego_GroundConform_AnimBlueprint_C_AnimGraph Parms{};

	Parms.InPose = std::move(InPose);

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.BlueprintInitializeAnimation
// (Event, Public, BlueprintEvent)

void UStego_GroundConform_AnimBlueprint_C::BlueprintInitializeAnimation()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "BlueprintInitializeAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStego_GroundConform_AnimBlueprint_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "BlueprintUpdateAnimation");

	Params::Stego_GroundConform_AnimBlueprint_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_2F411CBD426D1EAAD67856BCDC620287
// (BlueprintEvent)

void UStego_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_2F411CBD426D1EAAD67856BCDC620287()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ApplyAdditive_2F411CBD426D1EAAD67856BCDC620287");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ControlRig_036958D142C8EE4C5C2C138BE6F5BFFD
// (BlueprintEvent)

void UStego_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ControlRig_036958D142C8EE4C5C2C138BE6F5BFFD()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ControlRig_036958D142C8EE4C5C2C138BE6F5BFFD");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_F20A1D4044C8A91A1F40FB96E7F607C3
// (BlueprintEvent)

void UStego_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_F20A1D4044C8A91A1F40FB96E7F607C3()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_ModifyBone_F20A1D4044C8A91A1F40FB96E7F607C3");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_A14AACE94C5C21A180A02C8F22E69DDA
// (BlueprintEvent)

void UStego_GroundConform_AnimBlueprint_C::EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_A14AACE94C5C21A180A02C8F22E69DDA()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "EvaluateGraphExposedInputs_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint_AnimGraphNode_TwoWayBlend_A14AACE94C5C21A180A02C8F22E69DDA");

	UObject::ProcessEvent(Func, nullptr);
}


// Function Stego_GroundConform_AnimBlueprint.Stego_GroundConform_AnimBlueprint_C.ExecuteUbergraph_Stego_GroundConform_AnimBlueprint
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UStego_GroundConform_AnimBlueprint_C::ExecuteUbergraph_Stego_GroundConform_AnimBlueprint(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Stego_GroundConform_AnimBlueprint_C", "ExecuteUbergraph_Stego_GroundConform_AnimBlueprint");

	Params::Stego_GroundConform_AnimBlueprint_C_ExecuteUbergraph_Stego_GroundConform_AnimBlueprint Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

