#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_WeapAnimWith3P

#include "Basic.hpp"

#include "ShooterGame_structs.hpp"


namespace SDK
{

// UserDefinedStruct Struct_WeapAnimWith3P.Struct_WeapAnimWith3P
// 0x0018 (0x0018 - 0x0000)
struct FStruct_WeapAnimWith3P final
{
public:
	struct FWeaponAnim                            WeaponAnimMontageWeapFPVandPlayerTPV_3_E345A22A482C21885C5552A880D6082C; // 0x0000(0x0010)
	class UAnimMontage*                           Weapon3PAnimMontage_6_6173121A4C1DE5047A5B719782DF0195; // 0x0010(0x0008)
};

}

