#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Task_VRMainBossFindAndLookAtTarget

#include "Basic.hpp"

#include "AIModule_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Task_VRMainBossFindAndLookAtTarget.Task_VRMainBossFindAndLookAtTarget_C
// 0x0008 (0x00B0 - 0x00A8)
class UTask_VRMainBossFindAndLookAtTarget_C final : public UBTTask_BlueprintBase
{
public:
	double                                        SuccessAngle;                                      // 0x00A8(0x0008)

public:
	void ReceiveTick(class AActor* OwnerActor, float DeltaSeconds);
	void ReceiveExecute(class AActor* OwnerActor);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Task_VRMainBossFindAndLookAtTarget_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Task_VRMainBossFindAndLookAtTarget_C")
	}
	static class UTask_VRMainBossFindAndLookAtTarget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTask_VRMainBossFindAndLookAtTarget_C>();
	}
};

}

