#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Task_MissionIdle

#include "Basic.hpp"

#include "Task_MissionIdle_classes.hpp"
#include "Task_MissionIdle_parameters.hpp"


namespace SDK
{

// Function Task_MissionIdle.Task_MissionIdle_C.ReceiveExecute
// (Event, Protected, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           OwnerActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UTask_MissionIdle_C::ReceiveExecute(class AActor* OwnerActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("Task_MissionIdle_C", "ReceiveExecute");

	Params::Task_MissionIdle_C_ReceiveExecute Parms{};

	Parms.OwnerActor = OwnerActor;

	UObject::ProcessEvent(Func, &Parms);
}

}

