#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tek_Generator_RIG_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// ScriptStruct Tek_Generator_RIG_AnimBP.Tek_Generator_RIG_AnimBP_C.AnimBlueprintGeneratedMutableData
// 0x0001 (0x0002 - 0x0001)
struct Tek_Generator_RIG_AnimBP::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	bool                                          __BoolProperty;                                    // 0x0001(0x0001)
};

// ScriptStruct Tek_Generator_RIG_AnimBP.Tek_Generator_RIG_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x01F7 (0x01F8 - 0x0001)
struct Tek_Generator_RIG_AnimBP::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	class FName                                   __NameProperty_24;                                 // 0x0004(0x0008)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)
	class UBlendProfile*                          __BlendProfile_25;                                 // 0x0010(0x0008)
	class UCurveFloat*                            __CurveFloat_26;                                   // 0x0018(0x0008)
	EAlphaBlendOption                             __EnumProperty_27;                                 // 0x0020(0x0001)
	EBlendListTransitionType                      __EnumProperty_28;                                 // 0x0021(0x0001)
	uint8                                         Pad_22[0x6];                                       // 0x0022(0x0006)
	TArray<float>                                 __ArrayProperty_29;                                // 0x0028(0x0010)
	struct FAnimNodeFunctionRef                   __StructProperty_30;                               // 0x0038(0x0020)
	bool                                          __BoolProperty_31;                                 // 0x0058(0x0001)
	uint8                                         Pad_59[0x3];                                       // 0x0059(0x0003)
	float                                         __FloatProperty_32;                                // 0x005C(0x0004)
	struct FInputScaleBiasClampConstants          __StructProperty_33;                               // 0x0060(0x002C)
	float                                         __FloatProperty_34;                                // 0x008C(0x0004)
	bool                                          __BoolProperty_35;                                 // 0x0090(0x0001)
	EAnimSyncMethod                               __EnumProperty_36;                                 // 0x0091(0x0001)
	EAnimGroupRole                                __ByteProperty_37;                                 // 0x0092(0x0001)
	uint8                                         Pad_93[0x1];                                       // 0x0093(0x0001)
	class FName                                   __NameProperty_38;                                 // 0x0094(0x0008)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x00A0(0x0080)
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0120(0x0018)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                           // 0x0138(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_BlendListByBool;                // 0x0168(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;               // 0x0198(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;                 // 0x01C8(0x0030)
};

}

