#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: tek_tapejara_RIG_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function tek_tapejara_RIG_AnimBP.tek_tapejara_RIG_AnimBP_C.ExecuteUbergraph_tek_tapejara_RIG_AnimBP
// 0x0068 (0x0068 - 0x0000)
struct tek_tapejara_RIG_AnimBP_C_ExecuteUbergraph_tek_tapejara_RIG_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
	bool                                          Temp_bool_True_if_break_was_hit_Variable;          // 0x0004(0x0001)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)
	int32                                         Temp_int_Array_Index_Variable;                     // 0x0008(0x0004)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x000C(0x0001)
	uint8                                         Pad_D[0x3];                                        // 0x000D(0x0003)
	int32                                         Temp_int_Loop_Counter_Variable;                    // 0x0010(0x0004)
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0014(0x0004)
	float                                         K2Node_Event_DeltaTimeX;                           // 0x0018(0x0004)
	bool                                          CallFunc_IsDedicatedServer_ReturnValue;            // 0x001C(0x0001)
	uint8                                         Pad_1D[0x3];                                       // 0x001D(0x0003)
	class AActor*                                 CallFunc_GetOwningActor_ReturnValue;               // 0x0020(0x0008)
	class APrimalCharacter*                       K2Node_DynamicCast_AsPrimal_Character;             // 0x0028(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)
	uint8                                         Pad_31[0x7];                                       // 0x0031(0x0007)
	TArray<class APrimalBuff*>                    CallFunc_GetBuffs_TheBuffs;                        // 0x0038(0x0010)
	class APrimalBuff*                            CallFunc_Array_Get_Item;                           // 0x0048(0x0008)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0050(0x0004)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)
	class ABuff_DinoTekHelmet_Base_C*             K2Node_DynamicCast_AsBuff_Dino_Tek_Helmet_Base;    // 0x0058(0x0008)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0060(0x0001)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x0061(0x0001)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0062(0x0001)
};

// Function tek_tapejara_RIG_AnimBP.tek_tapejara_RIG_AnimBP_C.BlueprintUpdateAnimation
// 0x0004 (0x0004 - 0x0000)
struct tek_tapejara_RIG_AnimBP_C_BlueprintUpdateAnimation final
{
public:
	float                                         DeltaTimeX;                                        // 0x0000(0x0004)
};

// Function tek_tapejara_RIG_AnimBP.tek_tapejara_RIG_AnimBP_C.AnimGraph
// 0x0010 (0x0010 - 0x0000)
struct tek_tapejara_RIG_AnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              AnimGraph_0;                                       // 0x0000(0x0010)
};

}

