#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TeleportDestinationActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TeleportDestinationActor.TeleportDestinationActor_C
// 0x0030 (0x04C0 - 0x0490)
class ATeleportDestinationActor_C final : public AActor
{
public:
	class UArrowComponent*                        ForwardArrow;                                      // 0x0490(0x0008)
	class UTextRenderComponent*                   TitleComp;                                         // 0x0498(0x0008)
	class UTextRenderComponent*                   DestinationTitleComp;                              // 0x04A0(0x0008)
	class UBillboardComponent*                    DestinationIcon;                                   // 0x04A8(0x0008)
	class FString                                 DestinationTitle;                                  // 0x04B0(0x0010)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("TeleportDestinationActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"TeleportDestinationActor_C")
	}
	static class ATeleportDestinationActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ATeleportDestinationActor_C>();
	}
};

}

