#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TPV_GrenadeLauncher_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK
{

// ScriptStruct TPV_GrenadeLauncher_AnimBP.TPV_GrenadeLauncher_AnimBP_C.AnimBlueprintGeneratedConstantData
// 0x0A9F (0x0AA0 - 0x0001)
struct TPV_GrenadeLauncher_AnimBP::FAnimBlueprintGeneratedConstantData final : public FAnimBlueprintConstantData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	class FName                                   __NameProperty_318;                                // 0x0004(0x0008)
	int32                                         __IntProperty_319;                                 // 0x000C(0x0004)
	class FName                                   __NameProperty_320;                                // 0x0010(0x0008)
	int32                                         __IntProperty_321;                                 // 0x0018(0x0004)
	class FName                                   __NameProperty_322;                                // 0x001C(0x0008)
	int32                                         __IntProperty_323;                                 // 0x0024(0x0004)
	class FName                                   __NameProperty_324;                                // 0x0028(0x0008)
	int32                                         __IntProperty_325;                                 // 0x0030(0x0004)
	class FName                                   __NameProperty_326;                                // 0x0034(0x0008)
	int32                                         __IntProperty_327;                                 // 0x003C(0x0004)
	class FName                                   __NameProperty_328;                                // 0x0040(0x0008)
	int32                                         __IntProperty_329;                                 // 0x0048(0x0004)
	class FName                                   __NameProperty_330;                                // 0x004C(0x0008)
	int32                                         __IntProperty_331;                                 // 0x0054(0x0004)
	class FName                                   __NameProperty_332;                                // 0x0058(0x0008)
	int32                                         __IntProperty_333;                                 // 0x0060(0x0004)
	class FName                                   __NameProperty_334;                                // 0x0064(0x0008)
	int32                                         __IntProperty_335;                                 // 0x006C(0x0004)
	class FName                                   __NameProperty_336;                                // 0x0070(0x0008)
	int32                                         __IntProperty_337;                                 // 0x0078(0x0004)
	class FName                                   __NameProperty_338;                                // 0x007C(0x0008)
	int32                                         __IntProperty_339;                                 // 0x0084(0x0004)
	class FName                                   __NameProperty_340;                                // 0x0088(0x0008)
	int32                                         __IntProperty_341;                                 // 0x0090(0x0004)
	bool                                          __BoolProperty_342;                                // 0x0094(0x0001)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)
	float                                         __FloatProperty_343;                               // 0x0098(0x0004)
	struct FInputScaleBiasClampConstants          __StructProperty_344;                              // 0x009C(0x002C)
	float                                         __FloatProperty_345;                               // 0x00C8(0x0004)
	bool                                          __BoolProperty_346;                                // 0x00CC(0x0001)
	EAnimSyncMethod                               __EnumProperty_347;                                // 0x00CD(0x0001)
	EAnimGroupRole                                __ByteProperty_348;                                // 0x00CE(0x0001)
	uint8                                         Pad_CF[0x1];                                       // 0x00CF(0x0001)
	class FName                                   __NameProperty_349;                                // 0x00D0(0x0008)
	struct FAnimNodeFunctionRef                   __StructProperty_350;                              // 0x00D8(0x0020)
	class FName                                   __NameProperty_351;                                // 0x00F8(0x0008)
	class FName                                   __NameProperty_352;                                // 0x0100(0x0008)
	struct FAnimSubsystem_PropertyAccess          AnimBlueprintExtension_PropertyAccess;             // 0x0108(0x0080)
	struct FAnimSubsystem_Base                    AnimBlueprintExtension_Base;                       // 0x0188(0x0018)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_18;            // 0x01A0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_17;            // 0x01D0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_16;            // 0x0200(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_15;            // 0x0230(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_14;            // 0x0260(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_13;            // 0x0290(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_12;            // 0x02C0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_11;            // 0x02F0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_10;            // 0x0320(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_9;             // 0x0350(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_8;             // 0x0380(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_7;             // 0x03B0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_6;             // 0x03E0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_5;             // 0x0410(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_4;             // 0x0440(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_3;             // 0x0470(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_2;             // 0x04A0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult_1;             // 0x04D0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_TransitionResult;               // 0x0500(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_12;              // 0x0530(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_11;                 // 0x0560(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_11;              // 0x0590(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_10;                 // 0x05C0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_10;              // 0x05F0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_9;                  // 0x0620(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_9;               // 0x0650(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_8;                  // 0x0680(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_8;               // 0x06B0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_7;                  // 0x06E0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_7;               // 0x0710(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_6;                  // 0x0740(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_6;               // 0x0770(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_5;                  // 0x07A0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_5;               // 0x07D0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_4;                  // 0x0800(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_4;               // 0x0830(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_3;                  // 0x0860(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_3;               // 0x0890(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_2;                  // 0x08C0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_2;               // 0x08F0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult_1;                  // 0x0920(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer_1;               // 0x0950(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateResult;                    // 0x0980(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_StateMachine;                   // 0x09B0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_SequencePlayer;                 // 0x09E0(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_ApplyAdditive;                  // 0x0A10(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Slot;                           // 0x0A40(0x0030)
	struct FAnimNodeExposedValueHandler_PropertyAccess AnimGraphNode_Root;                           // 0x0A70(0x0030)
};

// ScriptStruct TPV_GrenadeLauncher_AnimBP.TPV_GrenadeLauncher_AnimBP_C.AnimBlueprintGeneratedMutableData
// 0x001B (0x001C - 0x0001)
struct TPV_GrenadeLauncher_AnimBP::FAnimBlueprintGeneratedMutableData final : public FAnimBlueprintMutableData
{
public:
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	float                                         __FloatProperty;                                   // 0x0004(0x0004)
	float                                         __FloatProperty_0;                                 // 0x0008(0x0004)
	float                                         __FloatProperty_1;                                 // 0x000C(0x0004)
	float                                         __FloatProperty_2;                                 // 0x0010(0x0004)
	float                                         __FloatProperty_3;                                 // 0x0014(0x0004)
	float                                         __FloatProperty_4;                                 // 0x0018(0x0004)
};

}

