#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Volcanic_Eruption_Hazard

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Buff_Base_AoE_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass Volcanic_Eruption_Hazard.Volcanic_Eruption_Hazard_C
// 0x0398 (0x0F90 - 0x0BF8)
class AVolcanic_Eruption_Hazard_C final : public ABuff_Base_AoE_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_Volcanic_Eruption_Hazard_C;         // 0x0BF8(0x0008)
	class UAudioComponent*                        EruptionCue;                                       // 0x0C00(0x0008)
	float                                         __1_NewTrack_0_69D12E4C43490FFB8500909865D5D6F2;   // 0x0C08(0x0004)
	ETimelineDirection                            __1__Direction_69D12E4C43490FFB8500909865D5D6F2;   // 0x0C0C(0x0001)
	uint8                                         Pad_C0D[0x3];                                      // 0x0C0D(0x0003)
	class UTimelineComponent*                     Zero_1;                                            // 0x0C10(0x0008)
	double                                        FloodingPreview;                                   // 0x0C18(0x0008)
	TArray<struct FTransform>                     FloodingCompartmentZones;                          // 0x0C20(0x0010)
	double                                        TimeLastEvent;                                     // 0x0C30(0x0008)
	double                                        TimeBetweenEvents;                                 // 0x0C38(0x0008)
	bool                                          AnyEventActive;                                    // 0x0C40(0x0001)
	uint8                                         Pad_C41[0x7];                                      // 0x0C41(0x0007)
	double                                        LengthOfEvent;                                     // 0x0C48(0x0008)
	struct FTransform                             ProjectileLaunchLocation;                          // 0x0C50(0x0060)
	TArray<class APhysicsVolume*>                 LavaPhxVolumes;                                    // 0x0CB0(0x0010)
	TArray<class APostProcessVolume*>             LavaPPVolumes;                                     // 0x0CC0(0x0010)
	double                                        MeshUnitScale;                                     // 0x0CD0(0x0008)
	double                                        CurrentFloodingValue;                              // 0x0CD8(0x0008)
	double                                        FloodIncrement;                                    // 0x0CE0(0x0008)
	double                                        ClientFloodValue;                                  // 0x0CE8(0x0008)
	TArray<class UStaticMeshComponent*>           LavaPlanes;                                        // 0x0CF0(0x0010)
	double                                        ClientFloodInterp;                                 // 0x0D00(0x0008)
	double                                        FloodDecrement;                                    // 0x0D08(0x0008)
	TArray<double>                                AreaOfCompartments;                                // 0x0D10(0x0010)
	double                                        SizeToStartStaggerDividingDamageLookupsSquared;    // 0x0D20(0x0008)
	int32                                         StaggerDivisionPower;                              // 0x0D28(0x0004)
	uint8                                         Pad_D2C[0x4];                                      // 0x0D2C(0x0004)
	TArray<int32>                                 StaggerBoxCountPerZone;                            // 0x0D30(0x0010)
	int32                                         BoxCountInt;                                       // 0x0D40(0x0004)
	bool                                          UsePerBoxAreaDivisionMultiplier;                   // 0x0D44(0x0001)
	uint8                                         Pad_D45[0x3];                                      // 0x0D45(0x0003)
	int32                                         AbsolouteMaxDivision;                              // 0x0D48(0x0004)
	int32                                         CompartmentWaterlineIndexPreview;                  // 0x0D4C(0x0004)
	bool                                          IsUpdatingTimeLineData;                            // 0x0D50(0x0001)
	uint8                                         Pad_D51[0x7];                                      // 0x0D51(0x0007)
	TArray<struct FVector>                        StagedOverlapCheckPOS;                             // 0x0D58(0x0010)
	TArray<struct FVector>                        StagedOverlapCheckExtent;                          // 0x0D68(0x0010)
	TArray<class AActor*>                         ActorsToBeDamaged;                                 // 0x0D78(0x0010)
	double                                        MinFloodValue;                                     // 0x0D88(0x0008)
	bool                                          UseFlooding;                                       // 0x0D90(0x0001)
	uint8                                         Pad_D91[0x7];                                      // 0x0D91(0x0007)
	struct FRotator                               AROT;                                              // 0x0D98(0x0018)
	struct FRotator                               BROT;                                              // 0x0DB0(0x0018)
	class UParticleSystem*                        Plume_PS;                                          // 0x0DC8(0x0008)
	bool                                          UseRockslideActivation;                            // 0x0DD0(0x0001)
	uint8                                         Pad_DD1[0x7];                                      // 0x0DD1(0x0007)
	TArray<class AHazardTrigger_Slide_C*>         SlidesToTrigger;                                   // 0x0DD8(0x0010)
	TArray<class ABiomeZoneVolume*>               BiomeVolumes;                                      // 0x0DE8(0x0010)
	TArray<class ATogglePainVolume*>              PainVolumesImmediate;                              // 0x0DF8(0x0010)
	double                                        DelayAfterWarmUpMatinee;                           // 0x0E08(0x0008)
	bool                                          WarmUpActive;                                      // 0x0E10(0x0001)
	uint8                                         Pad_E11[0x7];                                      // 0x0E11(0x0007)
	double                                        BiomeTempMulti;                                    // 0x0E18(0x0008)
	bool                                          SkipFirstPlayDelay;                                // 0x0E20(0x0001)
	uint8                                         Pad_E21[0x7];                                      // 0x0E21(0x0007)
	class AShooterMatineeActor*                   WarmUpMatinee;                                     // 0x0E28(0x0008)
	class AShooterMatineeActor*                   EruptionMatinee;                                   // 0x0E30(0x0008)
	class AShooterMatineeActor*                   CooldownMatinee;                                   // 0x0E38(0x0008)
	class AShooterMatineeActor*                   FalseStartMatinee;                                 // 0x0E40(0x0008)
	double                                        CurrentMatineeStartTime;                           // 0x0E48(0x0008)
	bool                                          PlayedWarmup;                                      // 0x0E50(0x0001)
	bool                                          PlayedEruption;                                    // 0x0E51(0x0001)
	bool                                          PlayedCooldown;                                    // 0x0E52(0x0001)
	uint8                                         Pad_E53[0x5];                                      // 0x0E53(0x0005)
	TArray<class ATogglePainVolume*>              PainVolumesStage1;                                 // 0x0E58(0x0010)
	double                                        PainVolumesStage1_Delay;                           // 0x0E68(0x0008)
	TArray<class ATogglePainVolume*>              PainVolumesStage2;                                 // 0x0E70(0x0010)
	double                                        PainVolumesStage2_Delay;                           // 0x0E80(0x0008)
	double                                        WarningTickDamage;                                 // 0x0E88(0x0008)
	double                                        EruptionTickDamage;                                // 0x0E90(0x0008)
	bool                                          TriggeredVolumes;                                  // 0x0E98(0x0001)
	uint8                                         Pad_E99[0x7];                                      // 0x0E99(0x0007)
	double                                        CurrentVolumeDamage;                               // 0x0EA0(0x0008)
	bool                                          PlayedFalseStartSequence;                          // 0x0EA8(0x0001)
	uint8                                         Pad_EA9[0x3];                                      // 0x0EA9(0x0003)
	int32                                         FalseStartInt;                                     // 0x0EAC(0x0004)
	double                                        LengthOfFalseStart;                                // 0x0EB0(0x0008)
	int32                                         MaxFalseStarts;                                    // 0x0EB8(0x0004)
	bool                                          UseOilVentActivation;                              // 0x0EBC(0x0001)
	uint8                                         Pad_EBD[0x3];                                      // 0x0EBD(0x0003)
	TArray<class AOilVent_BP_C*>                  VentsToTrigger;                                    // 0x0EC0(0x0010)
	double                                        Chance_to_target_player;                           // 0x0ED0(0x0008)
	TArray<class AShooterCharacter*>              Players_Close_To_Volcano;                          // 0x0ED8(0x0010)
	struct FVector                                Rotator_to_add;                                    // 0x0EE8(0x0018)
	double                                        TargetedMeteorVariance;                            // 0x0F00(0x0008)
	TArray<struct FVector>                        TestVector_0;                                      // 0x0F08(0x0010)
	int32                                         AreaToTest;                                        // 0x0F18(0x0004)
	uint8                                         Pad_F1C[0x4];                                      // 0x0F1C(0x0004)
	double                                        MinGravity;                                        // 0x0F20(0x0008)
	double                                        MaxGravity;                                        // 0x0F28(0x0008)
	double                                        GravityScaleDivisor;                               // 0x0F30(0x0008)
	double                                        GravityScale_Offset;                               // 0x0F38(0x0008)
	double                                        TargetedMeteorVarianceHorizontal_Strength;         // 0x0F40(0x0008)
	class USoundCue*                              EruptionSoundCue;                                  // 0x0F48(0x0008)
	class USoundCue*                              ProjSoundCue;                                      // 0x0F50(0x0008)
	class ALevelSequenceActor*                    WarmUpSequence;                                    // 0x0F58(0x0008)
	class ALevelSequenceActor*                    EruptionSequence;                                  // 0x0F60(0x0008)
	class ALevelSequenceActor*                    CooldownSequence;                                  // 0x0F68(0x0008)
	class ALevelSequenceActor*                    FalseStartSequence;                                // 0x0F70(0x0008)
	class AActor*                                 WeatherSystem;                                     // 0x0F78(0x0008)
	bool                                          Why;                                               // 0x0F80(0x0001)

public:
	void UserConstructionScript();
	void UpdateNearbyPlayers();
	void UpdateFloodingVisuals(double FloodValue);
	void TriggerVolcano();
	void ToggleSaggeredPainVolumes(bool Enable, bool SkipDealy, double TickDamage);
	void SyncNewPlayer();
	void SpawnLavaBomb();
	void SetNewBlendableInt(double Intensity);
	void SetMatineeSyncTime();
	void ReceiveBeginPlay();
	void ProjectileLaunchSFV();
	void OnShootLavaBombs();
	void ModulateLavaFlooding(double Increment);
	void Get_Damage_Bounds_and_Lava_Plane_from_Transform(const struct FTransform& CompartmentZoneTransform, double Flood_Value, struct FVector* DmgBoxCenter, struct FVector* DmgBoxExtent, struct FTransform* LavaPlaneTransform);
	void ExecuteUbergraph_Volcanic_Eruption_Hazard(int32 EntryPoint);
	void Earthquake(bool Remove);
	void CreateSubBoxVolumes(const struct FVector& BoxLocation, const struct FVector& BoxExtents, int32 divisionPower);
	void ClientWarmUpMatinee();
	void ClientFalseStartMatinee();
	void ClientEruptionMatinee();
	void ClientCooldownMatinee();
	void ClientAudio(bool Audible);
	void CheckDamageArea();
	void BuffTickServer(float DeltaTime);
	void AdjustBiomeTemp(bool Reset);
	void ActivateRockSlides();
	void ActivateOilVents();
	void Zero_1__UpdateFunc();
	void Zero_1__FinishedFunc();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("Volcanic_Eruption_Hazard_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"Volcanic_Eruption_Hazard_C")
	}
	static class AVolcanic_Eruption_Hazard_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AVolcanic_Eruption_Hazard_C>();
	}
};

}

