#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VRBossTargetBeamComponent_BP

#include "Basic.hpp"

#include "VRBossTargetBeamComponent_BP_classes.hpp"
#include "VRBossTargetBeamComponent_BP_parameters.hpp"


namespace SDK
{

// Function VRBossTargetBeamComponent_BP.VRBossTargetBeamComponent_BP_C.StartFiring
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVRBossTargetBeamComponent_BP_C::StartFiring()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VRBossTargetBeamComponent_BP_C", "StartFiring");

	UObject::ProcessEvent(Func, nullptr);
}


// Function VRBossTargetBeamComponent_BP.VRBossTargetBeamComponent_BP_C.StartCharging
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UVRBossTargetBeamComponent_BP_C::StartCharging()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("VRBossTargetBeamComponent_BP_C", "StartCharging");

	UObject::ProcessEvent(Func, nullptr);
}

}

