#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VRMainBossBeamSettings

#include "Basic.hpp"

#include "VRMainBossBeamType_structs.hpp"


namespace SDK
{

// UserDefinedStruct VRMainBossBeamSettings.VRMainBossBeamSettings
// 0x0008 (0x0008 - 0x0000)
struct FVRMainBossBeamSettings final
{
public:
	EVRMainBossBeamType                           BeamType_2_E78EA94546605BF43113DDAB6F88B5CC;       // 0x0000(0x0001)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)
	float                                         BeamWeight_14_F9C0E751450F73DC35E58C93C07CED42;    // 0x0004(0x0004)
};

}

