#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_BountyNotificationBP

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_BountyNotificationBP.W_BountyNotificationBP_C.ExecuteUbergraph_W_BountyNotificationBP
// 0x0004 (0x0004 - 0x0000)
struct W_BountyNotificationBP_C_ExecuteUbergraph_W_BountyNotificationBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)
};

}

