#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WaterSplashEmitter_Ichthyornis

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WaterSplashEmitter_Ichthyornis.WaterSplashEmitter_Ichthyornis_C
// 0x0000 (0x05C8 - 0x05C8)
class AWaterSplashEmitter_Ichthyornis_C final : public APrimalEmitterSpawnable
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WaterSplashEmitter_Ichthyornis_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WaterSplashEmitter_Ichthyornis_C")
	}
	static class AWaterSplashEmitter_Ichthyornis_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWaterSplashEmitter_Ichthyornis_C>();
	}
};

}

