#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WyvernPoisonImpactEmitter

#include "Basic.hpp"

#include "ExplosionEmitter_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WyvernPoisonImpactEmitter.WyvernPoisonImpactEmitter_C
// 0x0000 (0x05C8 - 0x05C8)
class AWyvernPoisonImpactEmitter_C final : public AExplosionEmitter_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WyvernPoisonImpactEmitter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WyvernPoisonImpactEmitter_C")
	}
	static class AWyvernPoisonImpactEmitter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AWyvernPoisonImpactEmitter_C>();
	}
};

}

